### ISSUE TITLE
Money Vocabulary

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#1]
We still need vocabularies for:
  * types of price, especially:
    * starting price
    * reserve price
    * estimated price
  * currencies
    * modern day (ISO4217)
    * [historical](https://en.wikipedia.org/wiki/List_of_historical_currencies)

**Comment by azaroth42** [comment]
Patricia seems happy to have a currency section in AAT.

**Comment by workergnome** [comment]
Great.  One less thing for us to build.

**Comment by azaroth42** [comment]
Patricia has added these, so now a vocabulary issue only.

**Comment by azaroth42** [comment]
To the extent that we need vocabulary in linked art, these are done as Patricia has them all in AAT. Closing.
