### ISSUE TITLE
Appellations cannot have Languages

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#103]
Because Appellation is a subClass of Symbolic Object and not Linguistic Object. Titles (which we don't use) can have Languages, as they're also a child of Linguistic Object, but that doesn't solve the issue for anything other than "Works".  For example, an Appellation of a Concept could not have a language as the Concept is not a work according to the scope notes of Title. Also People can have names in different languages, as can Places, and practically everything else.

Options:
 * Create a new property, with range of Appellation and domain of Language that quacks just like P72 has language
 * Introduce a new Name class which is a sub class of both Appellation and Linguistic Object.
 * Not associate languages with Appellations at all
 * Ignore the scope notes for Title and use it always
 * Use rdf:langStrings for the value of the Appellation, represented in JSON-LD 1.1 as e.g. `{"en": "Name", "fr": "Nom"}`

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-6c417eb18c6a4d07876b46e6f33f4488/page-1)

**Comment by azaroth42** [comment]
Advice from the SIG:  Just use multiple instantiation (e.g. the instance is an Appellation and a Linguistic Object) or create your own class as a subclass of both.

While I had thought of multiple instantiation, I didn't put it as an option because of the implementation difficulty.  I think the realistic options are, in preference order:

1. Adopt JSON-LD 1.1 and use rdf:langString (needs implementation work up front)
2. Create a Name class with both as parents 

New properties would be horrible in JSON-LD 1.0 as there would be two keys that should both be called `language`. See also `value` and `has_value`. langString would also be horrible in 1.0 as we'd need to use the `{@language, @value}` pattern because rdf:value isn't always linguistic, or even a string. With 1.1 we can customize when it's a string and when not.  Not associating language just doesn't work, as there are many multi-lingual names. Abusing Title also doesn't work, as it wouldn't interoperate at all with other/existing data.

**Comment by azaroth42** [comment]
Proposal is to create a new Name class, which is subClassOf Appellation and LinguisticObject, as agreed by the SIG.
We would then recommend its use everywhere that Appellation is used, other than Identifier.

**Comment by workergnome** [comment]
Agreed.  We should figure out how to assign, document, and provide derefencable URIs for things like this.
