### ISSUE TITLE
Clarify scope is only externally published data

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#104]
And not internal business data.  Internal logics can use whatever system you want, we're concerned with interoperability between systems.

For example, in order to have Move as a class that gets used, there would need to be a Move that is not better described as a Transfer of Custody, that institutions want to publish to the world.

**Comment by workergnome** [comment]
Not 100% sure I agree with that scope.  Is it a correct assumption that we are only interested in public data, or are we also interested in interoperable-but-private data such as loan records, where both institutions involved might be interested, but the data would not be public?

**Comment by azaroth42** [comment]
I would say that we're interested, at the current time, in specifying how shareable information is represented, without precluding private data from being managed in a compatible way. We're already boiling a sizable pond!

**Comment by azaroth42** [comment]
I think the goal of the work is interoperability between systems, not a theoretical model. We already have one of those :) The goal is not to build a single piece of software, but to enable many implementations to interact across system and institutional boundaries.

Given that as the goal, I think the following would be in scope for the data model part:

* A (semantic) profile of classes and relationships with CIDOC-CRM as the core ontology that a developer can expect to interact with across system or institutional boundaries, via defined protocols and APIs, including ... 
  * requirements for presence of classes and relationships (MUST / SHOULD / MUST NOT)
  * cardinality of relationships (1:1 / 1:* / *:*)

Bearing in mind the [design principles](http://linked.art/model/profile/), such as design for JSON-LD, avoid technology dependency, and so forth.

Data that requires authentication to access but is still accessible beyond the organization would thus be in scope.  E.g. open access is not a requirement, but publishing on the web somehow is. If it's not on the web, then it doesn't exist.

Meaning that out of scope would include:

* Management/production of the data, as a system specific concern. For example, it is not in scope to require that data using the model must be managed in a triplestore. This would violate the technology independency principle.
* Internal only patterns are a method of managing data. If an organization wants to use (e.g.) `crm:Image` internally and expose a linked.art compatible profile, it would remap the class on the way out to `crm:VisualItem`.  Equally, internally the data might be managed with multiple instantiation, but externally it is mapped out to one of the join classes in the linked art ontology. We should not mandate how the result is accomplished, just the end result.

**Comment by azaroth42** [comment]
Closed by #172
