### ISSUE TITLE
Consider Move for when museum owns exhibited item

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#105]
When an object that is owned by the museum hosting an exhibition is used as part of the exhibition, it would be good to have an equivalent activity for the Transfer of Custody for loan objects.

Consider:
    http://linked.art/model/exhibition/#exhibition-provenance-transfer-of-custody

As no custody is transferred, this would imply only a change of location, which is the Move activity currently in the "no use cases" bucket.

Proposal is to add an exhibition section following transfer of custody with this situation.  Thread on CRM-SIG list: http://lists.ics.forth.gr/pipermail/crm-sig/2017-October/003117.html

**Comment by workergnome** [comment]
I think all provenance events (including exhibitions, sales, etc) could potentially have moves associated with them.  The location of the artwork is important—it has been excluded in Art Tracks due to complications with the text-parsing model, but was explicitly called out as important in it.

**Comment by azaroth42** [comment]
Closed by #173
