### ISSUE TITLE
Web Pages should be Linguistic Objects

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#112]
As it's highly unlikely they contain no text whatsoever, even a title.

**Comment by azaroth42** [comment]
... but do we care about their language?

**Comment by azaroth42** [comment]
... yes because it's otherwise totally inconsistent with #111.

**Comment by workergnome** [comment]
Just to be difficult--what do we do with internationalized web pages, that can be in many languages?

**Comment by azaroth42** [comment]
At the moment we haven't actually given an example of `language`.  Do we expect it to be singular or multiple? If it's multiple, I question how much use the information actually is, as you couldn't tell whether the page was mostly English with some Latin, or mostly Latin with a few English words here and there. 

If the page handles language negotiation correctly, then there'll be a different URL for each language, and I would propose to follow https://github.com/IIIF/api/issues/942 and reference each individually.

**Comment by azaroth42** [comment]
Re-closing, nothing that there is an ongoing issue that CRM is terrible at describing digital "things" that can change state, or have multiple states at the same time.  There is the thing that is the home page of an object, and the linguistic content that is carried by that thing, in the same way that books can carry text.  The current pattern avoids the complexity, but conflates issues that will likely need to be teased apart in the future.
