### ISSUE TITLE
Add a classification for digital files for clarity

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#114]
Images can remain instances of `VisualItem`, but we need to be able to easily distinguish the conceptual visual item that an artwork shows (the "work") and a digital image file.
I propose:  http://vocab.getty.edu/aat/300215302

(modulo discussion with Patricia about the photograph parent concept, otherwise it might need to be electronic images, aat:300237904)

**Comment by mdlincoln** [comment]
Would this mean VisualItem (of type digital image) > depicts MMO > bears VisualItem (the concept)?

**Comment by azaroth42** [comment]
Ha, @workergnome and I were just walking through this yesterday.  I haven't updated the docs (but have heard from Patricia that she'll remove the BT of Photograph).

The MMO `shows` a VI that's the image carried by the object (the same way an MMO can carry the text of a book).
The MMO has a `representation` which is a VI that's a digital image.

Or to flip to your ordering ... the image VI represents the MMO which shows work VI.

The digital image can't also `show` the VI of the MMO, as the domain is Physical Man-Made Thing ... and Visual Items are of course not physical things. But the file VI can be the `representation` of the work VI, as `representation` has a domain of any CRM resource (E1 Entity).  Whether we actually instantiate that representation is another question, as it seems confusing for little gain.

Thus, given the dual nature of Visual Items, adding a classification to distinguish between the "work" like VIs and the "file" like VIs seems prudent.

**Comment by mdlincoln** [comment]
OK! That makes sense - I'm thinking (as I'm sure you both are) of the photoarchive context where photographs often show additional installation context that we want to distinguish from the MMO being depicted (and perhaps be able to connect to something like a IIIF bounding box annotation)

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-bd6cbb7d6906489f987a38e34746e7f5/page-1)
