### ISSUE TITLE
Model "narratives" containing items

### ISSUE THREAD

**Issue by Conal-Tuohy** [linked-art/linked.art#124]
Some datasets include "narratives" (alternatively, "sets", "lists", "aggregations", "stories") in which one or more blocks of text are interspersed with references to collection objects in a sequence.

It would be good to have support for this in the Linked Art model.

For example, this website renders (as "Sets") aggregations produced by the National Museum of Australia which they call "narratives" internally:
* http://collectionsearch.nma.gov.au/sets

The national metadata aggregators Trove and DigitalNZ provide their users with the ability to create similar data structures:
* Trove Lists [search](https://trove.nla.gov.au/list/result), [about](https://trove.nla.gov.au/list?q=)
* DigitalNZ Stories [search](https://digitalnz.org/records?tab=Stories&text=), [about](https://digitalnz.org/help/how-to-save-items-and-make-stories)

I have an example of rendering DigitalNZ stories as ORE Aggregations here:
* A source "story": https://digitalnz.org/stories/56e8e470fb002c527c0004ce
* As ORE Aggregation: https://oceania.digital/digitalnz-story/56e8e470fb002c527c0004ce

**Comment by Conal-Tuohy** [comment]
discussed in Slack https://linked-art.slack.com/archives/C50AP8USG/p1516664518000203

**Comment by Conal-Tuohy** [comment]
The desired model should also include CRM linguistic objects that refer to the collection objects.

**Comment by Conal-Tuohy** [comment]
Museum Victoria has "articles": https://collections.museumvictoria.com.au/developers#articles-api-by-id

**Comment by Conal-Tuohy** [comment]
Te Papa Tongarewa (the National Museum of New Zealand) has "topics": https://github.com/te-papa/collections-api/wiki/Collections-API-Object-Model#topic

**Comment by azaroth42** [comment]
Is this covered with the Aggregation pattern in Collections?

**Comment by Conal-Tuohy** [comment]
Yes, we have implemented these as `ore:Aggregation` resources, and happy with that.
