### ISSUE TITLE
missing languages

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#128]
At least:

* Spanish
* Japanese
* Greek

**Comment by azaroth42** [comment]
These are from issues with AAT's triples -- they are owl:sameAs other languages, which creates a multitude of problems.  It is in the process of being resolved in the source data, and this is blocked until then.

**Comment by Conal-Tuohy** [comment]
BTW, while talking to a linguist colleague yesterday, I learned that linguists generally consider "glottolog" to be the best source of language identifiers. Here is the Aussie language Nyunga (one of the ones I spotted was missing from AAT, among many others): http://glottolog.org/resource/languoid/id/nyun1247

NB HTTP content negotiation will yield an RDF graph containing SKOS, including links to ISO 639.

**Comment by azaroth42** [comment]
Closing this issue in favor of discussion in #110. The underlying issue (e.g. that AAT had bizarre owl:sameAs statements) has been fixed ... however we need to discuss if we actually want to use contexts to alias languages to codes.
