### ISSUE TITLE
Create Ontology File for LinkedArt (la.rdf)

### ISSUE THREAD

**Issue by kateblanch** [linked-art/linked.art#131]
Hello, we are currently generating data models and LA-compliant JSON for 3 museums. Since we are using the linked art model, it would be a great tool to have an .RDF file for the LA ontology available for ingest into the mapping/modeling tools. 

Here is an example of somthing similar for frbroo - http://www.cidoc-crm.org/frbroo/sites/default/files/FRBR2.4-draft.rdfs.

I'm sorry that I don't know what the level of effort is to produce an .rdfs for LA but I would be happy to assist in any way I can. 
Thanks!

**Comment by azaroth42** [comment]
https://linked.art/ns/terms/linkedart.xml
