### ISSUE TITLE
Use JSON-LD 1.1

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#137]
When this hits:
  https://github.com/digitalbazaar/pyld/pull/76 

We can update to using JSON-LD 1.1 features.

In particular:

- [x] Use `part` for all partitioning (scoped contexts per class to get to right predicate)
- [x] Use P91_has_value instead of rdf:value for Dimensions (scoped contexts to get to `value`)

**Comment by Conal-Tuohy** [comment]
How ready are consumers in general for these JSON-LD features? Are they supported ok?

**Comment by azaroth42** [comment]
There's support for 1.1 in Javascript, Python and Ruby, for consumers or producers.

I also don't think most consumers will do anything other than use the JSON structure directly. The issues above should be fixed in CRM (but never will be, c.f. recent rdf:value discussion on the SIG list), so we can work around them with scoped contexts.

**Comment by Conal-Tuohy** [comment]
Is the json-ld-java support lagging? Just curious, since Java is more my kettle of fish

**Comment by Conal-Tuohy** [comment]
To answer my own question, it does indeed seem as if jsonld-java is lagging in support for JSON-LD 1.1

https://github.com/jsonld-java/jsonld-java/issues/219

**Comment by azaroth42** [comment]
It's not even a final CG draft yet, but unless we've grossly misjudged the appetite in the W3C, we should have a WG approved in the next few months: https://json-ld.github.io/charter/

Hopefully the Java support will come during the WG phase.

**Comment by Conal-Tuohy** [comment]
I am working on the JSON-LD serialization right now, for the NMA project, with a view to a beta version due in a couple of weeks. So I will need to leave JSON-LD 1.1 out, obviously, but it may be that the Linked Art context we use will end up changing, around about the end of our project, which is a bit awkward, and something we will need to manage. Were you hoping that Linked Art would adopt JSON-LD 1.1 _before_ the WG was approved, or ... ? My preference would be to wait until JSON-LD 1.1 is a Recommendation, but I've no idea how much of a delay that would impose (though I'm guessing it could come shortly after a WG was approved, if much of the theoretical work was already done?)

**Comment by cbutcosk** [comment]
I came across a small speed bump related to this: the new JSON-LD context [breaks RDFLib's JSON-LD serialization](https://github.com/RDFLib/rdflib-jsonld/issues/54). Added bonus: whoever raised that issue was trying to consume the linked.art context!

Is it worth emitting a 1.0-compliant context for legacy frameworks? Or at least documenting that certain frameworks will not be able to consume the context?

**Comment by azaroth42** [comment]
Update -- W3C has created the JSON-LD 1.1 working group, chartered to get a new version done over the next 2 years. I'm one of two co-chairs, and we see a lot of interest in the work. We're ahead of the implementation curve, but in a good position to ensure that the features are present which we need.

Here is my PyLD plus rdflib code that translates from JSON-LD 1.1 to Turtle:
  https://github.com/linked-art/linked.art/blob/master/extensions/text.py#L268-L275

**Comment by azaroth42** [comment]
`value` is now no longer needed for strings, as we have `P190_has_symbolic_content`, which maps to `content` in the JSON. So this issue can be closed :)

It does break 1.0 only processors, but there's engagement from the major library developers that they will update, including python, ruby, javascript and (I believe) java. The PyLD library already works with the needed features for 1.1, and there's a relatively easy translation path over to RDFLib until it is natively supported.
