### ISSUE TITLE
Reconsider curation in light of Aggregations

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#151]
And whether it should be an Aggregation of Activities. 
Also whether the taking inventory activity should be linked to a temporal snapshot of the collection.

**Comment by azaroth42** [comment]
Aggregation of Activities doesn't have a start/end time, it's just a set. So the computation of the timespan of the ownership couldn't be associated with the Aggregation.  As the Aggregation is not ordered, you can't just take BotB of the first and EotE of the last entry, you'd need to work through every single aggregated activity to calculate.

Propose that curation is still an activity with included parts, rather than a set of distinct activities.

**Comment by workergnome** [comment]
Disagree--that means that every time someone adds a new curation activity, they have to update that information in two places--by adding the new activity, and then by recalculating the curation activity and updating the information about it--otherwise, information could be out of sync.  At the API level, that's probably something worth exposing, but as a data model, it seems like a bad idea to keep a calculated value stored as data.

**Comment by azaroth42** [comment]
I think that's the distinction that #104 is trying to make. Let's move model vs api discussion there.

**Comment by azaroth42** [comment]
If https://github.com/linked-art/linked.art/issues/104#issuecomment-400056836 is accepted, and the aggregation of events is not accessible outside of the data management system, then it's not in scope.  If it is accessible, then there should be one way to serialize the data to avoid duplication and extra work.

Thus ... 
> ... it seems like a bad idea to keep a calculated value stored as data.

is not a valid concern, as the storage is out of scope of the work. If it's a bad idea, or even an overly expensive good idea, then don't do that :) But if the interaction between systems should be able to get the timespan of the ownership "activity", then it needs to be in the model as such.

**Comment by workergnome** [comment]
It is in the model--it's just not instantiated as an explicit value.  I think my complaint is that a single piece of data is represented in two locations, and this means we can create inconsistent data.  "Don't do that" isn't a good principle for API design.  

At a more fundamental level, CIDOC-CRM is event-based, but ownership isn't an event--it's a state, and treating the duration and extent of states as a first-class entity is contrary to the representation of an event-based model.  We had this same discussion with provenance and ownership, as well as with the temporal snapshot conversation--in both cases, you can describe the events, or you can describe the states--but describing them both means you're instantiating two different theoretical ways of looking at the world.

**Comment by azaroth42** [comment]
It wouldn't be represented in two locations (Aggregation and ownership Activity), it would just be the values of the timespan associated with the Activity. Unless you mean the two locations as the earliest datetime of any aggregated/included activity and the bubbled up ownership activity?  It seems like we will always have that in practice, as there might be otherwise un-recorded events that contribute to the dating.

And I agree, of course, that CRM Activities are concerned with change of state. However there isn't a way to associate a Period with an object.  So I disagree that it's contrary to the model, otherwise there wouldn't be Period as a class. It might be contrary to the way we use the model, but until there's a resolution for inventory taking, unsold auction lots, and similar where there is evidence of state without a change of state, we have to use both ways.

**Comment by azaroth42** [comment]
#104 is closed, so closing this one. Physical storage is not a concern of the model or the API that materializes that model, but individual implementations. Data models do not need to be concerned with validity/integrity implementation details, but should express what those constraints are.

Closing, wontfix. The entire ownership of the object is not a set of discrete activities, it is a period-y-activity-thing that the CRM ontology does not deal well with that has those activities as part.
