### ISSUE TITLE
Model nationality and gender simply as types

### ISSUE THREAD

**Issue by Conal-Tuohy** [linked-art/linked.art#152]
https://linked.art/model/actor/index.html#person_11

A person could `crm:P2_has_type` a type with the label "British". This is simpler than creating an `ore:Aggregation` of British people and then labeling the Aggregation "British People" or something.

**Comment by azaroth42** [comment]
The rationale is that people are not inherently gendered nor of a particular nationality. I was a few months away from being a British citizen in 2008 (before scarpering to the US) and now am almost eligible for US citizenship (though I don't think I want it, these days).  These transitions mean joining a set of people.

That isn't quite the same as AttributeAssignment of a Type -- I'm not claiming British-ness by assigning metadata to myself, I'm actually participating in a test and subsequent little ritual where someone else assigns it to me.  Further, I can renounce citizenship, but you can't de-assign types.

The same applies to gender, in a non-binary non-biological sense.  This doesn't go so far as asserting that gender is an activity (e.g. the view that cross-dressing changes your gender temporarily) but that could be modeled by many Adds and Removes to the various gender Aggregations.

Finally, given the number of nationalities, it's more performant and technically reasonable to have a easy programmatic filter for the nationality of a person. If it was just a P2_has_type of aat:1234567, there's no way to determine what that particular Type is without prior knowledge. With the aggregation pattern, you find the aggregations that the person is a member of that have the nationality Type, and then look at the other type on the same aggregation.

Hopefully this is sufficient explanation :) Tagging `wontfix`, but feel free to reopen.

**Comment by Conal-Tuohy** [comment]
Thanks @azaroth42 ! 

I don't necessarily want to reopen this issue, since in our own project at NMA we haven't had to deal with this issue, since we're lacking the diachronic data (e.g. people changing their nationality), but I'm still curious about it. I can appreciate that P2_has_type is inadequate for modeling things that change over time (as nationality and gender can), but I'm curious as to how you would do that using Aggregation, i.e. how are the "Adds" and "Removes" you mentioned represented? They are not in the examples I linked to above, and I don't see anything obvious in the linked art context or ontology.

This is where, I think, the E74_Group class, which people can join and leave, is an appropriate concept. I have to say I'm less than convinced by the [argument](https://linked.art/model/actor/index.html#nationality) that E74_Group is inappropriate for nationalities because members of a nationality don't "take action as a single coherent entity". I don't see that requirement reflected in my reading of the scope notes for E74_Group (which, indeed, specifically approves of modeling nationalities using this class). I think it's rather peculiar to post that members of an E74_Group must act entirely coherently. The definition is a bit broader than that. For instance, it makes sense to me to say that "the British" have decided to leave the EU, or that "the Americans" elected Donald Trump president, even though the groups were pretty much evenly split on the question. 

BTW, on the point in your penultimate para, it's worth remembering that an instance of E55_Type is necessarily also an instance of E1_Entity and can therefore have a type of its own. e.g. if you _were_ to model "British" as an E55_Type, you could assign it its own type; "Nationality". So it seems to me that E55_Type is actually no different to Aggregation, in that respect. In the NMA dataset I know we have at least one of these "types of types"; in the source data we have "narratives" which have "audiences", and we are modeling the audiences as instances of E55_Type, and assigning them their own type which is http://vocab.getty.edu/aat/300192793 -- I'm not sure this is the best way to model it, but it's certainly schema-valid.

**Comment by azaroth42** [comment]
The documentation about Add and Remove (also for Collections of Objects!) is in progress.  I've been tied up with finalizing IIIF specs and the JSON-LD charter.

E74 is a subclass of E39 Actor:
> This class comprises people, either individually or in groups, who have the potential to perform
intentional actions of kinds for which someone may be held responsible. 

Temporality is (still) the issue rather than coherency. Dead people must still be part of the group lest they lose their nationality, and would make up an overwhelming majority. Yet dead people clearly take no intentional action and hence could not have participated in Brexit. This is further complicated by nationalities that no longer exist, but their constituents do. There are no citizens of West Germany today, yet people who were West Germans are still alive and would still be in the Group.  Compare de-accessioning of objects from a collection -- we need to know that the painting was part of the collection and is not now.

Agreed that Types can have Types ... the issue with doing that is that we're using AAT terms as those Types. That would mean making assertions about those resources, that the resources do not themselves make. This seems like bad practice, and at the very least complicates the data management. Agree that it's valid according to the ontology, and that if we were managing our own vocabularies directly in CRM, it would be relatively achievable.

**Comment by azaroth42** [comment]
Thinking this through with respect to the design principles, it's maybe worth considering the cost/benefit.

**Comment by azaroth42** [comment]
The downside is that unless there's a way to specify the joining/leaving equivalent for types, there ends up being two different models for the same thing when that information /is/ available ... which is against the design principles. 

The simple model is the same shape and complexity, just with different classes and predicates.

eg:
`<Person> classified_as { <NationalityType> classified_as <NationalityConcept> }`
is the same shape as:
`<Person> aggregated_by { <NationalityAggregation> classified_as <NationalityConcept> }`

So the better simplification would be to assert instead that aat:British is of type Aggregation, and is classified_as a aat:Nationality.

**Comment by azaroth42** [comment]
Propose above simplification:  

```
{
  "id": "aat:british",
  "type": "Aggregation",
  "classified_as": "aat:nationality",
  "label": "British"
}
```

**Comment by azaroth42** [comment]
With Phase, we can solve this :) See #180 and #179.

Thus the atemporal version would be:

```
{
  "type": "Person",
  "classified_as": [ "aat:british" ]
}
```

The temporal version for someone who was British between 1998 and 2018 would be:

```
{
  "type": "Person",
  "classified_as": ["aat:british", "aat:french"],
  "phase": [
    {
      "type": "Phase",
      "classified_as": "aat:nationality",
      "timespan": { 
        "type": "TimeSpan",
       "begin_of_the_begin": "1998-07-21",
       "end_of_the_end": "2018-09-01"
      },
      "relationship": "classified_as",
      "related_entity": "aat:british"
    }
  ]
}

(with the appropriate expansions of the Types)

**Comment by azaroth42** [comment]
Done. See https://linked.art/model/actor/#nationality

Phases of types remain open in #180 .

Closing.
