### ISSUE TITLE
Lots offered by a seller, but not sold

### ISSUE THREAD

**Issue by mdlincoln** [linked-art/linked.art#153]
We need to be able to state that a lot was offered for sale (http://linked.art/model/provenance/auctions.html#sale-of-lot) by an identified seller _even if the lot was not sold_, and hence there is no Purchase activity (http://linked.art/model/provenance/auctions.html#purchase) to which we can attach the seller Person. It's unclear how to do this right now, as the only Person attached to the sale of lot activity in the current spec is the auctioneer.

(This happens 300,000-500,000 times in the provenance index records)

**Comment by azaroth42** [comment]
I agree that this is covered by the ownership of the object, but to try and rephrase the concern as I understand it ...

From a description of an auction lot (the set of objects being offered), it must be possible to determine the then-current owner of each object, even if the auction did not result in a sale. There isn't an explicit activity carried out by the owner, and there isn't a way to assert that the owner of the object while being bound to that time period.

I think there are two options:
  * Given that we have an Aggregation for the Lot, we could assert the owner on Proxy for the object... (in the context of the auction lot set, the current_owner is J Smythe) but that's then a slightly weird pattern when the object _is_ sold and doesn't scale to other assertions of ownership, rather than state transitions between owners.
  * We can add an activity that _is_ carried out by the owner, such as adding it to the Lot. This is semantically strange, as they didn't actually do that, the Lot was likely (I assume?) constructed by the auction house, not the seller.  We don't know whether custody was transferred to the auction house, nor really how that would fit into the particular view.

**Comment by mdlincoln** [comment]
@workergnome indeed it's semantically the same - but if I understand @azaroth42 correctly, the question is how to state that they owned it AND that there was no intermediate ownership/activity between that and the lot sale activity

**Comment by mdlincoln** [comment]
That makes sense to me. From the historian's pov, its as useful as "inventory taking" because it registers the presence of the object in someone's holding at some point in time. Is the added redundancy onerous for those objects that sold? Is there a predicate connecting the "sale offering" activity and the "purchase" activity?

**Comment by mdlincoln** [comment]
Does this interact with #154 ? Because we will have sales where an agent or dealer offered a work for sale, but they did not themselves own it.

**Comment by ddegler** [comment]
Wading in with too little context, but... a thought. What is the over-arching event? While there is a specific sale event (or not) for an object, there is a broader auction or consignment event in which that occurs. Associated people have roles within the event, which means they can be a custodian without being an owner, and the owner may not be associated with the event. Then you just have @mdlincoln initial question, the seller's role(s) when an item isn't sold. But there is still a custodial transfer before and after? Somewhat like @azaroth42 second point, but not focused on "adding it to the Lot"? This may be problematic as there are events-within-events...

**Comment by mdlincoln** [comment]
Any updates on this? We're starting to transform our auction sales for the Provenance Index and could use some guidance.

**Comment by azaroth42** [comment]
I agree with the similarity to inventory taking. The utility of the information is that it gives a piece of evidence that the object was owned by some party at some point in time. Thus we have Actor, Object, the relationship between them (owning), and a Timespan. What we don't have is any real Activity to connect them, unlike with the "inventorying" case.

A clean and easy option that's less semantically appealing:

> The auction lot activity (P117) `occurs_during` the ownership activity.

This would let us do what we want the data for -- proving the timespan of the ownership activity. What it doesn't say is that the person owned the objects at the time, just that the auction activity's time period is temporally within the ownership activity's time period.

**Comment by mdlincoln** [comment]
We will sometimes need to express that there were 2+ sellers for an object for some lots. This is straightforward for the transaction event when there are sales - but here, would we need to create two overlapping ownership activities, one for each person? (fwiw in these cases we don't normally have information like "A owned 1/3 share of the object and B owned 2/3 share")

**Comment by azaroth42** [comment]
Then it would `occur_within` all of the owners' ownership activities. What would *not* work in any of these, other than the proxy, is if we know that two objects in a single lot, had different owners, and which object was related to which owner.  For that, we need something very close to the proxy... as weird as that pattern is.

**Comment by mdlincoln** [comment]
We do have a few thousand examples where multiple objects, each from a different owner, are combined into one auction lot.

(Counting this has has also helpfully pointed out an oversight in my own transform code ✅ )

**Comment by azaroth42** [comment]
Proxy pattern:

```
{
  "type": "Aggregation",
  "classified_as": "aat:auction_lot",
  "aggregates": [
    {
      "id": ".../object/1",
      "type": "ManMadeObject"
    },
    { 
      "id": ".../object/2",
      "type": "ManMadeObject"
    }
  ],
  "proxies": [
    {
      "type": "Proxy",
      "proxyFor": ".../object/1",
      "current_owner": [
        {
          "id": ".../actor/1"
          "type": "Person"
         }
      ]
    }
  ]
}
```

✅ It's consistent with other Aggregation patterns. It only adds the `proxies` part, as the above part is needed for the lot regardless. 
❌ For consistency, including this in every auction lot would be very long winded. It's not CRM-y. It's not just within the context of the auction lot that the object is owned by the actor, so while it's not wrong, it's also potentially confusing. Probably hard to query for.

**Comment by azaroth42** [comment]
Activity pattern:

```
{
  "type": "Activity",
  "classified_as": "aat:made_available_for_sale_or_something_like_that",
  "part_of": [".../activity/ownership-of-object"],
  "used_specific_object": [".../object/1"],
  "carried_out_by": [".../actor/1"],
  "referred_to_by": [".../text/auction_catalog_entry"]
  "specific_purpose": [".../activity/auction"]
}
```

✅ Consistent with inventorying and ownership period (cough activity). Only CRM patterns. Easy to connect to evidence and the auction activity. Can be easily pulled apart from the auction activity, unlike the proxy assertion from the auction lot.
❌ Doesn't actually anywhere assert that the actor is the owner of the object at the time (!), thus also hard to query for. Would be also very (very) long winded to do this for every event, but perhaps computable for the majority. The classification for the activity is semantic junk, constructed just for this use case.

**Comment by azaroth42** [comment]
Okay, in writing the above two and drawing drawing drawing on whiteboard... how about just that the activity of the auctioning of the lot `occurs_during` the ownership of the object by the owner? The owner/object relationship is the `used_specific_object` of the ownership, which then gets rid of the weird extra "offering for sale" activity.

Simplified Activity Pattern:
```
{
  "type": "Activity",
  "classified_as": ["aat:300054277"],  // ownership
  "carried_out_by": [".../actor/1"],
  "used_specific_object": [".../object/1"],
  "includes": [".../activity/auction"]
}
```

**Comment by azaroth42** [comment]
Hearing no objections, I'll document the above pattern.

**Comment by azaroth42** [comment]
This is re-solved in the new provenance model - transfer of custody from owner to auction house and back to owner.
