### ISSUE TITLE
Model agents who carry out purchases for third parties

### ISSUE THREAD

**Issue by mdlincoln** [linked-art/linked.art#154]
We need docs and graphs for [transfers of custody](http://linked.art/model/exhibition/#exhibition-provenance-transfer-of-custody) in the context of purchasing

re: https://linked-art.slack.com/archives/C50AP8USG/p1521647988000401

Also re: https://linked-art.slack.com/archives/C50AP8USG/p1522863853000035

We also need to be able to attach an AAT concept to that activity, such that we can distinguish between e.g. an agent buying on behalf of a purchaser at an auction, versus Knoedler taking an object on consignment (they take custody of the object, but ownership remains with the consigner; in any resulting sale, Knoelder would carry out the transaction, but the payment would go to the original consigner)

**Comment by azaroth42** [comment]
Agent:  This is the distinction between `carried_out_by` and `transferred_title_to` as part of the Acquisition of the auction lot. 

Consignment: Agree that consignment is a transfer of custody, and then then they become the agent that sells the object for the seller. So title is transferred from the owner to the buyer carried_out_by Knoedler.

**Comment by azaroth42** [comment]
Done as part of commissions.
