### ISSUE TITLE
classified_as and TimeSpans

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#158]
Do we need `classified_as` for TimeSpan? I don't believe there are different types of timespans, they're just a data structure for capturing the begin/end_of_the_being/end and min/max_duration.

Similarly, the Dimension given as min/max_duration does not need a Type via `classified_as`, because this is explicit in the relationship.

**Comment by workergnome** [comment]
Does this mean that we'd use attribute assignment (or Measurement, though I don't think we use that) to handle additional classifications for data?  Methodology, standards, etc?

`type: EDTF` or `type: Approximated` or `type: Computed`

**Comment by azaroth42** [comment]
`classified_as: aat:computed` seems like a good use case for P2 on timespans :)

**Comment by azaroth42** [comment]
Rolling this into #239.
