### ISSUE TITLE
Make it easier to distinguish statement from textual work

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#164]
Both of which might be `referred_to_by` the same resource.  Currently the only way to determine which is which, without understanding all of the AAT classifications, is to look for the presence of `value`, and assume all of the resources with a `value` are statements.

This could be a new term in `classified_as` similar to `aat:300133025` is for all artworks to distinguish them from non-art objects.

**Comment by azaroth42** [comment]
@workergnome and @azaroth42 agree on problem and proposed solution to make a new term for all statement LOs to make them easier to filter. Presence or not of value is an anti-pattern, as pamphlets or other short texts might end up being transcribed.

**Comment by workergnome** [comment]
Is this a Linked.Art-level concern?  Are we just distinguishing between two different concerns within a specific interpretation, or is there a significant pseudo-class difference between these two?

We've definitely said that "artwork" is a core concern of Linked Art, and should be called out explicitly for interoperability, but is "statement" at that same level?

**Comment by azaroth42** [comment]
I think it's an API part of linked art concern. Otherwise you need to filter based on the presence of `value` ... which seems flakey at best, and dangerous at worst.

**Comment by workergnome** [comment]
Coming back to this--I agree that the `classified_as` pattern is essential, and should be the way that we solve this. 

I think the question is do we want a "blessed" AAT term for statement, making statements a first-class concept within Linked.Art, or do we want to recommend that people add an appropriate classification?

**Comment by azaroth42** [comment]
I think we want to bless an AAT term, in the same way that we bless "artwork" but not "painting".

**Comment by workergnome** [comment]
Maybe what I'm stuck on is that I can't tell what the difference between a statement and any other LinguisticObject might be?

**Comment by azaroth42** [comment]
The abstract text of War and Peace, vs the 150 word materials statement for a dec arts object

**Comment by azaroth42** [comment]
We can use aat:300418049 - brief text

**Comment by azaroth42** [comment]
This is done.
