### ISSUE TITLE
When can/should we use blank nodes?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#166]
From Ethan, is there a policy on blank nodes? I don't have a URI for every possible individual measurement.

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-01108d70f9d849b29529df4a0c8c9d97/page-1)

**Comment by azaroth42** [comment]
Propose that this is out of scope and close.

**Comment by azaroth42** [comment]
Given discussion at F2F3, I believe that the answer is "Any time you want, other than when the API requires it to be a top level resource".

e.g. Name, Identifier, TimeSpan, Dimension etc as internal nodes can be blank nodes.

**Comment by aisaac** [comment]
"top-level resource" = "top-level resource in the JSON-LD" ?
if yes then I think I agree.

**Comment by azaroth42** [comment]
Agreement on 2020-03-11 call:

You MAY use blank nodes, but SHOULD use URIs if possible. You MUST use URIs if the resource is to be dereferenced according to the API (e.g. Person, HMO, etc).

Guidance for URIs - useful to have guidance for how to generate URIs in the absence of stable identifiers.  Maybe implementation note? 

Noted that https://www.w3.org/TR/annotation-model/#xpath-selector selectors are a useful construct in cases like this for annotation.

**Comment by beaudet** [comment]
We also discussed the possibility of using JSON-PATH as a selector since the specification is currently limited to JSON-LD.

**Comment by azaroth42** [comment]
This is documented now in the API section :)
