### ISSUE TITLE
theft and custody

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#18]
From @workergnome on gri-is/crom:

Re-flagging this as something potentially worth talking about—Art Tracks has modeled both theft and loss as ownership transfers, not as merely custody transfers—If a work is documented as stolen/and or lost, there is no functional ownership.

**Comment by azaroth42** [comment]
The CRM is pretty clear that it considers theft as a transfer of custody.  In the scope notes for E10 Transfer of Custody: 
> A specific case of transfer of custody is theft.

I believe (through the discussion of E30 Right on CRM-SIG) that this is because E10 and E8 are considered to be the transfer of the _right_ of ownership versus the physical possession of the object. These two probably overlap in a vast majority of cases (to at least 9/10ths of the law and use cases) but from a strict modeling perspective I think theft is custody, not illegal acquisition of the legal right of ownership.  If the stolen item was recovered, then the provenance would require the right of ownership to be re-acquired from the thief... which seems worse to me than the loss of functional ownership.

Is there something else we can do to maintain it as a transfer of custody, but that it also ends any functional (if not legal) ownership? Clearly a P2 is needed (aat:300055292). It could be carried_out_by the thief to make it clear the one sided nature of the transfer? Perhaps we need an activity that mirrors ownership period for custody, that the transfer of custody can explicitly end?  Seems overkill for non-theft though.

It seems like a more generic rights transfer class would be better:

```
_:theft a Transfer ;
  classified_as <theft> ;
  of <custody> , <functional-ownership> ;
  over <object> ;
  from <owner> ;
  to <thief> ;
  starts <period-of-possession-by-thief> ;
  ends <period-of-possession-by-owner> .
```

Which we could advocate for with the SIG?

**Comment by workergnome** [comment]
One of the things that was worrying to use about this was that stolen/looted/confiscated/nationalized artwork is often sold, at which there _is_ the transfer of the right of ownership, albeit perhaps not one that was legally permissible, or (often more commonly) was deemed legally impermissible in hindsight.  Without the theft being treated as a transfer of ownership, it gets really confusing.

**Comment by azaroth42** [comment]
This is subsumed into #19.
