### ISSUE TITLE
Always partition the "artwork" part of an object?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#185]
In order to be consistent, we should consider always partitioning the "artwork" part of an object out from the rest of it.  For example, at the moment if we want to say a painting is "oil on canvas", then the painting as a whole is made of oil paint, and the support part is made of canvas.  We have already de-conflated the object from the visual item ... we could further separate the artwork part from the whole.

Beyond consistency, this is potentially important for inferencing and rolling up assertions. If the artwork part is paper and watercolors, the support is canvas, the frame is oak and oil paint ... then the object is made of all five materials, but the artwork only of paper and watercolor.

It also means that the number of P2 references defined on the main object will be reduced -- the shape and color of the artwork would go on the physical artwork part, rather than the main object.  The artwork part would then `show` the artwork image.

It adds complexity, but also adds some value in the real world when applied to existing data.

**Comment by azaroth42** [comment]
The complexity pays off with digital, where the digital image digitally_carries the same visual item as the physical object.

**Comment by cbutcosk** [comment]
If this were made a requirement, what would the default case of an (intellectually) unpartionable object look like? There are plenty of objects that can't be split in this way, either materially or cases where the artwork's content is troubles the figure/ground distinction.

**Comment by workergnome** [comment]
I think an object could easily have a single part, which is the whole thing.  To me, this is the "object vs. array} complexity thing.

**Comment by cbutcosk** [comment]
Ah, that's really clarifying, thanks. I think the sub-part of interest being aat:artwork is what trips me up here--many registrars would think that a pretty cheeky act of classification where recto/verso, etc are not. "MMOs for things we collect as art are aat:artwork" uses the casual classifications already in use, but "only the oil and canvas are aat:artwork" feels pretty alien in that context.

**Comment by natuk** [comment]
Yes, I agree that it would be a bit strange to consider a bit of the object as "artwork" and not the rest. In conservation there are cases when the paint layer is removed from one support and put on another (e.g. when the original support is damaging the paint layer), but the understanding is that the original support is part of the artwork and that the process is destructive.

**Comment by azaroth42** [comment]
Seems like reasonable consensus here to not separate out the artwork part from the whole.  

Thus we should stick with the current model, where an "oil on canvas" painting has the whole painting `made_of` oil and the support `made_of` canvas.

The ramifications are:
 * We continue not to be able to build inferences about inheritance up and down the partitioned hierarchy -- just because the whole is made of oil does not mean that all of the parts also are made of oil. However inference is not a design goal, this level of explicitness is not supported in most data collection systems, and even if it was, the inferences drawn would be highly suspect.
 * The visual item of the art is not distinguishable from the visual item of the object as a whole. So a photograph of the the object on the wall is the same visual item as the object.  Again, this does not add any significant challenges, to my knowledge.
 * We can't distinguish an oval artwork in a rectangular frame. I think we can live with that, and in the situation where it becomes important, we can always partition. The consistency solution here is more troublesome than the exception introduced, as the number of cases where we both need the partitioning and have the data to support it is very low.

Propose close, won't fix.

**Comment by azaroth42** [comment]
Agreed to close, won't fix.
