### ISSUE TITLE
Please clarify case sensitive of types (and more generally for other property values on which data model depends?)

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#194]
I pose the question: Are the values for "type" generally case sensitive with the linked.art model? e.g. is "Actor" == "actor" ?

**Comment by Conal-Tuohy** [comment]
Yes these values (such as "Actor") are case sensitive in JSON-LD: https://json-ld.org/spec/latest/json-ld/#the-context

**Comment by beaudet** [comment]
Rob suggested on Slack that the IIIF specs should probably point this out / reinforce it.

**Comment by azaroth42** [comment]
Retagging as service, as the model cares not for case. This is an API issue to be documented clearly in the API docs, when we get there.

**Comment by azaroth42** [comment]
Done.
