### ISSUE TITLE
Guidelines for label selection

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#201]
From @aisaac on WG call of 2019-01-30: 

There should be guidelines for picking a label to use for a resource. For example, is there an intent for them to be consistent?

Related to #72 and subsequent #186.

**Comment by azaroth42** [comment]
To give my perspective, as `label` is only intended to be for developer use, rather than presentation to end users, the exact label string should be selected such that it is useful for that purpose. I don't think there's any need to stay consistent with the resources' `Name`s -- especially for some Types, the "official" names are sometimes not useful at all to developers.

Thus for the consistency question, the URI in `id` is where the consistency and code level checking comes in. The label can be whatever is locally useful, and if it's not useful to external developers there's at least the full URI to dereference and get the description of the `Type` :)

**Comment by beaudet** [comment]
Wondering if there's a way to convey to the "casual linked art data consumer" (if that even exists) that the label is meant only as a navigational reading aid for humans inspecting the JSON and should not be used in logical operations.

**Comment by aisaac** [comment]
To examplify my concern. `https://linked.art/model/base/` has as example
```
 {
      "id": "http://vocab.getty.edu/aat/300033618", 
      "type": "Type", 
      "label": "Painting"
  }
```
`http://vocab.getty.edu/aat/300033618` has as label (`rdfs:label`) `peinture (visual work)` (sic). Which should a French data publisher use?
In fact the concern extends even to monolingual cases: the English label of the concept is `paintings (visual works)`. Why/when would a data publisher strip the `(visual work)` part of the label?

**Comment by edgartdata** [comment]
I did wonder too about the use of  "label": "Painting" vs. "label": "Paintings (visual works)"

**Comment by beaudet** [comment]
Instead of "Label", could developers use an optional anchor in the URI to convey human readability? e.g. http://vocab.getty.edu/aat/300033618#Painting that would not impact the semantic importance of the URI?

**Comment by azaroth42** [comment]
To @beaudet's question about making the audience clearer - I think we're missing that in the documentation, even though it has been talked about a lot.  Also, we could make it a little more clear with a change to the context to adopt some convention about meta-metadata, such as starting with and `_`.  Thus it _could_ be `_label` rather than `label`. Whether that's friendlier or not, I don't know, but it would more clearly distinguish it?

To @aisaac & @edgartdata, I think this issue of data consistency (as opposed to model consistency) comes up only for external references such as the vocabularies used with `classified_as` where the data provider has a different label or set of labels.  Does it matter though?

For the qualifying string in parens, this is an AAT specific feature to distinguish homonyms within a particular language, and is not itself translated but managed separately in the system of record.

And to the idea of putting a fragment on the URI, that would make it much harder to write the code that aligns the URI with painting, with however that is then processed by the application. Especially as we can't predict if other vocabularies use fragments for semantic meaning.

**Comment by workergnome** [comment]
It does seem odd to me (as a developer) to be including human-readable comments within the machine-readable data.  I totally understand Rob's point, though, about the data stream being read by both humans and machines.  

I'd strongly support doing something that made it very clear that it's not something people should use...I'd even support it being something like `{"_comment" : "Painting"}` to make it very explicit.

**Comment by aisaac** [comment]
@workergnome and @azaroth42 's suggestions would alleviate the issue somehow, by indeed making it less important. 

Still, as long as we're going to have something in the model that looks like it matches a typical function of authority, it's going to be a problem if we say that people may do what they want based on existing labels, which can be authoritative (such as the Getty one). 

In other words, as a data publisher, if I see that AAT publishes `paintings (visual works)`, then it gives me some piece of mind: others have decided it was useful to have these labels as labels, even if they may look a  bit strange at times. If I'm in charge of deciding whether to strip parentheses or not, and I have to decide whether to use my native language or a lingua franca, then I'm potentially going to spend a lot of time pondering about the possible choices. It's going to be even more difficult in my organization there are other people who could have conflicting views on the matter (as this is supposed to be comments, they will see it in the data easily - in fact it's going to be the first thing they see, probably). And I guess we all live in such organizations ;-)

**Comment by beaudet** [comment]
I agree @aisaac - however, if the authority data needs to be cached / updated in order to keep it more or less in sync with the authority's label, that introduces complexity in implementations.

**Comment by aisaac** [comment]
Very good point @beaudet ! Still I think it's much easier to articulate a recommendation that says it's not a big deal if labels that once mirror authorities are now out-of-sync, rather than letting people figure out by themselves what data they should make up. And if the labels get out-of-sync, it's clear what data publishers should do if they want to fix it, and it's clear what is the tradeoff if they don't do anything. 
If they have to more-or-less make up labels, and they feel they have to articulate a strategy for it, then they have to embark on an effort that's not unlike authority control, which is not a sinecure.

**Comment by jeremytubbs** [comment]
So I have been working on an API implementation and had made the label field so that is `hasTranslations`, I do not plan on changing this even after the discussion I heard today. I am not concerned with labels getting out of sync... my API will allow for a default language to be defined which will be the fallback if a different language is requested. Adding new languages will be the prerogative of the data admins.  In reference to those external authorities, if they support the language requested then it will show their preferred nomenclature otherwise we can extend it base on our own authority.

**Comment by cbutcosk** [comment]
@workergnome I'm sort-of concerned about making statements about other people's stuff, but I also think that the global graph story probably needs to account for that kind of complexity (or, ugh seeing as it is 2019, that potential for abuse) at a higher level than the graph/document data model.

**Comment by azaroth42** [comment]
Decision at F2F meeting:  rename `label` to `_label` and document intended use.
