### ISSUE TITLE
API versioning approach needed

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#205]
Since linked.art will evolve over time as well as experience implementation experiments such as #202 that will eventually be consolidated back into future versions of the API, it seems like the project would benefit from adopting a simple, durable API versioning approach from the beginning.  The approach should include specifications to convey a request for a specific version of the API as well as fallback mechanisms and default behavior when no specific version is requested.

**Comment by azaroth42** [comment]
Agreed. Is this just semantic versioning, ala [IIIF](https://iiif.io/api/annex/notes/semver/)?
Do we need to actively do anything?

**Comment by beaudet** [comment]
If I'm understanding the IIIF semantic versioning you referenced correctly, I think it's more than that in the sense that an application consuming the data should not have to be updated in the future if an institution can support multiple end points, each of which support a different version of the linked art model / APIs.  For example, if an institution pays a contractor to develop a kiosk application that sources collection data via linked art version 2, then down the road the institution implements linked art version 3, it should still be possible to run the linked art version 2 implementation in order to support the kiosk which might have been a large investment and would be expensive to update.  This could be accomplished in multiple ways, e.g. specifying the version in the URL somewhere (host, base path, query param?) or requiring consuming applications to use content negotiation in order to specify a linked art version.

**Comment by aisaac** [comment]
I'm not willing to open a can of worms... but regarding the options suggested by @beaudet at the end of the last message, do we say anything about (making a difference between) information resource URIs (i.e. URLs for JSON-LD records) and non-information resource URIs (i.e. URI for the an art object)?

**Comment by azaroth42** [comment]
Can use conneg for explicit version negotiation:
`Accept: application/ld+json;profile="https://linked.art/ns/v2/"`

So long as the major version is in the URI of the profile (and thus context document)

(Also what IIIF does: https://iiif.io/api/presentation/3.0/#61-uri-recommendations )

Proposal:

Use semantic versioning, and version based content negotiation to manage cross-version implementation dependencies.

**Comment by azaroth42** [comment]
Done.

**Comment by beaudet** [comment]
I know we closed this issue, but semantic versioning might lead to the same URL produces two different results, so just something to keep in mind regarding caching.  Some thoughts on versioning here - not necessarily spring-specific: https://stackoverflow.com/questions/20198275/how-to-manage-rest-api-versioning-with-spring
