### ISSUE TITLE
Create full path model for commission activities

### ISSUE THREAD

**Issue by edgartdata** [linked-art/linked.art#216]
The commission activity would be linked to the object production activity.

**Comment by azaroth42** [comment]
Discussed on 2019-10-23 call.

Decision:  Commission is another sort of Provenance Activity (per #275) where the classification of the main activity is commissioning (suggest - [aat:300400904](http://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300400904)) and can contain all of the other sorts of sub-activities:

* Promise - Promise to pay the artist
* Acquisition - Payment by giving the artist some object
* Payment - Payment by monetary amount
* Transfer of Custody - Lending an object to the artist as part of the commission, e.g. to copy
* (etc)

The activity would be carried out by the commissioning party, and have a participant of the artist.
The activity then triggers the production of the object.
(Though as discussed in the same call under the API topic, this would likely come from the production to say that it was triggered by the commissioning activity)

**Comment by azaroth42** [comment]
Noting that `Production` events can then be `caused_by` the Provenance Entry, to demonstrate that the promise was fulfilled.

**Comment by azaroth42** [comment]
Done here:  https://linked.art/model/provenance/promises.html
