### ISSUE TITLE
Remove part/part_of (being broader/narrower) for Types

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#223]
This is both confusing, and one step too far removed from the scope of linked.art.  Yes we need a rich set of concepts, but we do not need to be opinionated on the modeling of the relationships between those concepts.

CRM SIG recommends the use of skos:Concept and its properties as a way to manage taxonomic hierarchy. We should at least (thus) use narrower and broader in an advisory extension, or simply refer to SKOS and call it done.

**Comment by azaroth42** [comment]
Closed by #224. We can reintroduce in a separate companion document if needed

**Comment by aisaac** [comment]
(for the sake of ease of information access: #224 closes the issue by removing altogether the section on partitioning types in the documentation, not introducing a new pattern.
