### ISSUE TITLE
Model for the discovery of the object rather than its production

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#230]
The finding of an object is sometimes the first known event in its provenance, and while the production date can be estimated, its rediscovery is an important activity to be able to describe.

For example, the Getty's much litigated [Victorious Youth](http://www.getty.edu/art/collection/objects/7792/unknown-maker-statue-of-a-victorious-youth-greek-300-100-bc) statue was probably made between 300 and 100 BC, but was found in the sea in 1964.

This discovery activity should be able to be consistently modeled across collections.

Possible solutions:

* An Activity that has a `classified_as` to a `Type` that denotes finding, and `used_specific_object` to the object found.
* Use the more specific, slightly strangely modeled and named [CRMSci](http://www.cidoc-crm.org/crmsci/sites/default/files/CRMsci%20v.1.2.5%CE%91%CE%9Ab-AV.pdf) class "S19 Encounter Event", and its properties O19 has found object and O21 has found at. I say strange, as it is an Observation (okay) which is an Attribute Assignment (wut?)
* Invent something new.

**Comment by ewg118** [comment]
Look at the CRMarchaeo extension. There's a lot of discussion of archaeological linked data modeling, within CRM and other ontologies (we have related contextual classes and properties in the Nomisma ontology). I think the S19 Encounter Event is used here also. We should be able to find some examples in Computer Applications in Archaeology articles.

**Comment by azaroth42** [comment]
After discussion also in London at the Linked Conservation Data meeting, plus Ethan's note about Archaeo, I think that using S19 with some appropriate context to rename to something more obvious would be the right approach.

**Comment by ewg118** [comment]
See https://github.com/linked-art/linked.art/issues/285 where I recommend `Discovery` for `S19_Encounter_Event`

**Comment by ewg118** [comment]
Two people from the Archaeological Data Service, who are also part of ARIADNE, are going to be at LODLAM. Perhaps we can discuss this in a few weeks.

**Comment by azaroth42** [comment]
Closing in favor of #285
