### ISSUE TITLE
Replace P2 to a property with P177

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#232]
Per SIG of March 2019, P177 is now `assigned_property_type`:

> This property associates an instance of E13 Attribute Assignment with the type of property or relation that this assignment maintains to hold between the item to which it assigns an attribute and the attribute itself. Note that the properties defined by the CIDOC CRM also constitute instances of E55 Type themselves. The direction of the assigned property type is understood to be from the attributed item (the range of property P140 assigned attribute to) to the attribute item (the range of the property P141 assigned). More than one property type may be assigned to hold between two items.

This solves the complexity of using P2 both for categorization of attribute assignment and recording the property/relationship between the instances. 

Need to update (e.g.) https://linked.art/model/assertion/#assignment-of-attributes to use the new property

**Comment by aisaac** [comment]
This is a step in the right direction!

I have one additional editorial suggestion: could all the 'assigned' elements ('assigned', 'assigned_property_type' and 'assigned_to') be presented in one sequence in the example at https://linked.art/model/assertion/#assignment-of-attributes ?

And the nitpicking: 'assigned' sounds a bit confusing when there are so many 'assigned-X' elements around. Couldn't we rename it 'assigned_attribute" in the Linked Art context? And would it be worth suggesting a similar renaming for P141 in CRM?

**Comment by azaroth42** [comment]
This is done, including using `assigned_property`.
