### ISSUE TITLE
Scoped terms won't resolve for P2/P177 references

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#235]
If there is an `AttributeAssignment` that uses a term which is defined in a scoped context to normalize the JSON-LD term, then the expansion algorithm will use the definition for `AttributeAssignment` (e.g. an `Activity`) and not the definition of the class to which the term is assigned.

For example, if the `AttributeAssignment` assigns a part as being `part_of` a larger object, the `part_of` should be physical, whereas it will instead resolve relative to the `AttributeAssignment`, and thus will be temporal.

Two possible solutions - either use the full term (`crm:P9_consists_of`) or define specific terms in the context within `AttributeAssignment` for the conflicting terms (`temporal_part`)

Example: http://tinyurl.com/y5ucnn2a

Note that `part` expands to P9, which is not valid for `HumanMadeObject`.

**Comment by azaroth42** [comment]
Propose the second option, with the following context scoped below P177:
```
      "@context": {
        "part": null,
        "temporal_part": "crm:P9_consists_of",
        "physical_part": "crm:P46_is_composed_of",
        "symbolic_part": "crm:P106_is_composed_of",
        "propositional_part": "crm:P148_has_component",
        "timespan_part": "crm:P86i_contains",
        "location_part": "crm:P89i_contains",
        "interest_part": "la:interest_part",
        "part_of": null,
        "temporal_part_of": "crm:P9i_forms_part_of",
        "physical_part_of": "crm:P46i_forms_part_of",
        "symbolic_part_of": "crm:P106i_forms_part_of",
        "propositional_part_of": "crm:P148i_is_component_of",
        "timespan_part_of": "crm:P86_falls_within",
        "location_part_of": "crm:P89_falls_within",
        "interest_part_of": "la:interest_part_of"
      }
```

**Comment by azaroth42** [comment]
Analyzing the impact of this, partitioning in this way will work as expected for temporal partitioning (as the AttributeAssignment is temporal), which is also the majority of the classes that we use. Attribute Assignments are referenced from the attributed resource, so we can fix this in the context by explicitly laying out the `HumanMadeObject -> AttributeAssignment -> assigned_property -> part_of` chain to be the right part-of (P46).

**Comment by azaroth42** [comment]
(Not really docs, but just to ensure that the context is set up properly for this one edge case)

**Comment by azaroth42** [comment]
Noting that this is a real bug, but very much an edge case.

**Comment by azaroth42** [comment]
Magic scoped context pattern to map part_of away from the temporal one to the parent class:
https://tinyurl.com/2bk9bnhd

**Comment by azaroth42** [comment]
The pattern to use anywhere we map `part_of` in the context:
```
    {
      "HumanMadeObject": {
        "@id": "crm:E22_Human-Made_Object",
        "@context": {
          "attributed_by": {
            "@id": "crm:P140i_was_attributed_by",
            "@context": {
              "assigned_property": {
                "@id": "crm:P177_assigned_property_of_type",
                "@type": "@vocab",
                "@context": {
                  "part_of": {
                    "@id": "crm:P46i_forms_part_of"
                  }
                }
              }
            }
          }
        }
      }
    }
```

**Comment by azaroth42** [comment]
Per @michielhildebrand, the new context breaks Apache Jena.

> Caused by: JsonLdError[code=A keyword redefinition has been detected [code=KEYWORD_REDEFINITION]., message=A keyword [@id] redefinition has been detected.]

However I believe this is a bug in Jena, as it works fine in the playground ... See https://tinyurl.com/yw5a6sbj and https://tinyurl.com/ycxfwzpw

And in Python's pyld:

```
from pyld import jsonld
import json
j = json.loads(js) # js is the string from the playground
expanded = jsonld.expand(j)
print(json.dumps(expanded[0], indent=2))
```

produces

```
{
  "http://www.cidoc-crm.org/cidoc-crm/P140i_was_attributed_by": [
    {
      "http://www.cidoc-crm.org/cidoc-crm/P177_assigned_property_of_type": [
        {
          "@id": "http://www.cidoc-crm.org/cidoc-crm/P46i_forms_part_of"
        }
      ],
      "http://www.cidoc-crm.org/cidoc-crm/P140i_was_attributed_by": [
        {
          "http://www.cidoc-crm.org/cidoc-crm/P177_assigned_property_of_type": [
            {
              "@id": "http://www.cidoc-crm.org/cidoc-crm/P9i_forms_part_of"
            }
          ],
          "@type": [
            "http://www.cidoc-crm.org/cidoc-crm/E13_Attribute_Assignment"
          ]
        }
      ]
    }
  ],
  "@type": [
    "http://www.cidoc-crm.org/cidoc-crm/E22_Human-Made_Object"
  ]
}
```

So I think we should leave the official context as is, file a bug with Jena, and produce a simpler context to use in place of the official one for situations like this.

**Comment by azaroth42** [comment]
Closing again in favor of #410, which I'll update to make sure it doesn't use this level of arcane trickery.

**Comment by michielhildebrand** [comment]
@azaroth42 I come back to this, just to make sure I understand what is happening. The redefinition of the @id in the nested context is allowed in pyld.

This is allowed:
```
{
  "@context": {
    "PhysicalObject": {
      "@id": "crm:E19_Physical_Object",
      "@context": {
        "attributed_by": {
          "@id": "crm:P140i_was_attributed_by",
          "@type": "@id",
          "@container": "@set",
          "@context": {
            "@id": "crm:P177_assigned_property_of_type",
            "@type": "@vocab",
            "@context": {
              "part_of": {
                "@id": "crm:P46i_forms_part_of"
              }
            }
          }
        }
      }
    }
  }
}
```
https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22PhysicalObject%22%3A%7B%22%40id%22%3A%22crm%3AE19_Physical_Object%22%2C%22%40context%22%3A%7B%22attributed_by%22%3A%7B%22%40id%22%3A%22crm%3AP140i_was_attributed_by%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%2C%22%40context%22%3A%7B%22%40id%22%3A%22crm%3AP177_assigned_property_of_type%22%2C%22%40type%22%3A%22%40vocab%22%2C%22%40context%22%3A%7B%22part_of%22%3A%7B%22%40id%22%3A%22crm%3AP46i_forms_part_of%22%7D%7D%7D%7D%7D%7D%7D%7D

However, redefinition of @id at the top level is not allowed in pyld. For example, 
```
{
  "@context": {
    "@id": "crm:E19_Physical_Object"
  }
}
```
https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22PhysicalObject%22%3A%7B%22%40id%22%3A%22crm%3AE19_Physical_Object%22%2C%22%40context%22%3A%7B%22attributed_by%22%3A%7B%22%40id%22%3A%22crm%3AP140i_was_attributed_by%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%2C%22%40context%22%3A%7B%22%40id%22%3A%22crm%3AP177_assigned_property_of_type%22%2C%22%40type%22%3A%22%40vocab%22%2C%22%40context%22%3A%7B%22part_of%22%3A%7B%22%40id%22%3A%22crm%3AP46i_forms_part_of%22%7D%7D%7D%7D%7D%7D%7D%7D

Is this indeed the intended behavior? Or is pyld not performing the checks for nested contexts? 

If it is indeed intended that we can redefine protected terms, such as @id, in a nested context then this is probably where Jena gets it wrong.

**Comment by azaroth42** [comment]
Yes, you're absolutely correct. The context was missing `"assigned_property":{` within the `@context`.

Redeploying with the fixed version.

**Comment by michielhildebrand** [comment]
Perfect! We are parsing linked art again.

**Comment by azaroth42** [comment]
Hooray! Thank you for following up again on this, and apologies for not catching the bug in the context (rather than in the playground version) sooner!
