### ISSUE TITLE
When to use Types of Types pattern

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#238]
Raised by Ethan that there is currently a Type of Type pattern used in the Person model, for example to assert that "female" is classified as a "gender", or that "British" is classified as a "nationality, however this isn't a well documented pattern.

The type-of-types is there to allow processors to manage the large number of possible classifications that any resource might have - there are hundreds of nationalities, and we do not have a mandatory [but see #186] set of base types. If we should use them for gender and nationality, should we also use them to say that a Painting is a Visual Work, but a sword is a decorative object?

**Comment by ewg118** [comment]
For more context:

    "classified_as": [
       {
         "id": "aat:300387350",
         "type": "Type",
         "_label": "exchange media"
       },
       {
         "id": "aat:300037222",
         "type": "Type",
         "_label": "Coin"
       },
       {
         "id": "aat:300037269",
         "type": "Type",
         "_label": "Quinarius"
       },
       {
         "id": "http://numismatics.org/crro/id/rrc-546.8",
         "type": "Type",
         "_label": "RRC 546/8"
       }
     ]

The idea here is that I want to be able to distinguish between higher level or lower level object type classifications (exchange media/coins) and denomination (a necessary classification for coins) and a typological identifier, of which there might be more than one. At the moment, there's no consistent way to parse out the coin type URI, which to me is more important than any other descriptor in the data model (because the coin type metadata is more authoritative and complete than the museum cataloging).

**Comment by aisaac** [comment]
I could live with using type, but can't some of these relationships already be encoded as skos:broader links in some vocabularies (like for Painting and Visual Work AAT)? Would the proposal require to convert some existing statements?

**Comment by workergnome** [comment]
It seems like we should either be using the `skos:broader` pattern, which is the standard way of encoding hierarchical relationships that are defined by the vocabulary creator, or something more like a collection pattern.  Asserting a type on a type means that this type is associated with that type in all contexts, which doesn't seem like what we're trying to do here, since that's the vocabulary's job, and there's already a mechanism for that.

Instead, we're trying to associate a collection of types with another type within a given context.  I've done this before with an Aggregation:

```son
{
  "id": "http://vocab.getty.edu/aat/aggregations/300055926/cross_referenced",
  "type": "Aggregation",
  "label": "Internal cross-references",
  "classified_as": [{
     "id": "http://vocab.getty.edu/aat/300311741",
     "type": "Type",
     "_label": "cross-references"
    }
  ],
  "aggregates": [
    {
      "id": "http://vocab.getty.edu/term/type/Descriptor",
      "type": "Type",
      "_label": Descriptor"
    },
    {
      "id": "http://vocab.getty.edu/term/type/UsedForTerm",
      "type": "Type",
      "_label": "Used for Term"
    }
  ]
}
```

The benefit of this is that it doesn't assert that relationship in the global scope, only in this particular context.

**Comment by aisaac** [comment]
@workergnome yes and in the same line it could be possible to use SKOS Collections in a new Concept Scheme, as a grouping of concepts from another vocabulary (or even across vocabularies). 

I guess one of my earlier worries still applies to this pattern (or yours) though: how much do we want to engage in our own vocabulary engineering? And this put obstacles to using anything else than the vocabulary (AAT) we're focusing here, as would-be users of other vocabularies may find it hard to apply the new construct on top of what they have (SKOS collections are fairly rare, and your new pattern would require new data to be asserted)

**Comment by workergnome** [comment]
I don't really want to engage in too much vocabulary engineering, but I do regularly want to manage application or dataset-specific subsets of vocabularies--and they're often not subsets defined by the hierarchy, or they're subsets that are curated from several vocabularies.  

I can do this at the application level, but if we're publishing this data it's useful to have a pattern to do so.

**Comment by aisaac** [comment]
I agree it is doable and would make sense to do it. I'm just wondering how much this would 'close the world' to only the types we're currently working with. This is more a community/governance question than a technical one, at this stage (I mean, once we have opted for a technical solution that requires extra work).

**Comment by workergnome** [comment]
To me, that's a question for #186.   I'm also nervous about the "closing the world" at the standard level.

**Comment by aisaac** [comment]
@workergnome you're completely right, #186 has the same sort of ramifications. I'm not sure it's entirely contained in it though (one could still leave it open to use types from another vocabularies, but practically making hard by enforcing a data pattern in this ticket, which is not available in these vocabularies). Anyway we can still try first there!

**Comment by azaroth42** [comment]
Regardless of how the relationships fall, unless there is some sort of reification, the assertions are at the global scope because *everything* is asserted globally.

We can't use `broader` because we should be able to pick and choose types from different taxonomies, and those taxonomies do not necessarily have the same structure.  Even within AAT there are a lot of levels that sit between, e.g. [Japanese](http://www.getty.edu/vow/AATHierarchy?find=&logic=AND&note=&page=1&subjectid=300388486) and the language concept.

I don't think that a collection pattern solves the problem either. In order to get from the type to the sort of type it is, and thus how to use it, there would need to be some relationship. That relationship (member_of, aggregated_by, part_of, whatever) would be asserted from the Type, otherwise you couldn't follow your nose to figure out what sort of type it is. And thus if the same Type is used in multiple collections, globally that member_of pattern would be true for all instances. 

So the best practice is just not to use the same type in different circumstances.

Regardless, this issue is not whether to do types of types or not, but in which circumstances we should do it.  My proposal for that is whenever the type is not defined by the model (per #186) as the breadth of the possible values is too high, then it should have an extra type associated with it. This would mean professions, nationalities and genders (as per today) but also any extended types that are more specific about (e.g.) the type of object, such that the processor knows that this particular URI is being used as an object type rather than an ethnicity or a color or anything else.

**Comment by ewg118** [comment]
So something like this, per our discussion?

	"classified_as": [
	    {
	      "id": "aat:300387350",
	      "type": "Type",
	      "_label": "exchange media",
	      "classified_as": [
		{
		  "id": "aat:300264092",
		  "type": "Type",
		  "_label": "Objects Facet"
		}
	      ]
	    },
	    {
	      "id": "aat:300037222",
	      "type": "Type",
	      "_label": "Coin",
	      "part_of": "aat:300387350",
	      "classified_as": [
		{
		  "id": "aat:300264092",
		  "type": "Type",
		  "_label": "Objects Facet"
		}
	      ]
	    },
	    {
	      "id": "aat:300037266",
	      "type": "Type",
	      "_label": "Denarius",
	      "part_of": "aat:300037222",
	      "classified_as": [
		{
		  "id": "aat:300264092",
		  "type": "Type",
		  "_label": "Objects Facet"
		}
	      ]
	    },
	    {
	      "id": "http://numismatics.org/ocre/id/ric.2_1(2).ves.1399",
	      "type": "Type",
	      "_label": "RIC II, Part 1 (second edition) Vespasian 1399",
	      "classified_as": [
		{
		  "id": "aat:300067209",
		  "type": "Type",
		  "_label": "typology"
		}
	      ]
	    },
	    {
	      "id": "https://rpc.ashmus.ox.ac.uk/coins/2/808",
	      "type": "Type",
	      "_label": "RPC II, 808",
	      "classified_as": [
		{
		  "id": "aat:300067209",
		  "type": "Type",
		  "_label": "typology"
		}
	      ]
	    }
	  ]

**Comment by azaroth42** [comment]
I think we should use http://vocab.getty.edu/aat/300435443 (object/work type) rather than the facet ... but otherwise yes :)

Writing documentation for it now!

**Comment by azaroth42** [comment]
Discussion at the Oxford F2F was that we should use types of types whenever there is a non-enumerable list of types needed, where the metatype cannot be inferred from the property.

So this would be required for object type (as the property is `classified_as` and there are many many possible types of object), but not for technique (as the property clarifies that the Type is a technique), not for language (as there's a subclass `Language`) and not for things like "possibly" where the value space is able to be fully enumerated.

**Comment by azaroth42** [comment]
Done in base patterns:  https://linked.art/model/base/
