### ISSUE TITLE
Document how to describe un-identified actors

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#246]
... where we still know some properties, we just don't have a clear cut identity. (As is very common!)

e.g. That the pattern is to create a Person per such unidentified / unknown entity, and associate the properties that are known, but not Identifiers.

Probably this comes in just before the [section on uncertain attribution](https://linked.art/model/provenance/production.html#previous-or-uncertain-attributions).

Consider if there is a good Type to associate, to indicate that the person is unidentified.

/ht Tom Scutt

**Comment by azaroth42** [comment]
Update for the group to discuss -- instead of lots and lots of anonymous people that can bloat out a dataset with hundreds of thousands of useless entities that will never be reconciled.

The approach that we've discussed locally is instead to use a Group to represent the set of possible people, despite the artificial nature of such a Group and that the scope notes would prevent it -- the set of all anonymous people cannot take coherent action. The group would then be classified with a term to know that it is one of these not-really-an-actor sets of people where we don't know enough to identify an individual, but only traits of that person.

**Comment by aisaac** [comment]
Relates to #229 which was discussed at F2F3

**Comment by azaroth42** [comment]
Closed by #589
