### ISSUE TITLE
Should statements be `about` a topic, rather than `classified_as` a topic?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#247]
In looking at some mappings, it struck me that (for example) we have both an Exhibition history statement, and the exhibition itself both `classified_as` an Exhibition (aat:300054766).

Actually, the LinguisticObject doesn't have Exhibition as a type, but rather as a subject. Similarly, a statement about materials is not a material, it has materials as its subject.

There is a property for subjects, the intuitively named `about`.

So instead of:

```
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "http://lod.example.org/museum/LinguisticObject/7",
  "type": "LinguisticObject",
  "content": "oil on canvas",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300010358",
      "type": "Type",
      "_label": "Material Statement"
    },
    {
      "id": "http://vocab.getty.edu/aat/300418049",
      "type": "Type",
      "_label": "Brief Text"
    }
  ]
}
```

It would be:

```
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "http://lod.example.org/museum/LinguisticObject/7",
  "type": "LinguisticObject",
  "content": "oil on canvas",
  "about": [
    {
      "id": "http://vocab.getty.edu/aat/300010358",
      "type": "Type",
      "_label": "Materials"
    },
  ],
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300418049",
      "type": "Type",
      "_label": "Brief Text"
    }
  ]
}
```

I realize this would be a big change, but would help with the types-of-types and similar questions that we've been discussing.

**Comment by Habennin** [comment]
Hi Rob,

It sounds a nice idea and clever solution. Was leaning towards its logic, but was mulling over it and am not sure in the end. The about property is supposed to indicate the primary subject of the information object. 

I have in mind the example of materials statement. So if we have a materials statement and we say Information About refers to Object X and is about Materials, I think that the synthetic reading of that set of triples would be this Info Object chiefly speaks about materials and refers to this object in doing so (maybe as an example). I think this is not what we want to say. The chief subject of the Info Object in this case is actually the Object it is talking about, more particularly it is about the particular materials of the object it is talking about. So if one wanted to use the about property, probably one would want to say both it is about 'materials' and then 'the materials of object x', but then because you have the list of particulars in your list of types it stops being useful.

I think the structure that would most efficiently do what we are aiming at here is the .1 on p67. Here we say, it refers to x in the manner of a or b. This semantically achieves exactly what is going on, I would argue. 

This info object refers to that object x AS materials statement.

I know there is reluctance to use the reified properties construct, but it seems like it's the real topology.

**Comment by azaroth42** [comment]
Discussion on call of 2019-07-31 -- should try to be as clear as possible with the use of p2_has_type, and thus saying that a LinguisticObject has_type / isA Material is really not good. Any system looking for materials (okay bad example as it would be E57 Material...) would then find a bunch of texts. 

Proposal is to allow about (@aisaac) generally, but to try to catalog the common types of statement and then create a list to send to Patricia for addition to AAT. Then we can continue to use `p2_has_type` / `classified_as` in the current fashion, without the potential for massive changes or semantic inconsistencies.

**Comment by aisaac** [comment]
Just to add one point to "Then we can continue to use p2_has_type / classified_as in the current fashion". We will still always need to allow for `about`, as we will never be able to capture all the "types-that-would-include-some-topic" out there, so we need to include some guidelines on when to use `classifed_as` and when to use `about`.
These guidelines would probably be heavily based on looking at the kind of concept to be used in the statements that data publisher wants to create. I.e a concept that fits as a type of statement, like "material statement", can be used with `classified_as` and a concept that doesn't fit as a type of statement like "materials" should be used with `about`.

**Comment by SamiNorling** [comment]
Started a discussion thread on the Google Group to collect a list of statement types used by participating museums: https://groups.google.com/forum/#!topic/linked-art/o9QA9FpWaII.

**Comment by azaroth42** [comment]
New AAT Terms added that resolve this issue - 

300027200 -  Note
300411780 -  Description 
300026032 -  Abstract 
300026100 -  Annotation 
300311705 -  Citation 
300026687 -  Credit Statement 
300435434 -  Copyright/License Statement 
300435426 -  Appraisal Statement 
300435425 -  Condition Statement 
300435427 -  Significance Statement 
300435428 -  Historical/Cultural Context 
300435420 -  Markings 
300435414 -  Inscription 
300435415 -  Signature 
300435421 -  Watermarks 
300435429 -  Material Statement 
300435430 -  Dimension Statement 
300435431 -  Culture Statement 
300435432 -  Period Statement 
300435436 -  Production Statement 
300435439 -  Acquisition Statement 
300435438 -  Provenance Statement 
300026497 -  Bibliography Statement 
300435424 -  Exhibition Statement 
300435422 -  Biography Statement 
300435435 -  Edition Statement 
300435440 -  Pagination Statement 
300435441 -  Foliation Statement 
300435433 -  Language Statement 
300028702 -  Transcribed Inscription 

(Will leave it open until I've updated the site with the new terms)

**Comment by azaroth42** [comment]
New AAT Terms added that resolve this issue - 

300027200 -  Note
300411780 -  Description 
300026032 -  Abstract 
300026100 -  Annotation 
300311705 -  Citation 
300026687 -  Credit Statement 
300435434 -  Copyright/License Statement 
300435426 -  Appraisal Statement 
300435425 -  Condition Statement 
300435427 -  Significance Statement 
300435428 -  Historical/Cultural Context 
300435420 -  Markings 
300435414 -  Inscription 
300435415 -  Signature 
300435421 -  Watermarks 
300435429 -  Material Statement 
300435430 -  Dimension Statement 
300435431 -  Culture Statement 
300435432 -  Period Statement 
300435436 -  Production Statement 
300435439 -  Acquisition Statement 
300435438 -  Provenance Statement 
300026497 -  Bibliography Statement 
300435424 -  Exhibition Statement 
300435422 -  Biography Statement 
300435435 -  Edition Statement 
300435440 -  Pagination Statement 
300435441 -  Foliation Statement 
300435433 -  Language Statement 
300028702 -  Transcribed Inscription 

(Will leave it open until I've updated the site with the new terms)

**Comment by azaroth42** [comment]
Site is updated, closing. (Noting of course that the vocabulary side of this issue is still open, as to whether and if so how to expose these terms)
