### ISSUE TITLE
Replace schema:genre with ... classified_as?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#248]
From previous discussions, the current predicate used for aesthetic [style](https://linked.art/model/object/aboutness/#style) is [schema:genre](https://schema.org/genre).  This was convincingly argued not to be the correct property ... but we did not come up with a replacement.

As a proposal, if only to encourage people to find something better, we could use `classified_as` to a `Type`, and as the set of styles is unenumerable, it would fall under the type-of-types pattern, similar to gender and nationality.

Better suggestions?

**Comment by azaroth42** [comment]
Or we could say that this is such an important feature that isn't covered by the CRM that we need to create a subproperty in the linked art ontology.

**Comment by aisaac** [comment]
If we want to encourage people to find something better (which I'm in favour of!) we could just leave it as an open question, listing alternatives and pointing to discussions (when have we had the discussion on schema:genre?). Putting a property we know would be even worse than schema:genre is likely to make us lose time, responding on comments about an option we didn't believe in, anyway.

**Comment by azaroth42** [comment]
Type of types pattern.

**Comment by azaroth42** [comment]
Above comment was from the Oxford meeting, where the type of types pattern was agreed upon for this use case. Thus it can be replaced by `classified_as` with the style type having a meta classification of style.

Done.
