### ISSUE TITLE
Which objects actually show a Visual Item?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#252]
Paintings, drawings, photographs, prints and other principally 2d objects can clearly show an image, but what about other sorts of object? For example, does a statue show an image? 

If there is a decorated table, and there is another table that looks the same, how do we say that they look the same if not by saying they share a Visual Item? Or the false perspective chalk street art drawings have a very different impression depending on where you stand relative to the artwork -- is the image the perceived 3d content or the absolute 2d content?

The scope note of VI:

> This class comprises the intellectual or conceptual aspects of recognisable marks and images. [...] This class does not intend to describe the idiosyncratic characteristics of an individual physical embodiment of a visual item, but the underlying prototype. [...] The class E36 Visual Item provides a means of identifying and linking together instances of E24 Physical Man-Made Thing that carry the same visual symbols, marks or images etc.

The intellectual aspect of an image, in my view, can include the impression of 3 dimensions, whether that is from a well formed 2d image or a real 3d object. 

The domain of `shows_visual_item` is Physical Human Made Thing, as Visual Item is an Information Object which is the product of human cognition.  Thus a shell or other naturally occurring thing does not have a visual item, but any PHMT can have one. People do not have a Visual Item, and hence a statue which is a good representation of a person, does not show the same visual item as the person... despite the possibility to use the P62 shortcut from statue (E22 HMO) to E21 Person.

**Comment by natuk** [comment]
Yes, I find the above correct and consistent. The scope note of Visual Item does not exclude 3D. P65 describes intention, so it does not apply to a shell (I guess one can use P128 for shells). And P62 is consistent with P65. But I do not think I am answering the question...

**Comment by azaroth42** [comment]
I think the question is -- do all physical human made things (and really I mean museum objects) have a visual item, or are there some that do not? Does a sword in the Royal Armory have a visual item, that it shares with other swords that were made to look the same?

**Comment by Conal-Tuohy** [comment]
I would say a statue definitely shows an image and swords as well, why not?

**Comment by azaroth42** [comment]
For the depicts / represents asymmetry, consider the shells:

```
Sculpture1-of-Shell shows VI-of-Shell .
Sculpture2-of-Shell shows VI-of-Shell .
VI-of-Sculpture represents Shell .
```

But the shell cannot show the same VI as the human made objects that look identical.
We could argue that the imbuing of value onto the shell makes it HumanMade, which would avoid the issue here... but the Statue case can't use that escape route as the Person can't be argued to be HumanMade.

```
Statue1-of-Nelson shows VI-of-Nelson .
Statue2-of-Nelson shows VI-of-Nelson .
VI-of-Nelson represents Nelson .
```

The most perfect Madame Tussauds statue of a person shows a VI, but the Person themselves does not show a VI, even though they might look identical to the statue.

It's not that the graph is disconnected, we still have represents ... it's just asymmetrical (to me) that the original does not have a VI whereas all copies do.

**Comment by natuk** [comment]
I think the property shows intentionality, i.e. someone made a decision to make something look like something else. Neither the shell nor a human features intentionality. So looking the same is irrelevant (or half-relevant).

**Comment by azaroth42** [comment]
Agreement that any HMO can have a visual item, including objects like swords or toasters.

**Comment by azaroth42** [comment]
I think this can be documented as a note in the object/aboutness page where we talk about visual items.

**Comment by azaroth42** [comment]
Done: https://linked.art/model/object/aboutness/

**Comment by azaroth42** [comment]
FWIW, This was made explicit in the scope notes Visual Item in CRM 7.1.1, 2021-03-08
