### ISSUE TITLE
Collect one-sentence bio for Editorial Board members

### ISSUE THREAD

**Issue by SamiNorling** [linked-art/linked.art#260]
Please provide:

Name, Title, Institution
One sentence bio w/ relevant roles, work

**Comment by aisaac** [comment]
Antoine Isaac, R&D manager, Europeana Foundation.
Antoine works as R&D Manager for Europeana. He has especially worked on the representation and interoperability of cultural collections and their vocabularies using Semantic Web and Linked Data technology. He has served in related W3C efforts (SKOS, Library Linked Data, Data on the Web Best Practices, Data Exchange) and co-chairs the Technical Working Group of the RightsStatements.org initiative and the Discovery Technical Specification Group at the International Image Interoperability Framework (IIIF).

**Comment by SamiNorling** [comment]
Samantha Norling, Digital Collections Manager, Newfields

As Digital Collections Manager at the Indianapolis Museum of Art at Newfields, Samantaha Norling manages digital assets and data related to the museum's art, archival, and horticultural collections. As a trained librarian and professional archivist working within an art museum, Samantha is particularly interested in digital projects that break down barriers between GLAM institutions.

[Second sentence optional - feel free to remove for length]

**Comment by karinanw** [comment]
Karina Wratschko, Asst Director of Library and Digital Strategies, Philadelphia Museum of Art

Oversees digital asset management and library technical services; member of [Art Information Commons](https://artinformationcommons.github.io/) team.

**Comment by beaudet** [comment]
David Beaudet, enterprise solution architect for the National Gallery of Art in Washington, is establishing integration services for the institution by aggregating art data and imagery from many sources and publishing it with open standards and APIs.

**Comment by azaroth42** [comment]
Rob Sanderson, Semantic Architect for the J. Paul Getty Trust.
Rob is co-chair of the Linked Art collaboration and CIDOC working group, and responsible for data and metadata standards for the Getty. He is a leader in the cultural heritage information standards domain, playing pivotal roles in IIIF, Linked Art, JSON-LD, BibFrame, Web Annotation, and beyond.

**Comment by edgartdata** [comment]
Emmanuelle Delmas-Glass, Collections Data Manager, Yale Center for British Art
Emmanuelle is responsible for the data management of the YCBA's art collection, with an eye towards using open standards to make it as efficiently sharable as possible. She is co-chair of the Linked Art collaboration and CIDOC working group, and member of the IIIF Operating Committee.

**Comment by BreeAnn7** [comment]
Bree Midavaine, Taxonomist, Philadelphia Museum of Art
Bree is responsible for the creation of an institution-wide knowledge base which will facilitate the discovery of art object information and their related contextual content generated across multiple museum departments.  As a member of the Art Information Commons team her goal is to ensure coherence with linked open data and other metadata standards for future interoperability.
