### ISSUE TITLE
Should we version the spec?

### ISSUE THREAD

**Issue by workergnome** [linked-art/linked.art#27]
I think semantic versioning of this would be really useful at some point.

(as a 0.1 version, so we can make breaking changes as needed, but it would be helpful to indicate that this is in flux to people, and also to indicate when it _stops_ being in flux)

**Comment by azaroth42** [comment]
:+1:

Question though -- where to put the version? Every document would need a header?

**Comment by workergnome** [comment]
in a VERSION file in the directory root would be my preference.  With a callout in README.txt, and maybe a embedded reference in the homepage?

**Comment by azaroth42** [comment]
Okay, but shouldn't it also be in the human readable representation?

**Comment by workergnome** [comment]
Yes.  But for now, I think including the version number on the homepage would suffice.  Let's worry about headers and the like in the next version of the web site.

**Comment by azaroth42** [comment]
Tagging defer until we at least complete the documentation for the core use cases

**Comment by azaroth42** [comment]
Added text to the README at the top to this effect.

**Comment by workergnome** [comment]
Don't see this?

**Comment by azaroth42** [comment]
Ahh, it's in the features branch rather than master yet.
Currently:  https://github.com/linked-art/linked.art/blob/features/README.md

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-7c6ffb31f9a74513972287d9aa536cbc/page-1)

**Comment by azaroth42** [comment]
We're approaching the point where we need to have an answer for this, although a fully stable 1.0 is still some time away (and hopefully will involve more people!).  So ... a bump to the issue, if not yet un-defer.

**Comment by azaroth42** [comment]
This year, the Linked Art editorial group is aiming to stabilize the model and api for Object, Person, Group, Place and TimeSpan to close to 1.0.  In order to have a coherent model, it shouldn't be considered 1.0 until everything gets there, otherwise we will run into terrible consistency issues.

Which is to say, we all agree that the documentation, model, api and supporting infrastructure should be semantically versioned when it has had sufficient testing to be confident it meets requirements.

**Comment by azaroth42** [comment]
Closing - no further decision (yes to semver) or action (API is versioned to 1.0) needed
