### ISSUE TITLE
ARIADNE-compliant archaeological find model

### ISSUE THREAD

**Issue by ewg118** [linked-art/linked.art#285]
I have been in recent contact with Achille Felicetti, who has been working on the CRMarchaeo extension and the [ARIADNE](https://ariadne-infrastructure.eu/) data model for representing relations between objects and archaeological excavations. I have put together a basic TTL representation of a coin -> discovery -> geographic coordinates that aligns with CRMarchaeo, sci, and geo: https://gist.github.com/ewg118/021bb71c0c15ef0b2f50c7aad5a4edc3. The scenario here is the most common one: an object is found at a place, but not scientifically excavated, and therefore doesn't conform to the most complex ARIADNE model for detailing stratigraphic layers and excavation metdata.

Sometimes a place has specific coordinates (e.g., g a coin is found in a field by a metal detectorist), but sometimes the place is simply a gazetteer URI (a vase found in Vulci, http://vocab.getty.edu/tgn/7015539). 

I have attempted to put together a JSON-LD representation here: 

```
{
  "@context": "https://linked.art/ns/v1/linked-art.json", 
  "id": "https://finds.org.uk/database/artefacts/record/id/975239", 
  "type": "HumanMadeObject", 
  "_label": "WILT-5C537D", 
  "was_found_by": {
    "id": "http://example.org/discovery/1",
    "type": "Discovery", 
    "specific_technique": "http://purl.org/heritagedata/schemes/agl_et/concepts/145148",
    "took_place_at": {
      "type": "Place",
      "part_of": "http://data.ordnancesurvey.co.uk/doc/7000000000016999",
      "defined_by": [
        {
        "type": "Geometry",
        "Q9_is_expressed_in_terms_of": "http://www.wikidata.org/entity/Q215848",
        "asWKT": "POINT (51.30311833, -1.97269609)"
        }
      ]
    }
  }
}
```

New properties to be added to the Linked Art context:

`was_found_by` = `sci:O19i_was_object_found_by`
`Discovery` = `sci:S19_Encounter_Event` 
`asWKT` = `geo:asWKT`

Note that the context does not actually include the namespace URI for the CRMgeo extension (`geo`).

We'll probably also need to add a property for `sci:O19_has_found_object` so that the Encounter Event URI resolves and we want to point the event to one or more objects found during the event (a metal detectorist might find two coins simultaneously).

Another note is that the specific spatial location of the find may be known or unknown, but it always occurs somewhere _within_ the place defined by the gazetteer URI. The findspot is never _the_ gazetteer place URI directly.

Thoughts?

**Comment by ewg118** [comment]
I would also like to point out that I would much prefer to use the wgs84 ontology for simple lat/long coordinate properties over WKT. The W3C wgs84 ontology is used more frequently across many datasets on the web and is therefore more interoperable than CRMgeo. Ideally, the CRMgeo ontology would relate the SP5_Geometric_Place_Expression to wgs84:SpatialThing in some capacity.

**Comment by ewg118** [comment]
Here's an updated proposal that expands some properties into arrays with `id`, `type`, and `label`, as per other examples in the model.

```
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://finds.org.uk/database/artefacts/record/id/975239",
  "type": "HumanMadeObject",
  "_label": "WILT-5C537D",
  "was_found_by": {
    "id": "http://example.org/discovery/1",
    "type": "Discovery",
    "specific_technique": [
      {
        "id": "http://purl.org/heritagedata/schemes/agl_et/concepts/145148",
        "type": "Type",
        "_label": "Metal Detecting Use"
      }
    ],
    "took_place_at": {
      "type": "Place",
      "_label": "Farmer X's Field",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300343519",
          "type": "Type",
          "_label": "fields (land)"
        }
      ],
      "part_of": [
        {
          "id": "http://data.ordnancesurvey.co.uk/id/7000000000016999",
          "type": "Place",
          "_label": "Easterton"
        }
      ],
      "defined_by": [
        {
          "type": "Geometry",
          "Q9_is_expressed_in_terms_of": "http://www.wikidata.org/entity/Q215848",
          "asWKT": "POINT (51.30311833, -1.97269609)"
        }
      ]
    }
  }
}
```

**Comment by ncarboni** [comment]
Why not using 
```turtle
crm:P168_place_is_defined_by "POINT (51.30311833, -1.97269609)"^^<http://www.opengis.net/ont/geosparql#wktLiteral> 
```
Because for wkt the CRS84 is the default reference system used.

If you want, following the syntax recommended in [geosparql](http://www.opengeospatial.org/standards/geosparql), you can specify the spatial reference system using a CRS URIs as part of the WKT literal. Example:
```turtle
crm:P168_place_is_defined_by "<http://www.opengis.net/def/crs/EPSG/0/4326>
POINT(51.30311833, -1.97269609)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>
```

However, I recommend to first check if it does work with your visualisation library.

**Comment by ewg118** [comment]
Doing that necessitates additional string parsing in the SPARQL-to-GeoJSON serialization that gets displayed in Leaflet. Not that it's impossible. Creating a node for the `Geometry` as opposed to inserting a WKT literal for `crm:P168_place_is_defined_by` allows me to insert separate properties for lat and long. See point number 3 here: http://kerameikos-project.blogspot.com/2019/10/linked-art-data-harvesting-and-aligning.html

The system harvests JSON-LD according to the above spec, but also places a wgs84:SpatialThing class on the node, which means I can use wgs84:lat and wgs84:long in addition to crmgeo:asWKT.

**Comment by ewg118** [comment]
It's also theoretically possible that people might use other coordinate projection systems than the standard WGS 84.

**Comment by azaroth42** [comment]
Is this different from #230? I think we should close one in favor of the other ... and would propose to keep this one.

**Comment by ewg118** [comment]
Yes, close the other one.

**Comment by azaroth42** [comment]
* S19 as class, "Encounter" as name (as Discovery is very specific to the documenter -- other groups may have known about it)
* O19 using "encountered" (for same reason)
* S19 is part_of Provenance Activity (as other things happen at the same time)

**Comment by azaroth42** [comment]
Done here: https://linked.art/model/provenance/encounters.html
