### ISSUE TITLE
JSON syntax highlighting of green/red color is poor accessibility

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#286]
... for red/green color blind people. Should change the styles to use more accessible color combination.

**Comment by firstladymb** [comment]
@azaroth42 Happy to help update the codehilite colors to be more accessible. 

If you want to keep the same background color, we could do something like this:
![image](https://user-images.githubusercontent.com/26513119/67625870-3d620300-f801-11e9-963d-f0e0ba176987.png)

I put the background color into this tool to play around with some color combinations:[http://colorsafe.co/](url)

![image](https://user-images.githubusercontent.com/26513119/67625886-7d28ea80-f801-11e9-90e0-eb05c2ba9862.png)

If you give me a starting point or some direction, I would be happy to put together a few palette choices to choose from. 

Let me know if you'd like me to take this one!

**Comment by azaroth42** [comment]
@firstladymb Thank you so much for the colorsafe.co reference, that's super useful.  I've made the updates to the CSS to use some of the safe colors :)
