### ISSUE TITLE
Should object part types have a meta-type?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#288]
E.g. should the type "Frame" have a metatype? And if so, is it an "Object/Work Type" like Painting, or is it different?

**Comment by edgartdata** [comment]
Can we make provision for a poly hierarchical structure? For example, it is unclear (to me!) if this work is a painting or a sculpture or mixed media: http://ink.nbmaa.org:8080/emuseum/objects/9257/west-rock-with-branches?ctx=f8599aea-dede-4947-846d-9fa53b94ed28&idx=0 
![image](https://user-images.githubusercontent.com/4093644/67034764-4f97bf00-f0e6-11e9-882c-42efb73237dd.png)

**Comment by azaroth42** [comment]
That's fine -- the same object can be both a painting and a sculpture, or part can be a painting and another part a sculpture.

It's the types that are only ever parts (frame, support, top, left-side, etc) that aren't really "object types" ... but the list of potential types is very long. So following the decision about the types-of-types pattern for objects, they should probably have their own meta-type ... but is that needed (given that they're parts by the `part` relationship) and if it is, what should it be?

**Comment by ncarboni** [comment]
How would the meta type works in practice?

**Comment by azaroth42** [comment]
The same way as for the meta-type for the full object's type, we'd add a "Part of Object Type" on "Frame", the same way as we will add "Object Type" to "Painting".

e.g. something like:

```
{
  "type": "HumanMadeObject"
  "classified_as": {
    "id": "aat:frame",
    "type": "Type",
    "classified_as": {
      "id": "aat:object_part",
      "type": "Type"
    }
  }
}
```

**Comment by cbutcosk** [comment]
FWIW in general I find the meta-types pattern challenging to reason about and implement, but especially if the source data are coming from most actually-existing collections management systems where part / whole vs part / part distinctions are often a pain. As an optional pattern it seems fine but not as a requirement?

**Comment by azaroth42** [comment]
Yes, agreed! The issue is if you do have a type that you know is a part (e.g. Frame, Support, Base, etc etc), should you also put a meta-type on that in the same way as for object types generally.  I think the answer is yes.

So it would be optional to have a type, but if you do, then the object_part meta-type would be required.

**Comment by azaroth42** [comment]
Done. Eg: https://linked.art/model/object/physical/#sides-of-an-object
