### ISSUE TITLE
Are Shape/Color properties of the HMO or the VisualItem?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#289]
We currently have them as properties of the `HumanMadeObject`, as they're both somehow physical. But the coca-cola logo is always red with its distinctive shape, regardless of whether it's printed on a billboard, or on a bottle wrapper, which leads me to question whether they should instead be on the `VisualItem` that the object shows.

Arguments in favor of HMO:
 * For objects that are shaped and do not have additional layers of pigment beyond the natural color (think a marble cube sculpture), then the color and shape are inherent to the material, which is physical.  It would be weird (IMO) to say that a sword shows a visual item which is sword shaped and steel colored.
 * If we don't need to introduce additional layers, then we shouldn't. Simple as possible says put it on the HMO.

Arguments in favor of VI:
  * For every print of a photograph, you would need to say it was individually the set of colors from the content. It would be much easier to simply say that the VI that all of the prints share has those colors.

Thoughts?

I'll document the HMO, as that is what we've discussed to date, but we can revisit that if VI is the preferred solution.

**Comment by natuk** [comment]
`VisualItem` is a conceptual object and as such it is impossible to have either shape or colour. The case you are describing for the photographic prints would need to be described individually anyway as a likely research question for that case would be "how are the colours different in the photographs showing this `VisualItem`?", e.g. when the coca-cola logo is black or grey. So I think stick with HMO.

**Comment by azaroth42** [comment]
I agree with the conclusion, but if shapes and colors are not part of the VisualItem, I have trouble describing its identity conditions. The black logo is the logo due to its shape, no? And you have different experience interacting with the black logo compared to the red logo.

The visual item of many flags relies entirely on color for their identity condition, as they're just a set of colored stripes.

I'm working on the docs for this under HMO so I think the issue can be resolved for Linked Art, but perhaps we raise the colors / visual item discussion to the SIG?

**Comment by natuk** [comment]
Yes, it would be interesting to discuss at the SIG, I think the identity condition of symbols depends on the intention. For the coca-cola logo, it may only be the outline, whereas for the Japanese flag the circle has to be red.

**Comment by ncarboni** [comment]
My two cents: 

Color is a dimension of the physical object. The perception of that dimension results in the classification of the object (or one of its part/feature) as red. 

The shape is also a physical feature. The perception and classification of the shape is conceptual (and socially harmonised) and bring upon the recognition of an entity (the recognition is dependant on the knowledge of the viewer in respect of the object). (I added some scattered details about this whole thing [here](https://www.mdpi.com/2571-9408/2/2/78)).

The identity of the shape could be recorded conceptually (as result of a classification) as well as using 3D/2D coordinates that identify it. But the 2D/3D coordinates would refer to the present of a specific shape or feature in the physical object. 
IMHO the two major problems are: 
+ we use E36 as visual type common to all instances, but we do need a singular example of it (what I declare as [Representation](http://w3id/vir/#IC9_Representation) in [VIR](http://w3id/vir))
+ the presence of "negative space" (what is the shape of a donut?)

**Comment by azaroth42** [comment]
Propose that we should raise this to the SIG, and assume HMO until there's some discussion otherwise.

**Comment by azaroth42** [comment]
Lacking any discussion to the contrary, I propose close -- that shape and color are documented as part of the physical object.

**Comment by azaroth42** [comment]
No discussion to the contrary, closing :)
