### ISSUE TITLE
Stop using hyde for website generation

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#291]
As it's not 3.x compatible and 2.x is end of life very very soon.

**Comment by ncarboni** [comment]
in [docs.swissartresearch.net](https://docs.swissartresearch.net) and [docs.cordh.net](https://docs.cordh.net) we use [mkdocs](https://www.mkdocs.org). It generate the documentation from markdown and it is quite flexible. Before building them up I flirted with [jekyll](https://jekyllrb.com) and the [doks theme](https://html.themejack.com/demo-doks.html)

**Comment by azaroth42** [comment]
Latest PyLD code is 3.x only, so currently need to it lock to 1.0.5. Should explore options with greater haste!

**Comment by azaroth42** [comment]
Yay done! Only took 2 years...
