### ISSUE TITLE
Errors mermaid js

### ISSUE THREAD

**Issue by ncarboni** [linked-art/linked.art#293]
In the page [https://linked.art/community/best-practices/vocabularies/index.html](https://linked.art/community/best-practices/vocabularies/index.html) the mermaid graph of the following entries:

+ [Group](https://linked.art/community/best-practices/vocabularies/index.html#group_1),
+ [Material](https://linked.art/community/best-practices/vocabularies/index.html#material)
 + [Measurement unit](https://linked.art/community/best-practices/vocabularies/index.html#measurementunit) 

are not loaded / present errors

**Comment by azaroth42** [comment]
Rats, thanks @ncarboni ! Will look into it

**Comment by azaroth42** [comment]
The data is broken (mea culpa) as the URI of the group is some crazy construct, so the diagram then also breaks.
