### ISSUE TITLE
Make "brief text" the metatype for brief texts

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#296]
Originally, we did not use the meta-type pattern. Now we have embraced it, but there is an instance when we had a pseudo-meta-type ... the use of "brief text" on linguistic objects for the Statement pattern.

It would be more consistent to have "brief text" as a type on the type of text, rather than on the linguistic object:

```
{
  "type": "LinguisticObject"
  "content": "This is a materials statement",
  "classified_as": {
    "id": "aat:materials-statement",
    "type": "Type",
    "classified_as": {
      "id": "aat:brief-text"
      "type": "Type"
    }
  }
}
```

**Comment by ewg118** [comment]
Should "brief text" be applied only to "statements"?

**Comment by workergnome** [comment]
What would happen in the instance where a materials statement would be, in one instance, a brief text, and in another instance, a long-form text?  Any use of this data in a graph store would make all of the records incoherent, since the metatype is associated with the type, not just the type in the context of this particular record.

Or is brief text only intended to be used in cases where that particular type of linguistic object is, in all cases within a given dataset, brief?

**Comment by azaroth42** [comment]
@ewg118, @workergnome  Yes -- we asked Patricia to add a concept by which we can call out short textual statements, as compared to longer form content. Thus, in Linked Art, the only things that would have these types are linguistic objects that are statements, and thus the only times they would be encountered would be when they're used as brief texts.

In the discussion about using the concept "materials" rather than a specific "material statement", Patricia then added concepts for all the statements. And thus if you associate "material statement" with a book, then you are simply doing it wrong. So there should now not be a case when a non-statement linguistic object is classified as a (x) which is in turn classified as brief text.

For example, per #247, biographical statement is now [300435422](http://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300435422), whereas a biography work would be [300080102](http://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300080102)

**Comment by cbutcosk** [comment]
I don't understand what `aat:brief-text` is achieving in the top example if there's already a classification around for the material statement itself. Is `aat:brief-text` a processing hint, a clarification of `aat:material-statement`'s place in a hierarchy of knowledge, an affordance for the global graph, etc? If i'm not interested in that layer can I ignore it as a consumer or producer?

To @workergnome 's point about classification collisions, "we'll just mint new AAT terms" does not feel scalable in the field for all users. I worry about collisions less on LOs, but for object classifications it's trivially easy to imagine contexts where a top-level metatype poisons lower-level classifications about, eg, objects depicted in a painting / photograph /etc. 

Maybe I'm wrong, it just seems like metatypes impose a very particular museological point of view that makes less sense the further from the HMO you get, with a large complexity / reasoning cost.

**Comment by azaroth42** [comment]
@cbutcosk It's a processing hint so that you don't need to have every consumer be pre-configured with every type of statement that any institution might want to create. If you only encounter types that the consuming application does understand, then brief-text (either on the LO or on the type) is ignorable. 

As to minting new terms -- they don't have to be AAT terms, but when we discussed this, we sent a call to the mailing list asking for the types of statements that institutions make. We then filtered out ones that only one institution had, and submitted the majority to AAT and they were added. So the common cases should all be covered already, and the edge cases can be either added to AAT if there's a common need, or local URIs used ... at which point the metatype pattern becomes very important.

I don't follow the object type issue. A photograph of a painting would have two types, but on very separate resources. And we don't claim that all photographs are artworks, only that photograph is a type of object. 

Also ... it's a museum / art oriented world view that we are trying to capture, not a universal one that can capture all possible views of a complex and uncertain historical reality.

**Comment by azaroth42** [comment]
Propose to make this change, barring any further discussion, after the call on 2020-01-15.

**Comment by cbutcosk** [comment]
@azaroth42 Thanks for explaining this, it answered my misgivings about metatypes. 

For textual cataloguing statements it strikes me that `aat:cataloguing-statement`, `aat:descriptive-cataloguing`, or even just `aat:statement` might be a clearer expression of producer intent. To the extent that the classification scheme is something a cataloguer or registrar may need to reason about in the course of events, grounding it in the field of cataloguing might keep people from confusion. But, uh, perhaps I'm alone in that. :)

**Comment by azaroth42** [comment]
Approved on call of 2020-01-15.

**Comment by azaroth42** [comment]
Done.
