### ISSUE TITLE
document reification model for changing attributions?

### ISSUE THREAD

**Issue by mdlincoln** [linked-art/linked.art#30]
Can we specify the solution we've discussed for GPI data in which different information objects make different assertions about the creator of an object?

(also, does this go in core? or is it an extension?)

**Comment by azaroth42** [comment]
Yes. I think the attribute assignment overlay model is an important addition, that any serious digital art history system will need to deal with. As it overlays, it shouldn't get in the way of people who don't have changing attribution / naming / etc. It's also the pattern documented for exhibition specific labels:  https://linked.art/model/exhibition/#exhibition-specific-labels  ... so I think it just needs calling out as a pattern.

**Comment by mdlincoln** [comment]
Great - a cross-link to that pattern would be v. useful.

Did we settle on the AttributeAssignment pointing to Appelations for our case, or to Actors?

**Comment by azaroth42** [comment]
If we know the period in which the assignment held (e.g. it was thought that X was the artist from 1904 until 1976, then we can just assign a timespan to the assignment? Or is that saying that it took 72 years to make the assignment?

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-dbeab6c0975947f79048604696359f4c/page-1)

**Comment by azaroth42** [comment]
After discussion, the AA's timespan should be just the time period in which the assignment was made. The usage is impossible to determine, and makes no sense in a global context -- /who/ was using it?

Assignments can be made as part of a super activity, such as curation or acquisition or inventory. It is not possible to infer that the bounds of this super activity apply to the usage in most circumstances.

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-0390e3e16502496b8d52967777d5633c/page-1)

**Comment by azaroth42** [comment]
I'm running into conflicts between branches, so I'm going to merge the attributes branch to master. We can further refine as needed.

Closing the issue, can reopen or open a new one if there are further requirements.
