### ISSUE TITLE
Supply GeoJSON geo extent?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#300]
It is straight forward to translate between WKT and GeoJSON using one of many code libraries, however it might be useful to provide it directly?

Per the discussion at the beginning of #69, WKT is a better candidate if we have to pick exactly one format ... however things have moved along in JSON-LD since then as well, and now we have a [JSON literal datatype](https://www.w3.org/TR/json-ld11/#json-literals) that could capture the GeoJSON directly in the graph, in a way that's friendly to web developers without getting tangled in GeoJSON-LD knots.

One datapoint - Arches exports GeoJSON representations (but a WKT datatype would not be a complex thing to add either).

**If** we want to support this, then we could define a `defined_by_geojson` as an alias for `P168_place_defined_by`, but takes a JSON literal as its value instead of a string literal.

**Comment by VladimirAlexiev** [comment]
Isn't `P168_place_defined_by` also used to capture a WKT literal? 
If I read the JSON Literal section correctly, the kind of value can be distinguished by datatype: `geo:asWKT` vs `rdf:JSON`. And you can have two values of `P168_place_defined_by` for the two representations. 

If you mean `defined_by_geojson` to be a JSON LD alias (term) that also fixes `@type: rdf:JSON` then I completely agree. With a similar `defined_by_WKT` for the other datatype. (Btw I'd use proper capitalization `defined_by_GeoJSON`)

**Comment by azaroth42** [comment]
Closing as WKT is easy enough to work with and convert to GeoJSON / GeoJSON-LD. Provide one way, not multiple.
