### ISSUE TITLE
Always subdivide Production?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#302]
We have found it useful to *always* subdivide `Production` activities for consistency across several use cases:

* Multiple artists requires the subdivision regardless
* When some aspects are uncertain (that can be expressed as attribute assignment of a partition), but there are aspects which are certain (that can be expressed directly in the data, on the top level Production)
  * For example, when the overall work is clearly influenced by some object or style, but we don't know that any individual contributor was so influenced.  
  * Or if we know that the work was produced in the 15th century, in Paris, and we are uncertain about any individual artist.

Consistency of patterns, even with only the first bullet, would argue that we should always partition the production ... however this is not an intuitive pattern and could introduce confusion. It's highly unlikely to be found "in the wild", as opposed to from people following Linked Art, and thus also creates some divergence.

Discuss :)

**Comment by ajs6f** [comment]
"in the wild" means in other CRM-based data?

**Comment by azaroth42** [comment]
Sorry, yes, other CRM based data that wasn't influenced by Linked Art discussions.

**Comment by johnmcquaid** [comment]
Even removing the case of multiple artists, so many works of art are assigned a creator such as follower of Leonardo or Florentine 15th century that despite any confusion always partitioning production seems to be the best option.

**Comment by ajs6f** [comment]
As y'all may recall, I rate CRM-compatibility much lower on the priorities than consistency. On another angle, most of our immediate use cases and most of our potentially-interesting applications come from within art curation/preservation/provenance/etc, so if it's easier for art-centric L.A consumers to have the division all the time, 'nuff said. We can move on to the wider world once we fully conquer our own yard. :sweat_smile:

**Comment by azaroth42** [comment]
Discussion at F2F: 

* No to requiring it - the consistency is illusory because there's still the tests needed for how many parts, and for where the timespan sits.

* Can always partition if you want ... but if you do for a single case, there's confusion as to the top event vs the parts, the same as the Provenance Activity pattern.

**Comment by azaroth42** [comment]
Closing, still wontfix :)
