### ISSUE TITLE
VisualItem represents class of thing?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#305]
The documentation currently has three patterns for describing the content of a visual item (the image content).

* `represents` for entities that you can point to (the sitter, a painting, etc)
* `about` for subjects that you can't point to (war, love, etc)
* `classified_as` for style and similar classifications about the overall image content

But we do not have a pattern for things that you can point to, but are not identified entities.  For example, a painting of flowers shouldn't require instantiating an entity for each flower if all you want to do is say that there are flowers depicted.

CRM allows for anything to be the subject of `represents` including non-physical things. Thus `Type`s can be represented ... such as a `Type` for flowers. This seems better than requiring a lot of anonymous things just to add the class to them, even if it's a little bit strange to say that you can point to a class of thing.

**Comment by natuk** [comment]
Following the LCD discussion on negative statements, there is a nascent proposal to introduce properties whose range is always E55 Type. So `E19 → P56 bears feature → E26` would require the creation of `E19 → Pxx bears feature of type → E55 Type`. This would be negated by `E19 → Pxx NOT bears feature of type → E55 Type`. So in the case here you could have: `my image → Pxx represents entity of type → flowers (E55)`. Obviously if this goes ahead, it will take a while to compile the new properties. But it is a relevant use case.

**Comment by azaroth42** [comment]
This would follow the general / specific pattern of other properties such as P16 / P125, P20 / P21,  P32 / P33,  P108 / P186, and so on.

Pxx_represents_entity_of_type seems like another reasonable, and easy to motivate, addition.

**Comment by azaroth42** [comment]
Raised: http://lists.ics.forth.gr/pipermail/crm-sig/2020-February/004257.html

**Comment by Habennin** [comment]
The other side of this one, just looking over the issue in preparing for the SIG, is that p138 already points to E1 so in LinkedArt we could just make a pattern that restricts it without requiring a new property. I agree that there is a precedent with the other properties you point out here. That being said, it causes the introduction of a new property, where another aim of LinkedArt is to simplify the model. I don't have a strong opinion either way. If one introduced a new property would it be a subproperty of the existing p138 just narrowing the range?

**Comment by azaroth42** [comment]
The question for me is whether we should distinguish between the type and an anonymous instance of the type, and the inferences that one might correctly or incorrectly draw from that.

If Visual Item X represents a HumanMadeObject B, and Visual Item Y represents a HumanMadeObject B, then we should reasonably conclude that both X and Y "visually represent" the same thing.  However if Visual Item V represents a Type A, and Visual Item W represents a Type A, then it does not seem reasonable to conclude V and W visually represent different instances of the Type, but instead that they both represent the Type itself.

For Types like "beach" or "flower" the distinction for instance vs concept might be clear -- there isn't an ur-beach or an ur-flower. But for concepts that are more theoretical, such as redness or love ... is it an instance of love that is represented that's different from another instance of love?
Conversely for somethings there *is* an ur-instance ... does the visual item represent the holotype or an instance of the type?

Activities aren't physical, but can have visual depictions, so I understand why it must be E1 as the range for the property, but there are various branches that I think make no sense, including Type.  (Also Dimension, Appellation, Propositional Object, etc.) 

I agree, of course, that we should reuse when possible and fewer is simpler than more ... until it becomes inconsistent. I think that a new property would be consistent with the existing pattern of general being separate from specific, and avoids the instance / holotype issues

**Comment by natuk** [comment]
I think you are right Rob, it is difficult to depict a type. The way I understand it (after a lot of discussion with Martin and Carlo re negative properties) is that the painting does not depict the type, it depicts an entity which is of a type. So for the painting of the flower we can say that "there existed an entity (maybe Human-Made Thing) of type: flower". When we have still life painting, this is what happened.
If, however, the flower is painted from memory, then there was no flower, there was a conceptual object. A conceptual object cannot be of type flower, but it can be of type "fictional flower"...

With the usual apologies if I am confusing things.

**Comment by azaroth42** [comment]
I think that's the pattern, that is being short-cut around due to not knowing (and having no way to ever know) whether the flower was real or fictional. 

So another reason for introducing a property would be to have two different long-cuts for the same shortcut - depicts conceptual thing of type [fictional] flower versus depicts physical thing of type flower without being explicit as to which is the correct long-cut.

Whether the conceptual thing and the physical thing can both be of the same class is, I think, up to the definition of the external vocabulary term being used.  If it's just flower without any relationship to existence or fictional, the CRM should not be making requirements on that external taxonomy. If it is known to be fictional, then great. If it's known to have existed, then great. If it's not known either way, we at least know it's a flower.

I think we should make a property for this in linked art, and then replace with a SIG ratified version when it comes.

**Comment by azaroth42** [comment]
SIG approved PXX represents_instance_of_type for inclusion in 7.2 (the upcoming, non-ISO, version)

**Comment by azaroth42** [comment]
Finally in 7.2.3 we have P199_represents_instance_of_type with scope note:

> This property establishes the relationship between an instance of E36 Visual Item and an instance of E55 Type that characterises the thing depicted.
