### ISSUE TITLE
Normal Custodian

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#308]
For objects that are on "permanent" or at least long term loan to an institution, we only have a transfer of custody.  But that custodian can then lend it to someone else, with the requirement that it be returned to them.

For example, if we have custody of an object but it’s a permanent loan from a donor, and we lend it to another organization for an exhibition, then the owner doesn’t change (still the donor, probably wanting to remain anonymous) and there’s a transfer of custody from ourselves to the exhibiting organization.  If that’s a travelling exhibit, it might pass through several custodians before it should eventually return to us.
 
There does not appear to be a way to track this not-quite-an-owner but not-just-the-current-custodian state.  The only way that I can see at the moment without introducing a new relationship is to model the right of permanent custody separate from the right of temporary custody…  and this opens the rights and temporal validity can of worms.

Another option would be to introduce `has_current_permanent_custodian` as a relationship, similar to `P54 has current permanent location` -- that is the "normal" location of the object, but at any given time it might not currently be there (e.g. the coin's normal location is in a particular case, but it might be in an exhibition or being conserved).

I have raised the question to the SIG

**Comment by azaroth42** [comment]
From provenance perspective we can solve with a Type on the transfer of custody to make sure that we can find permanent loans rather than temporary loans for conservation or exhibition.

The split for the has_current_permanent_custodian can be discussed in the exhibition pattern, as that affects the documentation of the exhibition.

**Comment by aisaac** [comment]
It could be that there are several "permanent" custodians. The safest bet from a modeling perspective would be to rely on the chain of provenance events that track the changes of custodianship.

**Comment by azaroth42** [comment]
Raised:  http://lists.ics.forth.gr/pipermail/crm-sig/2020-February/004251.html

**Comment by azaroth42** [comment]
Discussion in the SIG on 2020 - not accepted.  Instead the suggestion is that we should classify the transfer of custody (per comment on Jan 28) and to assign the exhibition as the motivation for temporary transfers. 

The existence of P54 has permanent location was questioned, and an issue to be raised about deprecating it on the same rationale as above.  So we need some required vocabulary about this, as the interpretation is critical to know which institution is the "master" custodian.

**Comment by azaroth42** [comment]
Call of 2020-11-04: Mint our own property to assert on the object, and also classify the transfers of custody (in provenance entries) for permanent vs temporary custody, and optionally also the purpose of the transfer (exhibition, conservation etc)

**Comment by azaroth42** [comment]
SIG meeting of 2021-03-10:  current_permanent_location was maintained, and current_permanent_custodian was rejected, so we will mint our own property for symmetry.
