### ISSUE TITLE
Do we have a documented example for expressing image rights?

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#311]
Do we have a documented example for expressing image rights and basic notions of standard vocabularies for expressing those rights along with a use context where applicable, e.g. CC0, fair use, expressly no rights?  Rights is potentially a very complicated scenario and so a text description of a rights statement will probably be necessary for clarification, but I think it would make sense to talk about some general rights buckets and general context buckets to allow segmentation of rights for images and other resources carrying the most commonly encountered set of rights.  I ask because I'm now getting requests from aggregators to use our collection API to detect when imagery changes.  I realize that we are not expressing rights of those images - the data enforcement is handled by our IIIF server - but the rights need to be expressed as well so that parties we authorize to download image sources can respect the rights associated with those resources.

**Comment by azaroth42** [comment]
We did, but it's not in sync with recent discussions about rights acquisitions etc. We should re-evaluate.

**Comment by azaroth42** [comment]
For example:

https://www.getty.edu/art/collection/objects/54724/man-ray-mona-lisa-as-seen-by-duchamp-la-joconde-vue-par-duchamp-american-1921-1922/

Copyright is owned by the Man Ray Trust, ADAGP, Artists Rights Society, and Succession Marcel Duchamps.

I've had inquiries from various rights oriented organizations as to the use of Linked Art -- perhaps we can put in some best-attempts for now and organize some joint discussions after we tackle Exhibitions?

**Comment by azaroth42** [comment]
Am working on #283, as a precursor to this issue.

**Comment by azaroth42** [comment]
We have run out of time and need to make a choice for 1.0 on this one.

I think there's two possibilities:

1.  The human readable form -- just have a rights statement as a linguistic object. No need for additional modeling.
2.  Use E30 Right -- the structured data form. Given the use case from Dave, I think we need to allow this as well.

In CRM, E30 is a thing-specific instance of a right, not the generic right itself.  Thus an E30 is the particular right, held by a particular actor, over a particular thing.  The type of right is given with `classified_as`:

![rights_structure](https://user-images.githubusercontent.com/871868/99397193-b884d400-28b0-11eb-9a3d-bf662a889455.png)

This has two weirdnesses ... first, the right is held by everyone, not any particular actor. Secondly, we need to treat CC-BY as a Type. Neither seem showstoppers, but slightly odd.

**Comment by aisaac** [comment]
For the record, how things are modeled in the context of rightsstatements.org, for simple and complex rights:
- the object (could be an image) has a rights statement (instance of dcterms:RightsStatements related to the object via a property like dc:rights, analogous to the subject_to in CRM above) which can be either simple (CC-BY) or complex (a "no copyright but no commercial use" (NoC-NC) statement that expires on a given date)
- in the case of a complex statement, its various attributes are represented following patterns from ODRL or other rights expression (or general metadata) ontologies. Importantly for interoperability, if the statement is derived from a standardized one (like a Creative Common or a RightsStatements.org one) this should be indicated via a property (in Europeana's EDM we use odlr:inheritFrom). See the first diagram on p9 at https://rightsstatements.org/en/documentation/technical-white-paper/

Some observations:
- it's not optimal that a standardized statement like CC-BY or NoC-NC could appear in several positions in the pattern (either as direct value of dc:rights or as the "base" for the more complex statement). But it's ontologically unavoidable: statements like NoC-NC are both rights statements of their own and a possible base for expressing more complex object-specific statements.
- the subject_to in the CRM pattern above is quite compatible with our pattern
- I am not so sure that the classified_as between the "Usage Right" node and CC-BY in the CRM pattern is a great match with our pattern. In our ontology rights statements are concepts so I guess they could be used in a classification relation. Still we (and ODRL that we re-use) really prioritized representing this link as a derivation one.

**Comment by azaroth42** [comment]
If it's a _statement_ then I think we have that covered with just the statement pattern?

If _all_ we need are statements, and just a way to say that there's a remote statement with a URI...

```
{
  "type": "DigitalObject",
  "referred_to_by": [{
    "id": "http://rightsstatements.org/NoC-NC/1.0/",
    "type": "LinguisticObject",
    "classified_as": [{
       "id": "aat:rights"
      "type": "Type"
    }]
  }]
}
```

**Comment by aisaac** [comment]
Maybe there can be some confusion about the word _statement_? For us they cover licenses, rules/access constraints, etc. and I'm not sure these can be reduced to linguistic objects.

**Comment by cbutcosk** [comment]
My very minor contribution: for the rights statement pattern it would be useful for non-semweb devs and legal departments to have an example in the documentation with the kind of statement @azaroth42 quoted higher upthread--"Copyright estate blah blah" and/or the cleared version, "Copyright ADGAP, Estate blah blah."

**Comment by azaroth42** [comment]
http vs https thread in IIIF: https://github.com/IIIF/api/issues/1874#issuecomment-559176437

**Comment by azaroth42** [comment]
Getty and Yale came to the same conclusion (independently?) of:

```
subject_to [
{
  "type": "Right",
  "classified_as": [{
    "id": "http://rights-uri-here/",
    "type":"Type",
    "identified_by": [{
      "type":"Name",
      "content": "name of the right to show to the user"
    }]
}
]
```

**Comment by azaroth42** [comment]
This is done: https://linked.art/model/object/rights/
