### ISSUE TITLE
Document what is a "provenance event"

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#312]
And seek feedback :)

**Comment by aisaac** [comment]
Documentation at https://linked.art/model/provenance/ could better represent that production and destruction are somehow 'out of scope' of 'production events' in the section https://linked.art/model/provenance/#provenance-event
Moving 'production and destruction' before 'production events' and renaming 'production events' as 'other provenance events' could provide a first trick.

**Comment by azaroth42** [comment]
Moved production, destruction to the object part of the documentation.

**Comment by azaroth42** [comment]
Seeking feedback time! :)

Comments on: https://linked.art/model/provenance/#provenance-event

Due by 2020-03-25 call.

**Comment by azaroth42** [comment]
Closing. 4 years for comments is long enough :D
