### ISSUE TITLE
Does P9 sufficiently capture intent of actor?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#316]
For partitioning activities, we use `P9_consists_of` with the definition:
> This property associates an instance of E4 Period with another instance of E4 Period that is defined by a subset of the phenomena that define the former.

Question is whether, when used with Activities, the intent of the actor that carried out the wider activity can be considered as included in the subset of phenomena.

For example, if there is an activity of writing a book, and that is then partitioned into writing individual chapters, the above definition would not lead me to conclude that the writing of the chapters was much more than temporally aligned with the writing of the book. Thus does the intent of the author to write a book in the creation of the text become part of the phenomena that can be subset into the intent of the author to write a chapter of the book?

**Comment by Habennin** [comment]
Do you recall the motivating case?

**Comment by VladimirAlexiev** [comment]
Well, yeah.
"P10 falls within" is the weaker version that implies only spatio-temporal inclusion, without coherence of intent or phenomena.

(Plus: never shake a beehive)
