### ISSUE TITLE
Modelling inscriptions and signatures

### ISSUE THREAD

**Issue by michielhildebrand** [linked-art/linked.art#348]
Hey,

On the website I can't find documentation on modeling inscriptions and signatures. I guess this must have been discussed before. Can someone point me to the right place? Is there a common pattern already?

On the best practices page I found the relevant AAT terms in the section on LinguistObject https://linked.art/community/best-practices/vocabularies/#linguisticobject

Combing the shows pattern with the Linguistec Object the following would work for us. Not sure about "represents" in this case. 
```json
"shows": [
  {
    "id": "https://linked.art/example/VisualItem/1", 
    "type": "VisualItem", 
    "represents": [
      {
        "id": "https://linked.art/example/inscription/3", 
        "type": "LinguisticObject", 
        "classified_as": [
          {
            "id": "http://vocab.getty.edu/aat/300028702", 
            "type": "Type", 
            "_label": "inscriptions",
          }
        ], 
        "content": "The actual inscription"
      }
    ]
  }
]
```

**Comment by azaroth42** [comment]
Hi @michielhildebrand, thanks for the very good question! I agree that this isn't and should be documented clearly in the object section.

I think there's two possible routes...

1.  The pattern laid out above, where `VisualItem` is the appearance-of-text and the `LinguisticObject` is the content-of-text. If it was important, for example, to say that the signature of Van Gogh in Irises had some particular visual appearance, then this could be valuable.

2.  The `carries / carried_by` pattern, where a text (a `LinguisticObject`) is carried by one or more `HumanMadeObject` instances as per here: https://linked.art/model/document/#physical-objects-conceptual-texts

My preference would be the latter, as unless we have some visual aspect of the inscription / signature that needs to be represented in the data, it could be as simple as:

```
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "type": "HumanMadeObject",
  "carries": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300028705",
          "type": "Type",
          "_label": "Transcribed Signature"
        }
      ],
      "content": "Vincent"
    }
  ]
}
```

Thoughts everyone?

**Comment by michielhildebrand** [comment]
Thanks for your clear breakdown of the two routes. The "carries" is a simpler pattern indeed. 

I do not yet know all the requirements, but in the source data I have seen fields like "inscription_position". This would require the first pattern. On the other hand in the few examples that I saw the position was empty :)

**Comment by azaroth42** [comment]
Positioning ... It would be very interesting to see what information is recorded, and whether anyone else has similar knowledge in their systems!

We have been discussing in the conservation domain using annotations on a digital image as a mechanism to locate a particular area within an object, e.g. where a sample was taken from or where an experiment was performed.  This could equally be used to position a feature of the artwork's visual content.

So instead of the measurement, there would be the signature `LinguisticObject` related from either the "physical part" via `carries` or the "visual work part" as in your pattern.

<img width="525" alt="disco-annotation-polygon" src="https://user-images.githubusercontent.com/871868/79773759-b5a80d80-82e6-11ea-96ac-b2f6b8a38532.png">

@Habennin Another use case to consider?

**Comment by beaudet** [comment]
We record the position of inscriptions (and I think marks too) but I believe only in text form.  I'll double check.

On Apr 20, 2020 12:11, Rob Sanderson <notifications@github.com> wrote:

Positioning ... It would be very interesting to see what information is recorded, and whether anyone else has similar knowledge in their systems!

We have been discussing in the conservation domain using annotations on a digital image as a mechanism to locate a particular area within an object, e.g. where a sample was taken from or where an experiment was performed. This could equally be used to position a feature of the artwork's visual content.

So instead of the measurement, there would be the signature LinguisticObject related from either the "physical part" via carries or the "visual work part" as in your pattern.

[disco-annotation-polygon]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F871868%2F79773759-b5a80d80-82e6-11ea-96ac-b2f6b8a38532.png&data=02%7C01%7C%7Cea1ab22418d74778d57108d7e5458678%7C53f6461e95ad4b08a8da973e49ae9312%7C0%7C0%7C637229959083054539&sdata=VNyegbWYJrAvaZv8uQaJmAxztSvWJs%2BmdAaSTRZu7vw%3D&reserved=0>

@Habennin<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHabennin&data=02%7C01%7C%7Cea1ab22418d74778d57108d7e5458678%7C53f6461e95ad4b08a8da973e49ae9312%7C0%7C0%7C637229959083064531&sdata=dYhO%2BRfWiByqHFvgAJxUSSZP%2FEc6PxGkrJYeS3O%2FokU%3D&reserved=0> Another use case to consider?

**Comment by ivozandhuis** [comment]
The Dutch RKD does enable storing the location of an inscription/label in its database. See for example: https://rkd.nl/en/explore/images/52947 The same construction is used for signature as well as for labels 'in verso', so at some point, besides position, dating a label could be useful, although this is not the case at RKD (yet).

@azaroth42 could you help me and provide a code-sample for your idea, related to the conservation?

**Comment by azaroth42** [comment]
> The text describes where on the object the inscription is positioned, and provides a transcription of the text; same for the marks.

Yes, this is already covered in the Statements pattern - an inscription statement that isn't a transcription, but instead a description is the common scenario outside of conservation (in my experience) as the exact location is less important. Instead, for conservation, the difference in location can be crucial for reproducibility or learning about the results of the conservation action.  (cc @natuk!)

The JSON-LD structure:

```
{
  "@context": "https://linked.art/ns/v1/linked-art.json", 
  "id": "http://lod.example.org/museum/VisualItem/0", 
  "type": "VisualItem", 
  "_label": "Image content shown by the physical thing",
  "identified_by": [
    {
      "type": "Identifier", 
      "assigned_by": [
        {
          "type": "AttributeAssignment", 
          "used_specific_object": [
            {
              "id": "http://lod.example.org/museum/DigitalObject/0", 
              "type": "DigitalObject",
              "_label": "Image Used for making Polygon"
            }
          ]
        }
      ], 
      "content": "polygon describing region in some format here"
    }
  ]
}
```

**Comment by johnmcquaid** [comment]
Frick photoarchive practices for signatures are in text and have the following pattern: 1 Signed, dated and/or inscribed. 2 Location on work. 3 Text in quotation marks. 4 Description about text in straight brackets, line breaks denoted by a forward slash". Multiple signatures are included in the after the word and. I can provide an export with many more examples if necessary.

Simple example: Signed and dated lower right: "Sargent 1914".
Complex example: Signed, dated and inscribed upper right: "AD / 1500 / aet 38 [AD in monograph]".
Multiple example: Signed and dated lower right: "W.H. 65." and inscribed under mat: "Sketch of Lincoln and Grant at City Point, Va. 1865.".
Example with everything: Signed, dated and inscribed upper right: "JMW / 1895 [JMW in monograph]" and inscribed lower center: "Jane /  Tulieres".

**Comment by edwardanderson** [comment]
Rijksmuseum have textually-described inscription positions in the CMS. I haven't collected examples of the scientific data yet.

[Road behind the Parsonage Garden in Nuenen, Vincent van Gogh, 1884](http://hdl.handle.net/10934/RM0001.COLLECT.7672) is signed by hand "Vincent" in the bottom left corner.

```xml
      <inscription>
        <inscription.type>
          <value lang="0">signature</value>
          <value lang="1">signatuur</value>
          <PersistentIdentifier>RM0001.THESAU.53814</PersistentIdentifier>
        </inscription.type>
        <inscription.position>
          <value lang="1">linksonder</value>
        </inscription.position>
        <inscription.content>Vincent</inscription.content>
        <inscription.method>
          <value lang="1">handgeschreven</value>
        </inscription.method>
      </inscription>
```

Trying to follow @azaroth42's positioning pattern (as pure CRM with blank nodes - for now), can I identify the signature's VisualItem with the textual-position content (_linksonder_ is 'bottom left'')?

```turtle
@prefix crm: <http://www.cidoc-crm.org/cidoc-crm/> .

<http://hdl.handle.net/10934/RM0001.COLLECT.7672>
  a <http://www.cidoc-crm.org/cidoc-crm/E22_Human-Made_Object> ;
  crm:P65_shows_visual_item [
    a crm:E36_Visual_Item ;
    crm:P138_represents <http://iconclass.org/25G3(POLLARD WILLOW)>, <http://iconclass.org/31A71>, <http://iconclass.org/46C1214> ;
    crm:P9_consists_of [
      a crm:E36_Visual_Item ;
      crm:P1_is_identified_by [
        a crm:E42_Identifier ;
        crm:P190_has_symbolic_content "linksonder" ;
        crm:P72_has_language <http://vocab.getty.edu/aat/300388256>
      ] ;
      crm:P138_represents [
        a crm:E33_Linguistic_Object ;
        crm:P2_has_type <http://hdl.handle.net/10934/RM0001.THESAU.53814> ;
        crm:P190_has_symbolic_content "Vincent"
      ]
    ]
  ] .
```

**Comment by vangoghworldwide** [comment]
For Van Gogh Worldwide we opted for the "carries" approach that @azaroth42 suggested. As a consequence we use a HumanMadeObject that is part of the artwork, instead of a VisualItem. See https://github.com/vangoghworldwide/linkedart#inscriptions

The nice thing of this approach is that it is also usable for labels/stickers.

**Comment by karinanw** [comment]
From Philadelphia Museum's of Art's TMS Style Guide:

**INSCRIPTION(S)**
Definition: Text inscribed on the work of art.

Content: List the material(s) used in the inscription as well as its support if other than the object itself,
the method used to make the inscription, and a description of the content and appearance, including
the location on the object.

Examples:
Center right: MARGGRET / HVNDERPFV- / NDIN IST AB / GEMACHT IRS / ALTER 41 IAR / DA
MANZALT / 1526 IAR AM / 22 TAG IENNARI / W H; lower right: 46
Center, on book: Domine l[abia mea] ape[ries]; on Virgin's halo: AVE MARIA GRATIA PLENA DOMINVS
TECVM
On reverse: Born December 15th 1752 Old Style / Died August 15 1835 New Style / Aged 82 years 7
mos 19 days.

**MARKS**
Definition: Maker’s or collector’s identifying mark(s).
Content: List the material(s) used in the mark, the method used, and a description of the content and
appearance, including the location on the object.

Examples:
Painted in blue under glaze: DOULTON & CO/ LAMBETH/ MB [monogram for Mary Butterton].
Maker's mark printed in red: crown surmounting circle enclosing design and #51.
Stamped: M Carlin and JME (monogram of furniture-makers' guild).

**SIGNED**
Definition: The artist’s or maker’s signature or mark.
Content: List the material(s) used in the signature as well as its support if other than the object itself, the
method used to make the signature, and a description of the signature’s appearance, including the
location on the object.

Examples:
Lower right: Claude Monet 91
Lower right: E. Boudin / [illegible] 94.
Signed in red on base: "Suzuki Seiichiro"
In graphite, lower right: Mabel Dwight

**Comment by azaroth42** [comment]
Discussion on call of 2020-09-23 - useful as an option for the cases when the information is available. Wouldn't be required, so if all a system has is text, then can just use a statement.

Good to have both -- statements are good for humans, structured data good for research. Can drill down into the detail.

**Comment by atiro** [comment]
The V&A data structure for it is:

```
    {
    "content": "",
    "inscriber": {
      "name": {
        "text": "",
        "id": ""
      },
      "association": {
        "text": "",
        "id": ""
      }
    },
    "date": {
      "text": "",
      "earliest": "",
      "latest": ""
    },
    "description": "",
    "interpretation": "",
    "language": "",
    "medium": "",
    "method": "",
    "position": "",
    "script": "",
    "translation": "",
    "transliteration": "",
    "type": "",
    "note": ""
  }

Mostly the information is in content & note. Position is used though for around 30k objects, with around 4k different free text entries:

  "A number is located under a drawing of a female head."
"A number is written below each drawing of a female head."
"appear three times in bottom half of sampler"
"approval green label"
"around base"
"Around base of lid"
"Around body"
"Around body of vessel"
"Around border on obverse."
"Around bowl"
"around buckle"
"around central band"
"Around exterior rim"

```

**Comment by beaudet** [comment]
We also have inscription and markings.  The content of signatures are recorded in the inscriptions data element although there's another flag that differentiates signatures from other types of inscriptions.

**Comment by aisaac** [comment]
Meta-comment: if one of the patterns here is also supposed to be used for representing the result of some (automatic) transcriptions in general, it would probably be relevant to mention the case in a more explicit way, as this would probably be interesting for many people!

**Comment by azaroth42** [comment]
> if one of the patterns here is also supposed to be used for representing the result of some (automatic) transcriptions in general, it would probably be relevant to mention the case in a more explicit way

Yes - this would be the `carries` case in my opinion ... we have transcription (from OCR/HTR) and what to say that it was created by a machine, and so forth. So a separate record, rather than embedding into the HMO object.

**Comment by cbutcosk** [comment]
@beaudet You might also consider a node with `format: "text/html"`, which IME provides better usability and parsing safety. Depending on the internal reference semantics of content in your CxMS's, HTML may provide better affordances for content that's more like markup than data.

**Comment by beaudet** [comment]
Thanks, that's not a bad idea.  There can be markdown in the texts authored in TMS although we try to stick with bold, italics, and underline.

**Comment by azaroth42** [comment]
Inscription footnotes: I would try to separate data from presentation to allow for differential reuse. We're never going to be able to capture all of the details of different web layouts, lest we reinvent HTML+CSS+JS, but the more different classifications (and other technical metadata ala format) on different bits of content, the easier it will be to reuse in different situations.
