### ISSUE TITLE
Model for recto/verso features of a page-like thing

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#35]
Such as the distinction between the front and back of a photograph, painting, page, print, panel, and so on.  

Some objects have artwork or modifications of interest on both sides, the majority only on one. The cases when there is interest on both sides should not complicate the majority situation where there is only interest on one.  The modifications could have happened at different times, by different people or be a single object with art on both sides that should be distinguished as to (for example) subject and depiction.

I _believe_ that the full CRM model would be something like the below. Whether this is justifiable or not is another matter!  There is a MMO representing the full object. Then parts for the support / frame, which can bear features for the recto/verso, which then have parts which are MMOs(?) of the artwork. 

```

{
  "@context": "http://linked.art/ns/context/1/full.jsonld", 
  "id": "http://lod.example.org/museum/object/0", 
  "type": "ManMadeObject", 
  "label": "What if we let Banksy spraypaint the back of Irises?", 
  "description": "Van Gogh's \"Irises\" and Banksy's \"Cat with an Assault Rifle\" on canvas in an oak frame. Banksy's spraypaint covers both canvas and supporting beams of the frame.", 
  "part": [
    {
      "id": "http://lod.example.org/museum/object/1", 
      "type": "PhysicalObject", 
      "label": "Support", 
      "classified_as": "aat:300014844", 
      "made_of": {
        "id": "aat:300014078", 
        "type": "Material", 
        "label": "canvas"
      }, 
      "bears_feature": [
        {
          "id": "http://lod.example.org/museum/ManMadeFeature/0", 
          "type": "ManMadeFeature", 
          "label": "Canvas Recto", 
          "classified_as": "aat:recto", 
          "part": {
            "id": "http://lod.example.org/museum/object/4", 
            "type": "ManMadeObject", 
            "label": "Irises", 
            "produced_by": {
              "id": "http://lod.example.org/museum/activity/0", 
              "type": "Production", 
              "carried_out_by": {
                "id": "ulan:Van_Gogh", 
                "type": "Person"
              }
            }, 
            "made_of": {
              "id": "aat:300015050", 
              "type": "Material", 
              "label": "oil"
            }, 
            "carries": {
              "id": "http://lod.example.org/museum/info/0", 
              "type": "InformationObject", 
              "label": "Van Gogh's conception of Irises"
            }, 
            "representation": {
              "id": "http://lod.example.org/museum/Image/0", 
              "type": "Image", 
              "format": "image/jpeg"
            }, 
            "depicts": "aat:flowers"
          }
        }, 
        {
          "id": "http://lod.example.org/museum/ManMadeFeature/1", 
          "type": "ManMadeFeature", 
          "label": "Canvas Verso", 
          "classified_as": "aat:verso", 
          "part": {
            "id": "http://lod.example.org/museum/object/5", 
            "type": "ManMadeObject", 
            "label": "Cat With Assault Rifle", 
            "produced_by": {
              "id": "http://lod.example.org/museum/activity/1", 
              "type": "Production", 
              "carried_out_by": {
                "id": "ulan:Banksy", 
                "type": "Person"
              }
            }, 
            "made_of": "aat:spraypaint", 
            "carries": {
              "id": "http://lod.example.org/museum/info/1", 
              "type": "InformationObject", 
              "label": "Banksy's conception of Cat with Assault Rifle", 
              "about": "aat:war"
            }, 
            "representation": {
              "id": "http://lod.example.org/museum/Image/1", 
              "type": "Image", 
              "format": "image/jpeg"
            }
          }
        }
      ]
    }, 
    {
      "id": "http://lod.example.org/museum/object/2", 
      "type": "ManMadeObject", 
      "label": "Frame", 
      "made_of": "aat:oak", 
      "part": {
        "id": "http://lod.example.org/museum/object/3", 
        "type": "PhysicalObject", 
        "label": "Structural beams of Frame", 
        "part": "http://lod.example.org/museum/object/5"
      }
    }
  ], 
  "current_location": {
    "id": "tgn:Los_Angeles", 
    "type": "Place"
  }
}
```

**Comment by azaroth42** [comment]
Given the addition of aat:work-of-art, the two part MMOs should also have this classification, but probably not the top level MMO which is the carrier.

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-29f75ce69aeb417c91d528e2bf6bc3fc/page-1)

**Comment by azaroth42** [comment]
Towards this:  https://features--linked-art.netlify.com/model/object/physical/#features

**Comment by azaroth42** [comment]
I think this is done. If there's any further definition needed, we can open more issues.

**Comment by workergnome** [comment]
Reopening for continued discussion, following discussion on March 4th at the Linked Art Working Group.

**Comment by natuk** [comment]
I think the proposed model here is reasonable. In bookbinding description where the recto/verso issue also comes up, we consider the cojoint bifolio (i.e. one sheet of parchment or paper) as a Man-Made Object and each page as a Feature. One bifolio will have four pages. Each page may have different painted miniatures on it, which are themselves separate Features.
From a conservation point of view I would be reluctant to consider the work of art outside its carrier. I can see the problem of each painting being a separate entity but this is not rock art, i.e. the support (carrier) was very much part of the original artwork and what happened on the back of the painting has not changed that. Arguably Banksy's choice of the specific support (which has a Van Gogh on the other side) is not random. Also, I am not sure how much work has been done to align AAT hierarchies with the CRM but work of art is under object.

**Comment by azaroth42** [comment]
See: https://github.com/linked-art/linked.art/issues/84#issuecomment-476353580 The two issues are essentially the same.

**Comment by azaroth42** [comment]
Closing in favor of #84
