### ISSUE TITLE
enhance exhibition model example to demonstrate how to model an object exhibition ID

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#353]
Our institution (I suspect this is common?) assigns exhibition IDs (DEX# below) to art objects that are part of an exhibition.  It would be helpful to see a fleshed out example of this in the documentation provided here: https://linked.art/model/exhibition/

Sample Data that can be used for Modeling:

Exhibition: Degas at the Opéra
open | close | venue mnemonic | venue name
09/24/2019 | 01/19/2020 | P | Musée d'Orsay
03/01/2020 | 07/05/2020 | W | National Gallery of Art

Exhibition Object for the NGA venue is listed below.  Note that some of these object properties can be overwritten at the exhibition level, particularly: title, catalog number, exhibition department ID, medium, displayDate, creditLine, dimensions, attribution, attributionInverted, photoRestrictions

I should note that there is also a link to the object loan and status of this object (approved, appeal, etc.) w.r.t. that particular loan.

title: Mademoiselle Malot, c. 1877
catalog number: no value in this case
DEX #: 1
medium: oil on canvas
display date: French, 1834 - 1917
credit line: National Gallery of Art, Washington, Chester Dale Collection, 1963.10.18
dimensions: overall: 81.1 x 65.1 cm (31 15/16 x 25 5/8 in.) framed: 106 x 90.8 cm (41 3/4 x 35 3/4 in.)
attribution: Edgar Degas
attribute inverted: Degas, Edgar
Photography restrictions: No specific instruction available. Contact the appropriate DEX exhibition officer for approval/direction prior to use of reproductions.
Object Loan Status: Approved
Object Loan ID: 12345
Key Object Flag: <unset, true, or false> - controls whether depictions of this object have been cleared for appearing in published materials

**Comment by azaroth42** [comment]
Yes. I think we discussed this in January, it just needs to be documented. Tagging as such.
(Also exhibition specific labels, descriptions etc.)
