### ISSUE TITLE
Role(s) in a production event

### ISSUE THREAD

**Issue by ncarboni** [linked-art/linked.art#356]
I am trying to find a way to describe roles in production events using linked.art. I know the question has been discussed, but I could not find any pattern in the documentation and/or issues.

At SARI We need to express that a person has a particular role within a production event. We have examples of several persons participating at the same production event, as well as examples where only one role and person are specified. 

My understanding is that we need to use sub-activities to define roles, but I was wondering where to specify the role itself. My guess would be to create both an activity(x) and its sub-activity(y). The sub-activity(y) would correspond to the actions that a person performed within an activity(x). The role of a person is then expressed by a type assigned to the sub-activity(y). Temporal boundaries (unless otherwise known) are assigned to activity(x) and not its sub-activity(y).

Probably an example would help:

```ttl
<https://linked.art/example/object/68> a crm:E22_Human-Made_Object ;
    rdfs:label "Painting" ;
    crm:P108i_was_produced_by <https://linked.art/example/activity/37> .

<https://linked.art/example/activity/37> a crm:E12_Production ;
	crm:P9_consists_of <https://linked.art/example/activity/37/role>  ;
	crm:P4_has_time-span <https://linked.art/example/time/18> ;
	crm:P14_carried_out_by <https://linked.art/example/actor/4> .

<https://linked.art/example/activity/37/role> a crm:E12_Production ;
	crm:P14_carried_out_by <https://linked.art/example/actor/4> ;
	crm:P2_has_type <http://vocab.getty.edu/aat/300025165> .

<https://linked.art/example/actor/4> a crm:E39_Actor ;
    rdfs:label "Artist" .

<https://linked.art/example/time/18> a crm:E52_Time-Span ;
    crm:P82a_begin_of_the_begin "1780-03-05T00:00:00+00:00"^^xsd:dateTime ;
    crm:P82b_end_of_the_end "1780-03-06T00:00:00+00:00"^^xsd:dateTime .
```

Of course this can be expanded and we would be able to say that an activity(x) has sub-activities (y, z) and two persons(a,b) are participant of one sub-activity only or more, in any combined fashion. 

Is this the semi-official representation of roles?

**Comment by ewg118** [comment]
Is it redundant to say that the Production event was carried out by the same actor which is linked to the sub-activity?

I don't know how granular we want to get, with roles vs. processes, but <http://vocab.getty.edu/aat/300025165> is a role of an agent, but <http://vocab.getty.edu/aat/300053225> is the process. In this case, I think you'd want to say the Production sub-activity has a type of the latter URI.

**Comment by azaroth42** [comment]
Yep.  It's documented here:  https://linked.art/model/object/production/#multiple-artists 

I can put "role" in the heading title to make it easier to find :)

**Comment by ncarboni** [comment]
> Is it redundant to say that the Production event was carried out by the same actor which is linked to the sub-activity?

It is, but personally I would still use it to make predefined search pattern work better.

> I don't know how granular we want to get, with roles vs. processes, but http://vocab.getty.edu/aat/300025165 is a role of an agent, but http://vocab.getty.edu/aat/300053225 is the process. In this case, I think you'd want to say the Production sub-activity has a type of the latter URI.

Yep, my bad. Got the wrong AAT term :-)
> Yep. It's documented here: https://linked.art/model/object/production/#multiple-artists
> 
> I can put "role" in the heading title to make it easier to find :)

Great, thanks!

**Comment by azaroth42** [comment]
Done
