### ISSUE TITLE
Date type normalisation to xsd:dateTime

### ISSUE THREAD

**Issue by edwardanderson** [linked-art/linked.art#358]
Hope it's alright to ask an implementation question.

For the expression of date accuracy in our CRM data layer, we're currently using a mixed economy of `xsd:gYear` `xsd:gYearMonth` and `xsd:date`.

When we generate our Linked Art JSON-LD, should we:

- extend the `@context` for P81 and P82 with these types?
- normalise the values and type with `xsd:dateTime` by appending dummy data for _first of the month at midnight_?

**Comment by edwardanderson** [comment]
I've read

- #239 
- https://linked.art/model/base/

... looks like I need to normalise to `xsd:dateTime`. To follow this up, is it then recommended to `Name` the `TimeSpan` with whatever my original `xsd:gYear` value was?

**Comment by azaroth42** [comment]
Yeah, the ontology specifies that it has to be`xsd:dateTime` for those properties. Arches only has day level granularity, so we just dummy in the missing hh:mm:ss values. Then indeed use a `Name` with the human readable name for the time span.
