### ISSUE TITLE
end_of_the_end is included, not excluded

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#371]
The SIG decided (their issue 417) that the `end_of_the_end` is **included** in the time range for the TimeSpan.
The beginning is still inclusive.

Thus the current representations include the first second after the end of the timespan, and they should not.
So our `end_of_the_end` values should instead of being `1971-01-01T00:00:00` should instead be `1970-12-31T23:59:59`

[Martin and Rob agreed that this was not wonderful, but the SIG generally felt that inclusive was easier to understand]

**Comment by beaudet** [comment]
yeah, the logical "problem" I guess is that a plank second cannot be expressed in any reasonable time format so ending at :59 seconds leaves a 1 second window of ambiguity.  Not the end of the world with cultural heritage, but might foreshadow interoperability issues in the future if merged with niche scientific applications.

**Comment by azaroth42** [comment]
Yes, 😿 Not a hill I'm going to die on, especially in the dank swamps of the SIG.
