### ISSUE TITLE
Content-type JSON-LD context

### ISSUE THREAD

**Issue by brechtvdv** [linked-art/linked.art#373]
When requesting "https://linked.art/ns/v1/linked-art.json", the content-type is set to "application/json".
This gives an error when trying to parse with a json-ld-context-parser.

Can you change the content-type to "application/ld+json"?

**Comment by azaroth42** [comment]
Oh, which json-ld library doesn't work with `application/json` for the context document?

Will see about changing the header ... I think it can be overridden in a _headers file.

**Comment by brechtvdv** [comment]
This one: https://github.com/rubensworks/jsonld-context-parser.js

Thanks in advance!

**Comment by azaroth42** [comment]
Can you try it with: https://api-0321--linked-art.netlify.app/ns/v1/linked-art.json and see if that fixes?
Thanks and apologies for the delays!

**Comment by brechtvdv** [comment]
Can't reach the document with the tool when running:
`jsonld-context-parse url https://api-0321--linked-art.netlify.app/ns/v1/linked-art.json`

Can you also add the access-control-allow-headers header?
for example: 
`access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept`

**Comment by azaroth42** [comment]
Done :) I now see:

```
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept
access-control-allow-origin: *
cache-control: public,max-age=86400
content-type: application/ld+json
```

Could you try again and see if that has solved it?

**Comment by brechtvdv** [comment]
Looks okay!

The JSON-LD parser struggles to parse it, because of the type-scoped contexts, but that's not a concern of this context. (https://github.com/rubensworks/jsonld-context-parser.js/issues/34)
