### ISSUE TITLE
Make _label for agent instances clearer

### ISSUE THREAD

**Issue by aisaac** [linked-art/linked.art#374]
In the [documentation for Production events](https://linked.art/model/object/production/#multiple-artists), and probably in other places, the _label associated with agent are too general and could be confusing for readers. 
For example one could think that "Sculptor" indicates the role of the agent in the production event, not its name (which is what it is supposed to be). It should eb changed to "Bob the sculptor" or anything that better reflects it is the label for the person and not their role.

**Comment by azaroth42** [comment]
Also the painting example that is intended as a description, but reads like a material statement, of "painting on canvas" in model/base (thx to @edgartdata)

**Comment by azaroth42** [comment]
Done by making everything explicit, real examples
