### ISSUE TITLE
Document & streamline data publication via GH repos

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#381]
Publication via GH and netlify is free. If it was easier to get data into GH (and it's not like it's very hard) and to link into a slot on the website (perhaps with a dynamic hostname) then we could provide a trivial and free hosting solution.

**Comment by jpadfield** [comment]
I would be interested in this. As part of the https://jpadfield.github.io/simple-site/ and https://github.com/jpadfield/cidoc-crm.examples work I have been exploring the automatic processing of data and creation of web resources with GH Actions so there could be some cross over, depending on the context :-)

**Comment by azaroth42** [comment]
Closing as unnecessary
