### ISSUE TITLE
Include condition checking events

### ISSUE THREAD

**Issue by natuk** [linked-art/linked.art#382]
It would be useful to include condition checking events as part of the Linked Art model which is helpful for the periodic check of collections and for object loans. At the meeting 16 Dec 2020 we discussed that this is better included as a separate section - possibly combined with conservation activity (see #383).

**Comment by natuk** [comment]
Pasting a possible structure to discuss here and at the next meeting:

```json
{
  "@context": "https://linked.art/ns/v1/linked-art.json", 
  "id": "https://linked.art/example/conservation/1", 
  "type": "Activity", 
  "_label": "Conservation Activity",
  "timespan": {
    "type": "TimeSpan", 
    "begin_of_the_begin": "2020-03-05T00:00:00Z", 
    "end_of_the_end": "2020-03-06T00:00:00Z"
  },  
  "carried_out_by": [
    {
      "type": "Person", 
      "_label": "Conservator"
    }
  ],
  "part":[
    {
      "type": "ConditionAssessment", 
      "_label": "Condition Assessment of Object",
      "note": "Regular condition check",
      "content": "Fine cracks throughout the object (crizzling)",
      "documented_in": [
        {
          "type": "Document",
          "_label": "Condition Assessment Report"
        }
      ],
      "identified": [
        {
          "type": "ConditionState",
          "_label": "Condition State",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300218594", 
              "type": "Type", 
              "_label": "Crizzling"
            }
          ]
        }
      ]
    }
  ]
}
```

I was not sure how to deal with multiple notes, i.e. one to describe the reason for the assessment and another for the actual content.

**Comment by azaroth42** [comment]
2021-01-06: Overall structure is accepted. Suggestion to use AttributeAssignment instead of ConditionCheck, with assigned / assigned_to, and then assign the Type directly to the object ... perhaps with a new relationship to avoid semantic weirdness of P2 in this case.

**Comment by natuk** [comment]
I propose to close this issue as it has now been merged and is visible on the website. Consider adding a link to the conservation section on the [main model page](https://linked.art/model/).

**Comment by azaroth42** [comment]
Done -- conservation linked from main page
