### ISSUE TITLE
How to flag hazardous material

### ISSUE THREAD

**Issue by natuk** [linked-art/linked.art#385]
We need to be able to identify objects made of hazardous materials. This can be done using [hazardous material](http://vocab.getty.edu/page/aat/300138222) as a category, or by including a separate note for which we would need to request a new AAT concept under [categories of information](http://vocab.getty.edu/page/aat/300435413).

**Comment by natuk** [comment]
Example of how this can be done combining the two approaches:

```json
{
  "@context": "https://linked.art/ns/v1/linked-art.json", 
  "id": "https://linked.art/example/object/48", 
  "type": "HumanMadeObject", 
  "_label": "Film roll", 
  "made_of": [
    {
      "id": "http://vocab.getty.edu/aat/300429277", 
      "type": "Material", 
      "_label": "motion picture film",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300138222", 
          "type": "Type", 
          "_label": "hazardous material"
        }
      ]
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject", 
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/???", 
          "type": "Type", 
          "_label": "Hazardous Material Statement", 
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049", 
              "type": "Type", 
              "_label": "Brief Text"
            }
          ]
        }
      ], 
      "content": "Extremely flammable nitrocellulose."
    }
  ]
}
```

I suggest that the categorisation using [aat:300138222](http://vocab.getty.edu/aat/300138222) is required while the extra statement is optional.

**Comment by azaroth42** [comment]
2021-01-06: Ask for a Hazardous Material note type, with fallback to aat:300138222 if necessary.
Noted that this is just flag and describe, not directly machine processable as to risk assessment or similar.

Move hazardous material up to be a Material, rather than a classification of a material to avoid all films being dangerous

**Comment by natuk** [comment]
Scope note and English label for new AAT term to describe notes about hazardous material:

**Term**: hazardous material description
**Scope note**: A description of the risks, primarily to humans, which are associated with handling a work due to the nature of the materials that it is made of.

**Comment by natuk** [comment]
This needs to remain open until the proposed new AAT term has been approved. If it is not approved we need to remove the corresponding entry from `vocab.py`.

**Comment by natuk** [comment]
New AAT concept not approved as it is a composite term. Proposal is to assign the AAT term to the material only and keep the note more generic.

**Comment by azaroth42** [comment]
https://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300138222 

--> #186 as this is just vocabulary now.
