### ISSUE TITLE
 How to describe conservation samples removed

### ISSUE THREAD

**Issue by natuk** [linked-art/linked.art#386]
I think this is only a documentation issue in that we need an example explaining how basic conservation sampling information can be shared, so that we can quickly identify where samples of a painting exist already.

**Comment by natuk** [comment]
Attaching an example of how sampling can be recorded based on the [existing example](https://linked.art/model/object/production/#production-by-removal) about the torn manuscript page being a separate thing. This is a paint sample removed from a painting.

```json
{
  "@context": "https://linked.art/ns/v1/linked-art.json", 
  "id": "https://linked.art/example/sample/1", 
  "type": "HumanMadeObject", 
  "_label": "Paint sample", 
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300028875", 
      "type": "Type", 
      "_label": "Sample"
    }
  ], 
  "removed_by": [
    {
      "type": "PartRemoval", 
      "carried_out_by": [
        {
          "type": "Person", 
          "_label": "Conservator"
        }
      ], 
      "diminished": [
        {
          "type": "HumanMadeObject", 
          "_label": "Painting", 
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300033618", 
              "type": "Type", 
              "_label": "Painting", 
              "classified_as": [
                {
                  "id": "http://vocab.getty.edu/aat/300435443", 
                  "type": "Type", 
                  "_label": "Type of Work"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by jpadfield** [comment]
In case it is useful, here is a link to an old CIDOC example for sampling, just using the core CRM though: https://jpadfield.github.io/cidoc-crm.examples/models/mermaid_sampling.html

**Comment by azaroth42** [comment]
2021-01-06: Explicitly call out conservation use case in the documentation.

**Comment by natuk** [comment]
Thank you merging at #413 . This this can close now.
