### ISSUE TITLE
Specify Content-Type for "content" property value

### ISSUE THREAD

**Issue by edwardanderson** [linked-art/linked.art#388]
Do we have a way of providing the `Content-Type` of textual data carried in the `content` property? If text is, for example HTML or Markdown, can this type be specified?

```json
{
  "type": "LinguisticObject",
  "content": "<p>This text is <strong>significant</strong></p>"
}
```

**Comment by azaroth42** [comment]
Assuming that the desired construction would be something like:

```
{
  "type": "LinguisticObject",
  "content": "<p>...</p>",
  "format": "text/html"
}
```

I think that we could use `dc:format` for the `format` property, as per its use for `DigitalObject` [here](https://linked.art/model/digital/).

**Comment by azaroth42** [comment]
#565 is dupe of this
