### ISSUE TITLE
Multiple PartRemoval events for the same entity?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#399]
Currently we allow the same entity to be removed multiple times, and thus the `removed_by` property always takes an array of `PartRemoval` events.

I think this is correct but would like validation of the (very theoretical) use case:

> An arm of a statue is found dismembered from the torso. It has thus been removed (either intentionally or not) in the past. It is then attached to a statue and displayed, until a second statue without an arm is found that is obviously the right one. The arm is thus removed again, and attached to its real owner.  Both statue and ontologist are happy.

Thus:

```
{
  "type": "HumanMadeObject",
  "_label": "Arm",
  "removed_by": [
    {
      "type": "PartRemoval",
      "_label": "Removal before discovery",
      "diminished": {
        "type": "HumanMadeObject",
        "_label": "Original statue"
        }
    },
    {
      "type": "PartRemoval",
     "_label": "Removal from incorrect statue",
      "diminished": {
        "type": "HumanMadeObject",
        "_label": "Incorrect statue"
        }
    }
  ]
}
```
And the corresponding `PartAddition` events for attaching to the wrong statue, and then to the correct one.
Yes?

Conversely, the `diminished` property is not multiple, as it's from the `PartRemoval` to the entity that the part was removed from ... and it can't be removed from multiple things at the same time. Same with the `augmented` property for `PartAddition`. Yes?

**Comment by natuk** [comment]
I am still struggling with the quantification notation on the CRM but the property seems to be many to many, which means that the range can have multiple instances of this property, i.e. many things can be diminished by the removal. The property scope note (and unlike your example) confirms that this can happen in one event: "it is possible to imagine circumstances under which more than one item might be diminished by a single instance of E80 Part Removal activity". And I imagine: the removal of a cornerstone diminishes both walls(?).
