### ISSUE TITLE
Are attached parts of objects separate in the API?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#400]
For example, in https://linked.art/model/base/#parts there is a `part` of an object embedded in the larger object.

This seems reasonable *if and only if* there is no need to reference the part separately from the parent.  This might work for things like supporting material (canvas of a painting), but not when the part is less intrinsic. Even frames of paintings, or the mounts for sculptures are changed, and thus would need separate identities. 

How about ... if it is impossible to remove the part without destroying the object, then it can be embedded within the object record without separate identity.  This allows for measurements and materials to be asserted separately, without leading to horrible inconsistency when some institutions use it for each chess piece or tea cup.

Meaning I think that the properties that the part can have are limited to:

* type - HumanMadeObject
* label - string
* identified_by - Name or Identifier
* classified_as - Type
* referred_to_by - LinguisticObject qua Statement
* member_of - Set
* dimension - Dimension
* made_of - Material 
* part - recursion
* shows - reference to a VisualItem
* carries - reference to a LinguisticObject
* representation - reference to a VisualItem

**Comment by natuk** [comment]
A couple of comments from a conservation perspective:
* it might be difficult to judge whether a part can be removed without destroying the object,
* dimensions, categories, materials etc. could of course apply to parts that cannot be removed and I can think of many cases where bringing up these parts as separate API entities in a search would be useful (e.g. give me all embossed tooling decoration marks showing a dragon).
I hope I understood the issue.

**Comment by azaroth42** [comment]
Difficult decision in 2021-03-10 call:  Always use `part_of` and never `part`, any entity that has properties should be at a  separate URI, and not referenced from the whole. This is consistent with other 'part' or 'member' relationships not being explicitly materialized, but instead inferred from the inverse.

Rejected the middle position of separate entities, but linked from both sides, as inconsistent with other patterns and the risk of introducing inconsistencies in the data, which design patterns say we should avoid.
Rejected the embedded parts as there's no way for an implementer to know when it should be allowed and when not, inconsistent with design patterns and other endpoints, and introduces multiple ways to do the same thing, thereby doubling the effort needed to consume and work with the data.

There was some reservations, so we should revisit with evidence later.

**Comment by azaroth42** [comment]
3 years later, we were correct in the hard decision. Closing.
