### ISSUE TITLE
Home page as Digital Object, not Textual Work, is inconsistent?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#406]
In working on the API documentation, an inconsistency has become apparent.

In our last discussion of digital objects (#283) we concluded that *for digital images*, it was clear that the separation of Digital Object that digitally shows the same content as a Physical Object was the best pattern, and thus all `representation` properties should point to a `VisualItem`, which can then be shown by physical and/or digital objects.

We did not discuss the same thing (as far as I recall) in the context of texts.  So ... at the moment, the "home page" of an object can be a linked via `subject_of` a Digital Object, `classified_as` a Web Page, rather than going through an intermediary `LinguisticObject` node, the equivalent of `VisualItem` for images. This is possible at all because Digital Object is a subClass of `InformationObject`. We have thus introduced an inconsistency in our patterns:

```
Object -subject_of-> DigitalObject  // meaning the *content* of the DO is about the Object
Object -representation-> VisualItem -digitally_shown_by-> DigitalObject
```

And the more consistent, and more verbose, pattern would be:

```
Object -subject_of-> LinguisticObject -digitally_carried_by-> DigitalObject
```
 
This would allow the textual content to be carried by multiple digital objects, and potentially physical objects. The pain of the verbosity is, of course, that it's very unlikely to be multiple entities that carry the same text, unless someone has printed out a copy of the home page and needs to (for some inexplicable reason) document that as a carrier of the content.

I note, also, that Digital Object is NOT a subclass of `LinguisticObject`, and thus the Digital Object description cannot have a `Language` associated with it. Meaning if there was (for example) a [Dutch home page](https://www.rijksmuseum.nl/nl/collectie/SK-C-5) and an [English home page](https://www.rijksmuseum.nl/en/collection/SK-C-5) for the Night Watch, we could not describe this distinction in a machine-processable way.

**Comment by edwardanderson** [comment]
Happy to confirm that we have exactly this use case at the Rijksmuseum.

**Comment by azaroth42** [comment]
Call of 2021-03-10: Agreement that the `language` issue is a deal-breaker, and thus we need to have the `LinguisticObject` intermediary, again with the reservation about API complexity of multiplying entities.

**Comment by azaroth42** [comment]
Done
