### ISSUE TITLE
API Displacements and/or Transclusions

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#411]
In #406 we decided (correctly, IMO) that the home page of an entity should be referenced through the Linguistic Object (e.g. Textual Work API) in order to associate language with the content, which is not available for a Digital Object directly.

Thus to get to the URI of the home page there is now 3 hops, needing two extra API calls:

```
<physical-object> subject <linguistic-object> .
<linguistic-object> digitally_carried_by <digital-object> .
<digital-object> access_point <uri> .
```

This seems very expensive, especially when the linguistic object of the home page exists only for consistency and language, and is unlikely to ever be referenced by any other entity.  In this case, I don't think the linguistic object really needs its own identity, it could be a blank node in the the main entity's graph. However, if it was a book about the entity, it definitely would need its own identity (and thus API endpoint) as there would be likely many references to it.

To me this is the straw that breaks the transclusion camel's back. In other words, I think this is so costly for such little gain, that we need to find a way to reduce the implementation cost ... and the way to do that is by allowing some entity descriptions that are normally separate to be embedded in other responses.

I would propose the following transclusions be allowed:

* <all apis> subject_of <textual_work> -- allow home page to be in the entity's record
* <textual_work> digitally_carried_by <digital_object> -- second hop of the above, or reference from text to digital carrier
* <visual_work> digitally_shown_by <digital_object> -- reference from image content to digital carrier
* <physical_object> carries <textual_work> -- object that carries a unique text and there's no need to reference the text separately
* <physical_object> shows <visual_work> -- object that carries a unique image and no need to reference image content separately

Also to discuss in the transclusion scope:

* Allow identified_by to be included in a reference to another entity to give a display name. Otherwise to render even the name of a Place (or other entity) you need to dereference it. Given that there might be a dozen referenced entities, this would get expensive in terms of time to render the page.

If we go this route, home page would be something like this:

```
{
  "id": "https://data.example.museum/object/1",
  "type": "HumanMadeObject",
  "subject_of": [
    {
      "id": "https://data.example.museum/object/1#webpage-text",
      "type": "LinguisticObject",
      "language": [ {"id": "aat:english", "type": "Language", "_label": "English"} ],
      "digitally_carried_by": [ 
        {
          "id": "https://data.example.museum/object/1#webpage-object",
          "type": "DigitalObject", 
          "access_point": "https://example.museum/collection/1"} ]
    }
  ]
}
```

**Comment by beaudet** [comment]
Is this still compatible with CRM?

**Comment by azaroth42** [comment]
Yes - we don't introduce anything new here in the graph, just how it's divided up into documents on the web :)

**Comment by azaroth42** [comment]
So I've tried it both ways with 1M archival documents. The cost is (as expected) very high for no value when they're separate. Each of the 1M documents of course becomes 3 ... where the only information in the other two is the `access_point` to the repository homepage, and there's no other references to them.

I think entities treated like this should have to have full URIs, not be blank nodes, but able to be transcluded to avoid using lots of files and network interactions just to get the URI. The benefit of consistency (always split) seems to me to be vastly outweighed by the cost in practice for using them.

**Comment by azaroth42** [comment]
#427 has implications here too - as the template entity isn't real, it probably should be embedded within the Set for which it is the template.

**Comment by azaroth42** [comment]
Discussion at call of 2021-11-17 - `members_exemplified_by` is useful for a small list of particularly representative items that do exist, that have been designated as such by some process (manual or automated). The values are then references to other entities, rather than an embedded description.

This then allows for the box full of vase shards to refer to one of the shards that has been described, or from the paintings department set to a representative painting object.

**Comment by azaroth42** [comment]
Discussion on call of 2021-12-01, resulting in concrete proposal from Rob:

Change the following two keys (changes in bold) in all API endpoints (e.g. documents/records):

* `subject_of`:  An array of json objects, each of which is *either* a reference to a Textual Work, the content of which focuses on the current entity, and MUST follow the requirements for a reference, *or an embedded textual reference to a digital resource*.
* `representation`: An array of json objects, each of which is *either* a reference to a Visual Work that represents the current Person, and MUST follow the requirements for a reference, *or an embedded visual reference to a digital resource*.

New definitions:

Embedded Textual Reference: 
 * MUST NOT have `id` (e.g. is a blank node) -- this makes it distinct from actual textual references
 * MUST have `type` with value `LinguisticObject`
 * MUST have `digitally_carried_by` with an embedded Digital Object -- as does this
 * SHOULD have `_label`
 * SHOULD have `identified_by` 
 * MAY have `classified_as` 
 * MAY have `language`

Embedded Visual Reference: 
 * MUST NOT have `id` (e.g. is a blank node)
 * MUST have `type` with value `VisualItem`
 * MUST have `digitally_shown_by` with an embedded Digital Object
 * SHOULD have `_label`
 * SHOULD have `identified_by` 
 * MAY have `classified_as` 

Embedded Digital Object:
 * MUST NOT have `id`
 * MUST have `type` with value `DigitalObject`
 * MUST have `access_point` with the URI of the resource
 * SHOULD have `_label`
 * SHOULD have `classified_as`
 * MAY have `identified_by`
 * MAY have `format`


Rationale: 
* This is unambiguous with the current structure, which allows only references that must have an `id`
* It allows pointers to images, web pages or any other online resource to be included with sufficient information as to make them understandable (e.g. via classified_as, language etc), renderable (e.g. format and access_point) and linkable in a UI (e.g. identified_by, type, classified_as), without requiring new documents to be created, published and maintained, and always needing to be dereferenced by the client
* It does not allow the full spectrum of description, to short circuit the API boundaries for the regular cases where the text / image should be able to be referenced from multiple other entities and does not conflict with these cases

**Comment by azaroth42** [comment]
Agreement to do all 5 categories with the same rules -- MUST NOT have an id if it's embedded.

**Comment by azaroth42** [comment]
Baseline in #552 but blocked by #551

**Comment by azaroth42** [comment]
Now done
