### ISSUE TITLE
Do we recommend reasonable inference to fill out the graph?

### ISSUE THREAD

**Issue by mdlincoln** [linked-art/linked.art#42]
Publishers targeting this model may want guidance on whether to fill sections of this graph via inference, in order to fill gaps left by a strict transform of their source data.

Scenario: a publisher has determined they can generally map the `type` field from their CMS to `classified_as: ...`, and the `technique` field from their CMS to `production: {technique: ...}` However, their source data are inconsistent. Many objects have `type: engraving` but were never assigned a value for `technique`. Should the publisher aim to fill out the graph by inferring `production: {technique: aat:engraving (printing process)}` if they are reasonably confident such an inference is accurate?

**Comment by mdlincoln** [comment]
re: #28

**Comment by azaroth42** [comment]
I think that publishers should be as explicit and complete as possible without totally undue repetition. Assuming that either the publication system or the client will be able to follow inferential axioms seems to be against the spirit of the "keep it simple / assume simplicity" design principle.

Thus if the publisher is sufficiently confident of their inference that engravings and produced with an engraving process (and they probably should be!) then they can add it into their data.  Per #47 they might also add the "computer generated" classification somewhere.

**Comment by mdlincoln** [comment]
I tend to agree. 

It would be useful to add relevant hyperlinks across the documentation for a data producer trying to implement this model. In the case of `types`, `production technique`, and `materials`, these sit on different pages in the documentation (and sections of the model) but will frequently be derived from a single field in a legacy CMS. Having each point to the other two would be very helpful.

**Comment by azaroth42** [comment]
@mdlincoln How do you suggest we move towards closing the issue?  Is #47 sufficient?

For the cross-links, I don't want everything to be cross-linked to everything else, but at the end of the day it is a graph.  Are there particular sections that should reference others? Or would further recipes in the cookbook section be sufficient guidance?

**Comment by azaroth42** [comment]
Closing without prejudice.
