### ISSUE TITLE
Elevation of Place

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#425]
The elevation / depth of a place may be known independently from any point or polygon. From a natural history example, a fish might be netted via a trawl that dredges at 100 feet depth ... but the location where the fish was actually caught could be anywhere along the path of the boat. Or that we know a dragonfly was caught at 3 meters of elevation, but the location is only described with a string ("1 mile west of farmer's gate"). While we can already include elevation in the WKT format (x,y,z) rather than (x,y), we might not know any x or y and only z ... which would not be a useful representation to say anywhere in the world at a z of 3 meters.

Not sure if there are artwork based use cases for this?

**Comment by ewg118** [comment]
Is there a use case for linking pigments to source materials that only exist at certain elevations? I.e., show me all paintings that include pigments from alpine regions?

**Comment by azaroth42** [comment]
07/14 call: Hard to find use cases for this. Notre Dame photogrammetry discussed, but also have lat/long. Would need x/y/z for any photogrammetry. Also need angle and distance for reconstruction of photography.  Installation art as use case ... but very specific to individual objects, not useful to share?

Proposal - close and reopen if a use case in art comes up

**Comment by atiro** [comment]
I should add for the record - https://collections.vam.ac.uk/item/O107643/view-from-the-kunzam-pass-photograph-bourne-samuel/ (but it's about 5 objects in the collection that have this patterm, so don't think could claim it's a common case)

**Comment by azaroth42** [comment]
Ahh, so you know it's 14,931 feet of elevation from the title ... but don't have any other geospatial information as to the location. Will at least put our mapping in this issue when we get to it from the natural history side.
