### ISSUE TITLE
Instances of identifier named in conformance with schema/pattern

### ISSUE THREAD

**Issue by edwardanderson** [linked-art/linked.art#428]
Thank you for the recommendations on implementing identifiers in yesterday's call (#421). I've been working on improving our own templates for identifiers and realised I am uncertain how (and where) to describe certain properties of an identifier's name.

For example, we would like to record that the identifier "SK-C-5" is the `"Object Number"@en` and `"Objectnummer"@nl` of a painting. Are these names direct properties of the instance of the identifier, or does the identifier conform to some other CRM entity (representing the underlying field in the source system) with its own names and properties?

```turtle
@prefix crm: <http://www.cidoc-crm.org/cidoc-crm/> .

<https://id.rijksmuseum.nl/2005216>
  a <http://www.cidoc-crm.org/cidoc-crm/E22_Human-Made_Object> ;
  crm:P1_is_identified_by [
    a crm:E42_Identifier ;
    crm:P1_is_identified_by [
      a crm:E33_E41_Linguistic_Appellation ;
      crm:P190_has_symbolic_content "Object Number" ;
      crm:P2_has_type <http://vocab.getty.edu/aat/300404670> ;
      crm:P72_has_language <http://vocab.getty.edu/aat/300388277>
    ], [
      a crm:E33_E41_Linguistic_Appellation ;
      crm:P190_has_symbolic_content "Objectnummer" ;
      crm:P2_has_type <http://vocab.getty.edu/aat/300404670> ;
      crm:P72_has_language <http://vocab.getty.edu/aat/300388256>
    ] ;
    crm:P190_has_symbolic_content "SK-C-5" ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300312355> ;
    crm:P37i_was_assigned_by [
      a crm:E15_Identifier_Assignment ;
      crm:P14_carried_out_by <https://id.rijksmuseum.nl/21018560> 
    ]
  ] .
``` 

With this pattern (above), it's necessary to make blank `Name` nodes for every occurrence of our "Object Number" identifier (a lot). Also, these `Name` nodes aren't really specific to the particular instance of identifier. So instead, is there a pattern where the identifier node `conforms_to` (or other) a class of identifier which is named only once (and could be further annotated)?

**Comment by edwardanderson** [comment]
Ah, maybe I simply apply an extra `P2_has_type` and mint a thesaurus term for "Object Number". Simple as that?

**Comment by azaroth42** [comment]
A Type with names seems easy, and makes it easier to be consistent by reusing that Type with all your identifiers :)

**Comment by azaroth42** [comment]
Okay to close?
