### ISSUE TITLE
event0 diagram not rendering

### ISSUE THREAD

**Issue by edwardanderson** [linked-art/linked.art#438]
The Mermaid diagram for [event0](https://linked.art/api/1.0/endpoint/event/#event_0) does not render. I've debugged, and I think the cause is unescaped double quote characters on line 65 (403 in the HTML) wrapping _A Gentleman_.

```
O6-- content --&gt;O6_3("''Besides paintings, this sale included a few lots with musical instruments and watches. The owners were a number of dealers who regularly consigned their wares to this auctioneer, despite the fact that the title page names "A Gentleman" as the owner.''")
```

[Reference to line in crom code](https://github.com/linked-art/linked.art/blame/master/docs/api/1.0/endpoint/event/index.md#L102).

**Comment by jpadfield** [comment]
Yes it seems to work if the double quotes are replaced with single ones: [Example](https://research.ng-london.org.uk/modelling/?data=eJydVU1T4zAMPZcZ%2FoNPywWaBPoFt7LLMjvDx87Qe0d11MTg2llbaem%2FXyVOYVPawuwlrSJZ7%2BnJUia58uLepqg7OXghrSF8pU5OVPirKNLKvGDaBUeR8dEyaV6c8Yvus7fm%2BEgDXuESDUVxh9YFdsaS1FLRuu2aapgxxk%2FrCZ0YlxxkjbBzcQ9O5iIZncftA1KD92quMJ2C7wDQ1UUcx%2F3esJ8cH7XMADvhx7ajAd2g3VSp2ygq5d%2BAMlt3ptcPx0f8CBkfYIHBrFUx1LlJV%2BBS8fUiDqX%2FtfG5BmRXwb24Nzh%2FLziYOwpuHE3BjyuD7mzM6TKDqXgoF7M3lKaUa5dcxqM2W4dzdI7xyX6ke6dMVipPSj7OnlHSIdIX%2FV4yeOdWm7tIB0dD%2Bgd66VRRSbodsRslGcW9y%2FfQ2tyFEhwNyrVTOBcTvuNbeqDnZnlRgOKumMyfCqpGw4NGoYzUZcpKgpjjSmhLXqwU5WJReiVBc4AnVy44kRdgUrECkjn6rpjkKGzVDT6ADjmBqZtRXZoUOXflyK1wmJUanF5XE9i0jXJUjlM5pkU20IFw5xDdKZ%2F3hSKs4sQcJPEfoNoiRcy6gAyF4UvsxclY3DI5jQswJ4LnnDa8ulsTrDi8ABOav9%2Fzz7Ub7BQ9ODatVb7QsBaTitf%2FAbY81r5MOaHEKYRVxZtqaSXMuhkSrbuYlhFlJhrGSTIc8fh8HhNq%2BF0l%2FVJ4U9mdNen2FpTgXHVVbUnVGO1Jxu02UZ%2BV6ifDQX8vZjsssLx1tiy%2BeqIh2l5d38TTNuvSM2VfoOQ5k1Nbz%2FiGO77CotDYtS6LPJKPNtvjsD%2BwfUL6NHCzqLV%2B26p31ZDxlOxaVPinVEseHvOBYTMfUQGeonldbFSt5Si%2BiJIPNA5GH%2Fqa%2BbLWZ2rnuySSQKBtdkildsi%2BDfv5wUa4JxbDi%2B%2FBF1Q7C9h%2FAQBejx0%3D)

**Comment by azaroth42** [comment]
Fixed with upgrade to newer mermaid
