### ISSUE TITLE
Allow equivalent in extended type definition in API

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#439]
So that aat:painting can be equivalent to lcsh:painting and wikidata:painting.

**Comment by azaroth42** [comment]
2021-09-22: Agreement to add to reference to a type, and full description of a type. Additionally, make type a bona fide top level entity for transparency, rather than having it as an option in the shared constructs docs.

**Comment by beaudet** [comment]
I think you were covering the specifics when I joined late to today's call, but if you have some examples of before / after that you could put into this issue, that would be helpful.

**Comment by beaudet** [comment]
We have these stored in TMS as alternative identifiers which is fine, but would you expect to find a wikidata ID in both the equivalent IDs as well as under identified_by or only in equivalent?

**Comment by azaroth42** [comment]
I think the equivalent link is more useful -- the Identifier would just be a string, and you'd want to use the AttributeAssignment method to say where it came from.  It wouldn't be wrong ... but I don't think it would help.

In a new dataset in LUX we've implemented this issue (add equivalent to references) and it was both easy and helps a lot for processing

**Comment by azaroth42** [comment]
Done
