### ISSUE TITLE
Turtle (styled) links no longer functioning properly

### ISSUE THREAD

**Issue by eecanning** [linked-art/linked.art#451]
The Turtle (styled) representation links on the Linked Art site are now all going directly to [https://cdn.jsdelivr.net/gh/niklasl/ldtr@v0.2.2/demo/](https://cdn.jsdelivr.net/gh/niklasl/ldtr@v0.2.2/demo/) instead of the representation of the data.

**Comment by azaroth42** [comment]
Fixed
