### ISSUE TITLE
Question: modelling uncertain and/or multiple attributions?

### ISSUE THREAD

**Issue by sdevalk** [linked-art/linked.art#454]
Hi all,

(Rob, if you're the one reading this - sorry to bother you once more :))

I'm modelling a dataset about Dutch artworks with Linked Art. Quite a number of these artworks have rather complex attributions: we don't know exactly who has made these. Some examples from our dataset:

1. Painting X was made, according to curator B, by the workshop of artist C or, according to curator D, in the style of C. There is an 'or' relation in these attributions.
2. Painting Y was made, according to curator B, by artist C and, according to the same curator, by the workshop of C (e.g. the artwork was initially created by C, but - after his death - finished by unknown artists in his workshop). There is an 'and' relation in these attributions.
3. Painting Z was made, according to curator B, by artist C and, according to the same curator, by the workshop of C or, according to curator D, in the manner of C. There is an 'and' and an 'or' relation in these attributions.

I can use (a combination of) the patterns '"Style Of" Attribution' [1],  'Attribution of a Group' [2], 'Multiple Artists' [3] and 'Uncertain or Changing Attributions' [4]. But I was wondering: is there a preferred/recommended approach for describing uncertain and/or multiple attributions?

Thank you.

[1] https://linked.art/model/assertion/#style-of-attribution
[2] https://linked.art/model/object/production/#attribution-of-a-group
[3] https://linked.art/model/object/production/#multiple-artists
[4] https://linked.art/model/object/production/#uncertain-or-changing-attributions

**Comment by azaroth42** [comment]
For these sorts of things, we normally throw our hands up in the air and put them into a human-oriented note's text.  The ands and ors especially quickly become completely impossible to manage in a structured way. My rule of thumb is:  If you want it to be indexed, make it structured data even if the semantics aren't exactly correct. If you want it just to be read by a human, and not indexed, make it a note. e.g. if painting X should be indexed as produced by artist C (somehow) then C needs to be listed in a Production (e.g. following those examples you list)... but if you just want a reader to see the name C and let her figure out the relationship, then a note is more effective.

Not yet documented in the website, mea culpa, but there's also issue #229 which describes more details about attributions.

**Comment by sdevalk** [comment]
Hi Rob,

A crystal clear answer - thank you very much for sharing your thoughts!
