### ISSUE TITLE
Determine what should be returned from API named query URIs

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#456]
For example, per #412 and #455, we have a URI `https://linked.art/api/1.0/rels/produced` ... what should be returned by the web server when a client dereferences that URI?

Similarly, what happens when `https://linked.art/api/1.0/rels/` is dereferenced?

**Comment by beaudet** [comment]
I think it depends on whether the API is extended RESTfully from the base URI of a top-level entity or whether access to the API is served through an entirely different URI than the data response.  Let's use any HMO LA URI pattern, say... https://linked.art/example/object/54.json  What should the response be for just https://linked.art/example/object ?   Is it a 404 or should it respond (with pagination hopefully) through all known HMOs in the graph?  Is this the same URI

**Comment by azaroth42** [comment]
Reading the spec in more detail:
>  Custom link relation types (Extension Relation Types in [RFC5988])
>   SHOULD be URIs that when dereferenced in a web browser provide
>   relevant documentation, in the form of an HTML page, about the
>   meaning and/or behaviour of the target Resource.

So we should have a page for each such named query with HTML docs. We could also content negotiate for something more machine readable.

So dereferencing linked.art/api/1.0/rels/produced should result in a web page that describes the meaning of "produced"

**Comment by beaudet** [comment]
Yep, or both a description and an enumeration of entities? Or an enumeration and a link to documentation? What's the difference in the intended functionality of the two hypothetical endpoints /API/1.0/... and /object/12345/...  ?

**Comment by azaroth42** [comment]
2021-12-20: @azaroth42 and @beaudet did some exploration of the docs and implementations and came to:

* The curie is to give a URI for the relationship, that when resolved, returns HTML documentation. E.g. "la": "https://linked.art/api/1.0/rels/{rel}" plus a key of "la:subjectOf" resolves to   "https://linked.art/api/1.0/rels/subjectOf" as the relationship definition URI. Going to that linked art URL would get the HTML docs page, which should include (in our case) HTML definition, plus any SPARQL / GraphQL or similar ways to define/implement it
* The href that would be the value of "la:subjectOf" is essentially the object of a triple, where the subject is "self" and the predicate is the rel as above.  e.g. "http://example.museum/obj/1" "https://linked.art/api/1.0/rels/subjectOf" "http://example.museum/obj/1/MySubjectList" ... and from there you get the list of texts that the current object is `about` (or whatever the definition of subjectOf is)

There's no need for the rel to be in the target URI.
For ease it should probably be absolute, rather than relying on implementations to know how to concatenate.
It shouldn't have parameters, so likely the current entity's identifier will be in the URL somewhere (as above, it just appends /MySubjectList to the end of the json record URI)

This can also be boilerplate for database level APIs, such as text search, SPARQL, GraphQL or whatever comes next.

So:
```
"_links": {
  "curies": [
  {
    "name": "la",
    "href": "https://linked.art/api/1.0/rels/{rel}",
    "templated": true
  }],
  "self": {
    "href": "https://lux-front-dev.collections.yale.edu/data/person/ea7418ad-0feb-4f72-b7cd-4e723d26eaad"
  },
  "la:depictingObject": {
    "href": "https://lux-front-dev.collections.yale.edu/data/person/ea7418ad-0feb-4f72-b7cd-4e723d26eaad/common:depictingObject"
  },
  "la:sparql_api: {
    "href": "https://lux-bacl-dev.collections.yale.edu/api/sparql"
  },
  "la:search_api: {
    "href": "https://lux-back-dev.collections.yale.edu/api/search?q={queryString}",
    "templated": true
}
```

**Comment by azaroth42** [comment]
Human readable text as expected. Good to go.

**Comment by azaroth42** [comment]
Closing -- we determined it was human readable text. Still need to /write/ said readable text but that's #455
