### ISSUE TITLE
Context specific assertions use API-unfriendly pattern

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#458]
The example for context specific assertions (https://linked.art/model/assertion/#context-specific-assertions) is an okay model... but impossible in the API. It would mean that the exhibition activity would need to manage all of the AttributeAssignments for entities that were part of the exhibition. That breaks our child-to-parent API principle.  And going from child to parent would mean there was hundreds of little parts of the exhibition, that weren't venues or whatever, but just namings.

Propose to change the model to something that fits more neatly within the confines of the API.

In particular, as per the first example in the page, put the AA on the Object, and then have it `motivated_by` the Exhibition.  Then the name is with the object and we're extending the base pattern, rather than creating a new one.

**Comment by edwardanderson** [comment]
Could many assignments be made as part of a single activity? For example, a bunch of objects were given new names in an exhibition? Could this naming event be retrievable from the Events endpoint?

```turtle
# Exhibition.
<https://linked.art/example/activity/0> a crm:E7_Activity ;
  crm:P2_has_type <http://vocab.getty.edu/aat/300054766> .

# Bulk naming activity.
<https://linked.art/example/activity/99> a crm:E13_Attribute_Assignment ;
  crm:P9i_forms_part_of <https://linked.art/example/activity/0> ;
  crm:P9_consists_of [
    a crm:E13_Attribute_Assignment
  ] , [
    a crm:E13_Attribute_Assignment
  ] , [
    a crm:E13_Attribute_Assignment
  ] .
```

**Comment by azaroth42** [comment]
Must be allowed in both records, as any dataset might have only one or the other not both.  If a single dataset has both, then the preference is to put it in the object record (but recommended not must)

**Comment by azaroth42** [comment]
Per #551, cross-institution links aren't in directly scope for 1.0 (e.g. exhibitions have this issue in spades) so new model works with the API as expected.
