### ISSUE TITLE
clarification on difference between "broader" and "member_of" for terms and "part_of" w.r.t. Getty's LA AAT service

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#460]
The external vocabulary recommendations at https://linked.art/api/1.0/shared/type/ suggest inclusion of "broader" as well as "member_of". 

```
Property Name | Datatype | Requirement | Description

identified_by | array | Recommended | An array of json objects, each of which is either a name of the Type and MUST follow the requirements for Name, or an identifier for the Type and MUST follow the requirements for Identifier

referred_to_by | array | Optional | An array of json objects, each of which is a human readable statement about the Type and MUST follow the requirements for Statement

broader | array | Optional | An array of json objects, each of which is a Type that the current Type is narrower than and MUST follow the requirements for an entity reference to a Type

member_of | array | Optional | An array of json objects, each of which is a Set that the current Type is a member of and MUST follow the requirements for an entity reference to a Set

```

What is the semantic difference between these two properties?

Given these recommendations, should I expect the Getty's Linked Art data service running at data.getty.edu/vocab/aat to include the broader property for determining whether a given term belongs to a broader, more general, concept?  For example, determining that the color green belongs to the broader concept of color?  The Getty's service does not seem to include broader or member_of but rather "part_of" in its response.  I can work with that logically speaking, but it would help to know the semantic meaning first.  Wouldn't it be best for the AAT service to align with the LA recommendations for external terms?

**Comment by beaudet** [comment]
For SHACL validation purposes, I've ignored this Getty LA service and written a program that exports the AAT using a construct query that produces a list of all AAT terms along with their 'broaderExtended' property.  That allows SHACL validation to test whether a term is considered to reside below a particular concept in AAT.  I think this is all we need for SHACL, but I might be missing something.

**Comment by beaudet** [comment]
As per call on 1/12/2022, Rob to promote https://linked.art/api/1.0/shared/type/ as its own "API endpoint" as opposed to a shared structure.  I will adjust the construct query above to produce the properties according to the URL above rather than using broaderExtended.  member_of should be used to refer to "blessed sets" whereas "broader" will be used as a substitute for broaderExtended.

**Comment by beaudet** [comment]
Related to this, how to create local memberships to supplement the validator, e.g. local directory that has only a local installation's terms.

**Comment by azaroth42** [comment]
Broader vs Member_of:

* Broader is a reference to a Concept that is broader in scope than the current one. `attic-black-figure-vases broader vases`
* Member of is a reference to a Set that this concept is part of. The set could be for any purpose and might include non-concepts. So the type of attic-black-figure-vases could be in a set along with HMOs that are those vases, or with the concept for the color black, or anything else.

**Comment by azaroth42** [comment]
Re Getty -- it's using a previous version where we tried to put them together under `part_of` but subsequently split it back out
