### ISSUE TITLE
additional clarification needed for use of concepts with predicates that use them such as identified_by, classified_as

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#463]
Are specific concepts in AAT recommended when using the identified_by and classified_as predicates? Do these vary based on the entity being identified?  For example, should AAT's primary name always be recommended for Actors (Person/Group) but not necessarily for a blank node like dimensions where it is recommended but the examples currently use "display title" rather than primary name.  In the case of art objects, for example, I think it makes total sense to check the concepts used in classifying an art object to ensure "Artwork" is assigned to top level objects and to also ensure the "type of work" is selected from below a particular branch of the AAT.

Similar question for typing of other shared concepts such as AttributeAssignment.  

In the interest of compatibility, it seems prudent to push these type concepts as deeply into the model as possible but to strike a balance between flexibility and standards.   Put slightly differently, these approaches are shared across entities, but should the validation of data be handled "generically" for these structures or should it also take into account the context in which the concepts are being used?  I would argue for the later and in that case, it would be helpful if the API could list these constraints together with the contexts in which they can appear, e.g.

Entity                        Predicate                      Recommended Concept                                   Note:
Art Object                classified_as                  Artwork (aat:30000000000)                               required for art objects with no parent
Dimension               identified_as                  Display Title (aat:300000000)                           

etc., etc.

**Comment by azaroth42** [comment]
I think this will be solved by #186?

**Comment by azaroth42** [comment]
Indeed solved by #186. Closing.
