### ISSUE TITLE
Fix model documentation for digital integration to add linguistic object

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#464]
Some of the examples show the use of a digital object as the object of the subject_of predicate for art objects.  The API indicates that textual works are the only permitted class.

`An array of json objects, each of which is a reference to a Textual Work, the content of which focuses on the current object, and MUST follow the requirements for an reference
`

Should the API be revised to permit digital objects as the object of 'subject_of'?

**Comment by beaudet** [comment]
As per prior discussion, subject_of should always point to a linguistic object to differentiate between different languages and not directly to a digital object.   Also comes up with IIIF v2 and v3 manifests where we wanted to say "this is the set of manifests" you choose which to use.

**Comment by azaroth42** [comment]
Model docs are out of date. We should always have an intervening LinguisticObject or VisualItem.

**Comment by azaroth42** [comment]
Fixed in model docs
