### ISSUE TITLE
Question: `AttributeAssignments` and `produced_by`?

### ISSUE THREAD

**Issue by sdevalk** [linked-art/linked.art#469]
Hi all,

A question about the use of `AttributeAssignment`s and `produced_by`:

1. The ['Style of' attribution example](https://linked.art/model/assertion/#style-of-attribution) has an `assigned_by` to make clear that an artwork was produced "in the style of" a known artist. It uses an `assigned_property` = `produced_by`.

2. The ['Uncertain or changing attribution' example](https://linked.art/model/object/production/#uncertain-or-changing-attributions) has a `produced_by` and a nested `assigned_by` to make clear that it was previously thought that an artwork was produced by some artist. It uses an `assigned_property` = `part_of`.

I don't fully understand why the first example doesn't have a `produced_by` property and the second example does. Both examples, I think, aim to make something clear about the producer of an artwork, but use a different approach for modelling the `AttributeAssignment`. Would it be possible to explain this in the documentation?

Thank you!

**Comment by azaroth42** [comment]
These docs haven't been looked at for a while, and could benefit from it, thanks!

The first one is overly vague. It could just be an influence on a real Production, without a carried_out_by.  The attribute assignment is unnecessary here. I think it should just go into the docs for production.

The second could be `produced_by` so long as there isn't a role or other information being asserted. E.g. if you wanted to assert that X was the artist and Y was the designer, then you'd need the role pattern. So this example uses that pattern ... even though it doesn't have to.

Both could do with further clarity.

**Comment by sdevalk** [comment]
Hi @azaroth42 Thank you for the clarification!

I see you've added the label `docs-needed` to the issue, so I probably shouldn't close it. But feel free to do so.

**Comment by azaroth42** [comment]
Docs have been updated :)
