### ISSUE TITLE
Question: modeling rejected and uncertain depictions?

### ISSUE THREAD

**Issue by sdevalk** [linked-art/linked.art#474]
Hi all,

I'm modeling a dataset with metadata of artworks. The dataset contains references to the people depicted on these artworks, the sitters. I can use the ['Depiction' pattern](https://linked.art/model/object/aboutness/#depiction) for this, using the `shows` and `represents` properties.

I also want to add some statements about these depictions:

1. Some depictions aren't valid anymore. For example: we previously thought that person A was portrayed, but we've now rejected this (but it's still useful to know this). Is there a way to express this status (e.g. 'active' or 'rejected')?

2. Some depictions are uncertain. For example: we think that person A is portrayed, but we're not sure. Is there a way to express a level of certainty (e.g. 'possibly' or 'likely')?

Is modeling validity and certainty of depictions in scope of Linked Art? If so, do you have a modeling recommendation?

For example: would it be possible for depictions to follow the approach of ['Uncertain or Changing Attributions'](https://linked.art/model/object/production/#uncertain-or-changing-attributions) or to use [qualifiers](https://github.com/linked-art/linked.art/issues/229#issuecomment-999840471), by using attribute assignments?

Thanks!

**Comment by JamieBlu** [comment]
This could be handled with an external approach such as RDF Conjectures.
  I'd be pleased to tell you, or anyone, more details.

   With best wishes,
--
Jamie Blustein, PhD
Assoc. Prof. of Computer Science & Information Management at Dalhousie Univ. (in Canada)
  (Dalhousie University is in Mi'kma'ki, on the ancestral and unceded territory of the Mi'kmaq Nation.)
Director of HAIKU research group ▻ https://haiku.cs.dal.ca/
Dalhousie University Senate Vice-Chair (Academic Programmes)
On the WWW at https://www.cs.dal.ca/~jamie/
Pronouns:  I do not use gendered pronouns to refer to myself

Please note that this address uses servers hosted outside of Canada.

#BlackLivesMatter

P.S.: I sincerely apologize if my message seems curt.  I'm receiving too many messages to deal with each one as I used to.  If you require more information about the specific content of my message please speak with me in-person.  For transactional messages I recommend an article in the Harvard Business Review at <URL:https://hbr.org/2016/11/how-to-write-email-with-military-precision>.


On Mon 31 Jan 2022 at 06:41 -04:00, Sjors de Valk ***@***.***> wrote :

**Comment by sdevalk** [comment]
Hi Jamie,

Thank you - that sounds interesting! If you could tell something about your approach (and perhaps point me to some RDF to look at :)) - most welcome!

I'm especially interested in the integration with Linked Art and hoping to find a 'common practice' for modeling uncertainty and conjectures.

**Comment by azaroth42** [comment]
I would use the Uncertain/Changing Attributions pattern, but with `represents` instead of `produced_by` (or `part_of`).

Similar to #469 that documentation needs work!

**Comment by sdevalk** [comment]
Hi @JamieBlu Thank you! I think your attachments got lost in the GitHub issue. If you have the time to share them again (e.g. by attaching them to the issue or by posting a download link), most welcome!

**Comment by sdevalk** [comment]
Hi @azaroth42 Thanks for your suggestion - that makes sense! Something along these lines (some details omitted for brevity)?

```json
{
  "type": "HumanMadeObject",
  "_label": "Painting",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting"
    }
  ],
  "shows": [
    {
      "type": "VisualItem",
      "assigned_by": [
        {
          "type": "AttributeAssignment",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300404908",
              "type": "Type",
              "_label": "Obsolete"
            },
            {
              "id": "http://vocab.getty.edu/aat/300435722", // Could also be 'Probably' (http://vocab.getty.edu/aat/300435721)
              "type": "Type",
              "_label": "Possibly"
            }
          ],
          "assigned": [
            {
              "type": "VisualItem",
              "represents": [
                {
                  "type": "Person",
                  "_label": "S. Sitter"
                }
              ]
            }
          ],
          "assigned_property": "represents"
        }
      ]
    }
  ]
}
```

This example aims to express that we previously thought that person 'S. Sitter' was possibly depicted on artwork 'Painting', but that is no longer held to be correct.

**Comment by azaroth42** [comment]
docs updated with possibly by as the example. #186 for the vocabulary management.
