### ISSUE TITLE
Simplify context document?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#48]
Should there be two context documents, the first gives all of the classes and relationships that are actively used and known to be useful, even if not currently used.  The second then gives the rest of the CRM classes/relationships for compatibility with non linked-art modeled data.

This would keep compatibility (as much as one can hope for, given CRM) while still encouraging the use of the profile and making the context easier to understand and use.

**Comment by azaroth42** [comment]
Thoughts on this, @workergnome? Others?

**Comment by workergnome** [comment]
I say no.  Nothing will break if there isn't a context for those classes (the JSON will just be ugly), and I don't know if we want to be responsible for maintaining something that we're not using.

**Comment by azaroth42** [comment]
To clarify ... are you in favor of having _only_ the classes and properties that we use in the context, and no others?  e.g. if we don't use Image (for example), then linked.art does not have a context entry for it?

If so, I'm not sure I'd go that far. If an institution is otherwise compatible but can't buy into the VisualItem vs Image analysis, or has some other CRM pattern that we just haven't discussed yet, they might instead just avoid the entire thing to everyone's detriment. 

I agree that if the generation of the JSON is done via framing and compaction with the context, that it will generate ugly-but-valid JSON-LD ("crm:Image") ... but if it's built just as JSON, and the assumption is that "Image" will be okay because that's how everything else is written, then it would break.

There seems to be three choices:
1.  Status Quo: everything in a single context
2.  Split: Two contexts, one for stuff we use, one for stuff we don't
3.  Single: One context, only with stuff we use

I'm not in favor of single, I'm /shrug on 1 or 2. It's not like many people actually look at the context document directly, and although long, it's relatively readable... so my vague preference is Status Quo (despite asking the question!)

**Comment by workergnome** [comment]
I prefer Single, and am /shrug on 2, mostly because it's work that I don't want to take on—I've watched the Erlangen group try and keep up (mostly unsuccessfully) with the changes to CIDOC, and I'd rather not tie the accuracy of our work to CIDOC's—particularly for things that we're not using and might be unlikely to notice changes to.

I'm against 1:  I think that if we're proposing a cut-down version of CIDOC for utility, it's confusing to people that things that we don't recommend work, and I think that having terms not compact would be a good indicator that they're outside of our suggestions.  Having a fallback mechanism for people who are knowingly working outside our world would be nice, I suppose, but I like the strictness.

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-9b31059b981747e1bfc3fcccdfc820fe/page-1)

**Comment by azaroth42** [comment]
Resolution is to have two contexts, the one that we "guarantee" as part of the specification and one that we provide as a convenience to the community that uses the same rules applied to the rest of CRM.  The second document will be noted that if it doesn't work as expected to please raise an issue so it can be fixed, but we won't necessarily keep it complete or up to date.

Main context:  `https://linked.art/ns/v1/linked-art.json`
Secondary: `https://linked.art/ns/v1/cidoc-extension.json`

**Comment by azaroth42** [comment]
Implications on #27.

**Comment by azaroth42** [comment]
.json vs .jsonld ... @azaroth will check with @iherman and @gkellogg whether .jsonld is actually recommended or just a side effect of the registration with IANA.

**Comment by azaroth42** [comment]
@gkellogg says:
> But really, it's your choice. JSON-LD is valid JSON, so it's reasonable to treat it that way and just use a .json extension.  

I think @workergnome said it best that .json seems more developer-focused and .jsonld seems more LOD-focused. As such, I think _our_ intent is to emphasize the developer and we use .json

**Comment by azaroth42** [comment]
https://new-context--linked-art.netlify.com/model/jsonld/

**Comment by azaroth42** [comment]
Done.
