### ISSUE TITLE
current_or_former or former_or_current

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#488]
We don't currently use `former_or_current_owner` but it seems like it would be valuable to, in the JSON LD context, make it more regular to follow the typical pattern of `current_or_former_*`

**Comment by bluebinary** [comment]
If this property is not currently in use, it seems like the ideal time to revise the naming to match the pre-existing convention, such as that used in `current_or_former_curator` and `current_or_former_member`. I like the symmetry in the names when they follow a pre-existing convention, and I think it can make them easier to follow as there doesn't seem to be any semantic difference whether "former" or "current" appear first or last in the property names.

On a related note, would it be worth considering revising the naming of `former_or_current_keeper` and `former_or_current_location` to match as well, or are either or both of these known to already be in use and thus have to remain as-is?

**Comment by azaroth42** [comment]
The properties in question are:

* P49 has former or current keeper
* P51 has former or current owner
* P53 has former or current location
* P74 has current or former residence
* P107 has current or former member
* P109 has current or former curator

So it's actually evenly distributed :( Propose that we just leave it alone given that we don't use them in linked art anyway.

**Comment by azaroth42** [comment]
Closing won't fix ... We don't use them, so no need to get tangled up.
