### ISSUE TITLE
Payment Class could have a payment 'for' property

### ISSUE THREAD

**Issue by Habennin** [linked-art/linked.art#489]
Payment class supports documenting payment of amount from someone to someone but does not allow the explicit documentation of the thing paid for. Should it? Could it?

**Comment by azaroth42** [comment]
I don't think it should. The pattern we have so far is to use a parent activity and have the payment as a `part` of it along with whatever else was happening. Which allows for multiple payments, multiple objects, paying for non-things (e.g. services), and so on. Also exchanges rather than payments of money.  So I'm :-1: on adding such a relationship

**Comment by Habennin** [comment]
but a class doesn't exist by itself. Would that mean that E8 or E10 should not have objects of transfer of custody or ownership

**Comment by Habennin** [comment]
so there is a lack of consistency with those other classes (but the thing talked about seems parallel).

The payment can be for different things. 900 for the painting. 100 for the frame. How do we capture that?

**Comment by azaroth42** [comment]
I think it's more parts to group them together. Transfer of ownership could be for different things too ... I'll give you this sculpture for that sculpture and that frame, and this $100 for that miniature, and this $500 on top for services rendered and so on. The benefit of partitioning by activity is that we don't have to then also add `for` to all of the other activities which might be part of an exchange. 

- overall
   - painting
     - ownership: painting (a to b)
     - payment: 900 (b to a)
   - frame
     - ownership: frame (a to b)
     - payment: 100 (b to a)

**Comment by azaroth42** [comment]
Closing won't fix. We don't want payment to conflict with the other provenance data structures. It's the financial equivalent of Acquisition -- the transfer of a monetary amount from agent a to agent b. That might be for some thing, or it might be a gift, or it could be for some service rendered, or etc.
