### ISSUE TITLE
Overpainting / Restoration - HMO carries multiple VIs over time

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#490]
See:
https://en.wikipedia.org/wiki/Girl_Reading_a_Letter_at_an_Open_Window

There are two different visual items that the physical painting shows at different times. 
Vermeer painted the original with the background cupid, then it was overpainted, and now it has been restored. This isn't an infrequent scenario, of course.

The HMO is clearly the same object. One VI clearly depicts cupid, and the other does not.

Without a `Phase` or similar pattern, I'm not sure that we can represent this?

**Comment by natuk** [comment]
Rushing to respond here given the luring title: I think the visual item does not depend on the observation parameters. I.e. under UV or IR light you can see the underlying layer of paint and you can see cupid. So the visual item exists even if it is not visible under normal light. On the other hand, when the image of cupid was removed by a conservator, for our purposes the thing has been destroyed and a new identity is required. The new thing does not carry the visual item. Does this make sense?

**Comment by azaroth42** [comment]
Interesting, I see your point ... the HMO physically carries that image, but you can't see it due to the over painting.  Is there an issue with the scope note of P65, that it says "shown by" (it no longer does) and that it's not a "visual representation" any more as you can't see it visually? 

So in the example, it always P128 carries the version of the image with the cupid (even when you can't see it, and debatable if it shows it). Then the overpainting adds a new VisualItem (without the cupid) ... but as intellectual things can't be destroyed, don't we still have a problem when the overpainted material is removed? How does the HMO sometimes carry the overpainted VI for only a limited amount of time?

**Comment by natuk** [comment]
Thinking outloud:

> Interesting, I see your point ... the HMO physically carries that image, but you can't see it due to the over painting. Is there an issue with the scope note of P65, that it says "shown by" (it no longer does) and that it's not a "visual representation" any more as you can't see it visually?

I think that the terminology works if you consider observations outside visible light. I think the property is more about associating the two things, rather than what can be seen. I.e. you would want someone interested in cupids to find this painting even if the cupid is overpainted.

> So in the example, it always P128 carries the version of the image with the cupid (even when you can't see it, and debatable if it shows it). Then the overpainting adds a new VisualItem (without the cupid) ... but as intellectual things can't be destroyed, don't we still have a problem when the overpainted material is removed? How does the HMO sometimes carry the overpainted VI for only a limited amount of time?

The conservation event is a transformation which significantly changes the HMO. The old identity is gone and a new one is created. The old identity hold the Visual Item with cupid and the new a different Visual Item without cupid. If we accept that the painting has not changed identities, then we need to talk about parts: The HMO (or rather the feature of HMO) with the cupid has a separate identity to the painting. When the feature is removed, the feature is destroyed. So the feature always carries the Visual Item of cupid.

**Comment by azaroth42** [comment]
I think the danger of the transformation is that the object gets treated as two completely different objects in search/discovery systems, when really only one object exists at any given time. Otherwise reframing or rebinding would seem like a transformation, and we end up in the ship-of-theseus problem. 

Parts, on the other hand, seem like a very useful pattern.

T1 - Painting shows image-with-cupid
T2 - PartAddition of a HMO (the overpainting material) that shows image-without-cupid
T3 -  PartRemoval of that HMO, thereby leaving only image-with-cupid 

The painting always shows image-with-cupid (as desired) and between T2 and T3, it also shows image-without-cupid due to the new part. Times T2 and T3 are recorded due to the PartAddition/PartRemoval activities.

**Comment by natuk** [comment]
Yes, I think this is correct, with one clarification for T2: the part added cannot show the whole image, it can only show the image of the overpainting which is the empty wall/background. Another concern also is that T3 is not Part Removal as the paint layer loses its identity, i.e. it cannot be tracked after that event (although conservators do magic which allows transferring paint layers from one substrate to another but that is a different case). In my view it is a destruction of the part.

Also, the same would have to apply if we had cupid removed. I.e. I think we would need to consider it as a feature which was destroyed.

**Comment by azaroth42** [comment]
Propose defer, lacking data in systems

**Comment by azaroth42** [comment]
Closing and when there's real data we can reopen.
