### ISSUE TITLE
la:accesspoint missing from Linked.art serialization?

### ISSUE THREAD

**Issue by Habennin** [linked-art/linked.art#494]
I don't know if this is a feature or a bug but there is this documented pattern:

https://linked.art/model/digital/#other-pages

and it mentions the property la:accesspoint

however I don't find it in the present serialization file. 

https://linked.art/model/profile/ontologies/linkedart.xml

Is that on purpose?

**Comment by Habennin** [comment]
or is this pattern superceded by:
https://github.com/linked-art/linked.art/issues/411

**Comment by azaroth42** [comment]
The ontology is now here:
   https://linked.art/ns/terms/index.xml 
and has access_point in it.

Closing, fixed.
