### ISSUE TITLE
Question: type for exhibition sets?

### ISSUE THREAD

**Issue by sdevalk** [linked-art/linked.art#499]
Hi all,

I'm modeling a dataset with exhibitions. The Linked Art [pattern for exhibitions](https://linked.art/model/exhibition/#objects) recommends to use a `Set` to make clear what the exhibited objects are:

(Details omitted for brevity)
```json
{
  "id": "https://linked.art/example/activity/2",
  "type": "Activity",
  "used_specific_object": [
    {
      "type": "Set",
      "member": [...]
    }
  ]
}
```

The `Set` does not have a `classified_as` property. But the sets used for [auctions](https://linked.art/model/provenance/auctions/#set-of-objects) and [collections](https://linked.art/model/collection/#sets) do (http://vocab.getty.edu/aat/300411307 and http://vocab.getty.edu/aat/300025976, respectively).

Is it useful to have a type for the exhibition set, to be able to distinguish it from other sets? If so, what AAT term would be appropriate?

Thank you!

**Comment by azaroth42** [comment]
Yes, good question. It should have a classification ... but what is indeed the question. I don't think there'll be an AAT entry, as it's not the exhibition activity, the exhibition concept, nor the exhibition catalog, but a construct to group the included objects and works together as a coherent whole.

**Comment by azaroth42** [comment]
Discussed at face to face -- we'll use aat Topical Collection for now (300378926) but request a more specific term be created for exhibition collection (separate from "checklist")
