### ISSUE TITLE
change file extension for RDF/XML ontologies from .xml to .rdf 

### ISSUE THREAD

**Issue by axrdo** [linked-art/linked.art#500]
Mentioned in https://linked-art.slack.com/archives/C50AS8E68/p1667333812301459

Relevant standard is  https://datatracker.ietf.org/doc/html/rfc3870

Modifications wanted to these files: 
- https://github.com/linked-art/linked.art/blob/master/docs/model/profile/index.md
- https://github.com/linked-art/linked.art/blob/master/docs/model/profile/ontologies/cidoc.xml
- https://github.com/linked-art/linked.art/blob/master/docs/model/profile/ontologies/cidoc6.xml
- https://github.com/linked-art/linked.art/blob/master/docs/model/profile/ontologies/linkedart_crm_enhancements.xml

**Comment by azaroth42** [comment]
Hi Rhys! Good to hear from you :)

Interesting. I hadn't realized that .rdf was officially registered in the media type registry. Let me do some tests with some vanilla applications and see if they continue to work. Thanks for the issue!

**Comment by axrdo** [comment]
Hi Rob :)
We've been using Triply https://triply.cc/ successfully since November 2022.
The issue came up trying to import a new graph using the urls from https://linked.art/model/profile/ eg https://linked.art/model/profile/ontologies/linkedart.xml
Cheers Rhys
