### ISSUE TITLE
Versioning of Model and API

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#508]
* Version of API
* Version of Model
* Local versioning information (e.g. lux extensions version 1.1)

To be able to know how to process the semantics and the api.

Put into `_links` under the la namespace.

* la:model_version
* la:api_version
* la:local_version

href points to the documentation for the version.

Each has all of _major, _minor and _patch as integer values.

Aggregators need to have their own local_version, not just maintain the individual sources.

**Comment by azaroth42** [comment]
The proposal from May would result in (a):

```
{
 "_links": {
   "la:modelVersion": {"href": "https://linked.art/model/1.0/", "_major": 1, "_minor": 0, "_patch": 0},
   "la:apiVersion": {"href": "https://linked.art/api/1.0/", "_major": 1, "_minor": 0, "_patch": 0},
   "la:localVersion": {"href": "https://example.org/extension/2.1/", "_major": 2, "_minor": 1, "_patch": 0},
 }
}
```
Which relies heavily on out of band extension properties on the Link Object class from HAL.

An alternative which is slightly longer but perhaps more readable and more consistent (b):

```
{
 "_links": {
   "la:modelVersion": {"href": "https://linked.art/model/1.0/",  "_embedded": {"major": 1, "minor": 0, "patch": 0}},
   "la:apiVersion": {"href": "https://linked.art/api/1.0/",  "_embedded": {"major": 1, "minor": 0, "patch": 0}},
   "la:localVersion": {"href": "https://example.org/extension/2.1/",  "_embedded": {"major": 2, "minor": 1, "patch": 0}}
 }
}
```

But it is not obvious from the documentation whether `_embedded` is allowed on Link Objects or whether there would need to be an `_embedded` separately, with separate objects in it, each with a `self` reference to the URI in `href` (c):

{
 "_links": {
   "la:modelVersion": {"href": "https://linked.art/model/1.0/"},
   "la:apiVersion": {"href": "https://linked.art/api/1.0/"},
   "la:localVersion": {"href": "https://example.org/extension/2.1/"}
 },
 "_embedded": {
   "la:versions": [
     {"major": 1, "minor": 0, "patch": 0, "_links": {"self": {"href": "https://linked.art/model/1.0/"}}},
     {"major": 1, "minor": 0, "patch": 0, "_links": {"self": {"href": "https://linked.art/api/1.0/"}}},
     {"major": 2, "minor": 1, "patch": 0, "_links": {"self": {"href": "https://example.org/extension/2.1/"}}},
   ]
}
```

Which looks like both a pain to generate and a pain to consume.

My preference is for (b). Thoughts?

**Comment by cbutcosk** [comment]
It seems advisable to stay close to the versioning pattern that the [HAL draft spec provides](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal#name-name). In the linked.art case it would look something like:
```json
{
  "_links": {
    "la:modelVersion": {"href": "https://linked.art/model/1.0/", "name": "v1.0"},
    "la:apiVersion": {"href": "https://linked.art/api/1.0/", "name": "v1.0"},
    "la:localVersion": {"href": "https://example.org/extension/2.1/", "name": "v2.1"},
  }
}
```

While their example is about `curies` this case seems pretty similar (`name` being a "secondary key" for the link).

**Comment by azaroth42** [comment]
@cbutcosk And then rely on the name being parsable (or at least sortable) in order to accomplish the goal of the client knowing which versions it can understand? The parse rules for your strawperson would be as simple as: 
1. remove the initial 'v'
2. split on '.' 
3. assume any missing values out to 3 places are '0'
4. parse strings to integers for major, minor, patch

And then compare against the client's supported versions. A little bit more work for the client ... but not much, and the result in the JSON is much cleaner.

**Comment by cbutcosk** [comment]
@azaroth42 Yep something simple, concise, and usable is probably best. Agreed those steps look OK and not much work for clients--most package managers use something similar, as does OpenAPI.

>  rely on the name being parsable (or at least sortable)

Yes and double-yes to sortable (vs integers). Actually-emitted linked.art api and model vers may always be integers, but patch versions are often stringy for good reasons and it's nice to keep them emittable in tooling spaces like tests, branches, and in feature-flag branches (and for sussing out when those accidentally make it to `main`--not that such things happen). `1.0.0b1`, endless release candidate series (again--never!), slugged datetime stamps, and so on.

**Comment by azaroth42** [comment]
If they're sortable and not integers, we'd need pretty clear naming rules for major and minor to avoid them sorting as v1,v10,v11,v2,v3 etc. I'd propose major and minor MUST be integers, and patch must sort correctly within the major+minor space but otherwise be a string.

**Comment by cbutcosk** [comment]
Yeah `int` maj/min and `str` patch seems fine. So the strawperson now with a stringy patch:
```json
{
  "_links": {
    "la:modelVersion": {"href": "https://linked.art/model/1.0/", "name": "v1.0"},
    "la:apiVersion": {"href": "https://linked.art/api/1.0/", "name": "v1.0"},
    "la:localVersion": {"href": "https://example.org/extension/2.1.0-beta1/", "name": "v2.1.0-beta1"},
  }
}
```

Should those URIs return JSON? Seems OK without given the low-footprint API design goal. For now avoiding `_embedded` avoids calling the question.

**Comment by azaroth42** [comment]
Approved  call of 2023-12-13

**Comment by azaroth42** [comment]
Done.
