### ISSUE TITLE
Textual Work -- About vs Refers To for subjects

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#513]
Not convinced we ever really know the distinction. Freedom from choice would say to merge together.

**Comment by aisaac** [comment]
"refers to" seems more 'active' in the sense that the object not merely 'happens' to be about a subject. A painting of a king could be said to be about royalty, but it doesn't refer to it.

**Comment by azaroth42** [comment]
Yes and no ... P67 refers to is the super property of P129 is about, so according to the ontology, any 'aboutness' is also a 'reference'.  

The distinction is that for `about` is that "it describes the primary subject or subjects" rather than for P67 which could be a passing mention or allusion. My concern is that in most systems all we have is "subject" rather than any difference between primary subjects and others. 

Given that, my proposal is that we should always use `about` for subjects rather than trying to make a distinction that doesn't exist in most datasets or other formats

**Comment by azaroth42** [comment]
Or only ever P67 ?

**Comment by azaroth42** [comment]
Regular cataloging rules say only to put in main subjects, so `about` would be correct.

Agreed to use `about`
