### ISSUE TITLE
Add Used_For to Set for exhibitions (etc)

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#514]
If you don't know about the objects in the exhibition, there's no need for a Set. So the optional Set should link to the more commonly known about Exhibition.

Also, Curation of a collection is the use of the set, carried out by the department or museum

**Comment by aisaac** [comment]
I'm not sure I understand the text above, sorry, even though there seems to be important case.

**Comment by azaroth42** [comment]
Sorry, should have been clearer!

In the Set API definition (https://linked.art/api/1.0/endpoint/set/) there's no way to connect the Set with an activity that it (or its constituent members) is used in, such as an Exhibition or the Curation of the objects. That's the inverse of `used_specific_object` on the Activity, which would be `used_for` on the Set.

Then whether the activities can be embedded (per #411), or must be separate records, or whether both is fine

**Comment by azaroth42** [comment]
Nope! Instead use used_specific_object on Event/Activity record.

**Comment by azaroth42** [comment]
New proposal:  Allow used_for on a Set ONLY to include an embedded 1:1 event that doesn't need to be referred to separately.  For example, the collection of the department is curated by the department -- we don't need a new event record for the curation, the same way we don't need a new event record for the publication of a linguistic object.

**Comment by azaroth42** [comment]
Done.
