### ISSUE TITLE
Add Linked Art logo

### ISSUE THREAD

**Issue by julsraemy** [linked-art/linked.art#538]
The Linked Art logo could be added to the website, for example:

- [ ] As favicon
- [x] In the header

The quality of the [logo](https://github.com/linked-art/linked.art/blob/master/docs/media/logo/Linked_Art_logo.png) we currently have is not of great. It's probably good enough for the favicon, but we should create a new one in SVG for the header.

**Comment by buccalon** [comment]
@azaroth42 @julsraemy could you point me to more context regarding the current logo design, please? 

I can prepare a SVG version of the current one, and we will probably need black/white versions too. However, I think we should discuss changes in typography and color contrast to improve its readability alongside other logos:

<img width="825" alt="image" src="https://github.com/user-attachments/assets/c3e27c43-ebcf-4934-8d03-cc8a235028d0">

**Comment by julsraemy** [comment]
> @azaroth42 @julsraemy could you point me to more context regarding the current logo design, please?
> 
> I can prepare a SVG version of the current one, and we will probably need black/white versions too. However, I think we should discuss changes in typography and color contrast to improve its readability alongside other logos:
> <img alt="image" width="825" src="https://private-user-images.githubusercontent.com/476699/378105069-c3e27c43-ebcf-4934-8d03-cc8a235028d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzI4OTksIm5iZiI6MTcyOTY3MjU5OSwicGF0aCI6Ii80NzY2OTkvMzc4MTA1MDY5LWMzZTI3YzQzLWViY2YtNDkzNC04ZDAzLWNjOGEyMzUwMjhkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwODM2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjM5MDE4MTMxMDhhZjJiZGM3NDc5MzE0OGQxZjFhNzE1YjA4MDhkMTQ3Y2YyNTUwY2UxMTFkYzNhOWZiYjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.otdybfLO24WChfpCRw_h6dFXQdMm970ppCnT1gpZQXM">

@azaroth42 can provide more insight about how the logo was created (back in 2019), here is already a link to several ideas: https://drive.google.com/file/d/1g4f6d5lBeiEOhFFnOfyv04Eu3ercM97l/view?usp=sharing
