### ISSUE TITLE
Machine readable link from HTML page to Linked Art record

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#541]
One method to do this is via schema.org:
  https://github.com/linked-art/linked.art/issues/516#issuecomment-1839113518 

But the requirement could be too high to embed the full schema representation into a web page. Are there easier methods, or can we extract the core function out from schema and describe exactly how to do that one thing, regardless of the rest of the schema.org mapping?

Other options could be an HTTP header (not easily visible/accessible to code); a header in HTML (needs a type, and to quantify linked-art-ness but accessible to JS at least); other microformats (but why, when there's schema.org), or other options I haven't thought of.

**Comment by workergnome** [comment]
A typed `rel` link might be the easiest to implement and consume?

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel

**Comment by azaroth42** [comment]
Yep, the link relations registry for the various values for rel is here: https://www.iana.org/assignments/link-relations/link-relations.xhtml 
The RFC for web linking using rels in headers is: https://www.rfc-editor.org/rfc/rfc8288.html

The closest is probably `describes` (?) but we'd want to have some way to say the linked-art-ness ... perhaps via media type:

```
<link rel="describes" type="application/ld+json;profile='https://linked.art/ns/v1/linked-art.json'" href="https://example.museum/object/1.json"/>
```

The schema.org property is (I think): https://schema.org/mainEntityOfPage   (e.g. the thing with the URI of <linked art uri> is the main entity described by me (the web page)

No harm in doing all of them, but we should at least mandate one way.

**Comment by azaroth42** [comment]
1.1 as backwards compatible -- outside of model and api, just a "best practice" ... but an important one.

**Comment by azaroth42** [comment]
Given #555, I think this gets pulled up to 1.0

**Comment by azaroth42** [comment]
Yes, and also add docs for `seeAlso` from IIIF Manifest for the same reason.

**Comment by azaroth42** [comment]
Returning to this, we could be in sync with the signposting spec with one change:  use describedBy instead of alternate.

The spec is here: https://signposting.org/FAIR/ 
And the discussion about the conventions is here: https://signposting.org/conventions/

This seems worthwhile to align with, as it's a very easy change that doesn't make a huge difference semantically, we're just affirming that from a high level, the web page content describes the thing which is described by the content retrieved in the body of the URI for the object (or other entity).  This treats the URI as the URI of the entity described by the data (eg the model level, not the API level)

At the moment we use `alternate` as the body of the web page is an alternate representation of the body of the API response. This treats the URI as the URI of the response itself, not the entity (e.g. the API level and not the model level).

Both are valid, but alignment with an external spec seems to tip the balance towards URI-as-model, not URI-as-API.
