### ISSUE TITLE
Mapping Multiple Current Locations into single HumanMadeObject

### ISSUE THREAD

**Issue by bluebinary** [linked-art/linked.art#543]
At the Getty (and I'm sure at other institutions) we have a need to be able to map multiple current locations into the same `HumanMadeObject` in the case where a single Object record in our collections management system (TMS in our case) represents multiple parts, and where some of the those parts are in one location, and other parts are in another location.

While the single Object record represents multiple separable parts, the multiple parts have not actually been catalogued separately into their own distinct collections management system Object records, and it is extremely unlikely that they ever will be due to there being scant data to make cataloguing the individual parts worthwhile as well as due to time and resource constraints.

As such we have single Object records in TMS representing multiple separable parts, with those single Object records being assigned multiple display locations as well as sometimes one or more storage locations so that staff can keep track of where all of the multiple parts catalogued under this single record are actually located.

From reading the current Linked.Art documentation, and from our discussion during the Linked.Art call on 12/13, it seems there are at least three possible solutions to this need:

* Revise the cardinality of the `current_location` property in the Linked.Art context to allow multiple locations to be mapped into the `current_location` property at the top level of the `HumanMadeObject` record (this approach will however force all current adopters of Linked.Art to adjust their use of `current_location` to be lists of dictionaries, instead of the current singular reference to one dictionary).
* To partition the `HumanMadeObject` record via its top-level `part` property, and to use the `part` property to carry two or more `HumanMadeObject` entities (likely as blank nodes), which embed their own individual `current_location` properties onto which each of the public display location references can be mapped. In this case the `HumanMadeObject` record's top-level `current_location` property would be omitted.
* To partition the top-level `Place` record assigned under the `HumanMadeObject` record's top-level `current_location` property, and to add a `part` property to the top-level `Place` entity to carry two or more additional `Place` entities which reference the multiple locations. The top-level `Place` entity would likely become a blank node.

There may also be other ways to accomplish this need, and workable, semantically valid alternatives are welcomed. The three discussed solutions listed above are illustrated below:

## Revising the cardinality of `current_location` to hold multiple `Place` references rather than a single `Place` reference:

```
{
  "id": "object/1",
  "type": "HumanMadeObject",
  "_label": "(Single Object record representing multiple separable parts)",
  "current_location": [
    {
      "id": "place/1",
      "type": "Place",
      "_label": "Place #1"
    },
    {
      "id": "place/2",
      "type": "Place",
      "_label": "Place #2"
    },
    ...
  ]
}
```

## Partitioning the `HumanMadeObject`:
```
{
  "id": "object/1",
  "type": "HumanMadeObject",
  "_label": "(Single Object record representing multiple separable parts)",
  "part": [
    {
      "type": "HumanMadeObject",
      "_label": "(Synthetic HumanMadeObject record to carry one of the current locations)",
      "current_location": {
        "id": "place/1",
        "type": "Place",
        "_label": "Place #1"
      }
    },
    {
      "type": "HumanMadeObject",
      "_label": "(Synthetic HumanMadeObject record to carry one of the current locations)",
      "current_location": {
        "id": "place/2",
        "type": "Place",
        "_label": "Place #2"
      },
      ...
    }
  ]
}
```

## Partitioning the `HumanMadeObject`'s `current_location`:
```
{
  "id": "object/1",
  "type": "HumanMadeObject",
  "_label": "(Single Object record representing multiple separable parts)",
  "current_location": {
    "type": "Place",
    "_label": "(Synthetic, partitioned Place record to carry each of the multiple current locations)",
    "part": [
      {
        "id": "place/1",
        "type": "Place",
        "_label": "Place #1"
      },
      {
        "id": "place/2",
        "type": "Place",
        "_label": "Place #2"
      },
     ...
    ]
  }
}
```

Feedback and thoughts on any of the above or suggestions for alternative ways to accomplish the same would be most welcome. This need isn't just specific to museum collections but very likely would also be of use for archival collections.

**Comment by azaroth42** [comment]
Discussed on a call -- better option is to partition the object if at all possible, as tracking "this object is here and it's also here" doesn't really help anyone. Having the same thing in two places at once is also very weird (without partitioning)

Partitioning the place is interesting, but very artificial -- the two locations could be entirely different, and when the object moves again, the synthetic place disappears, which would be annoying to track. Compared to partitioning the object which is just better description.
