### ISSUE TITLE
Consider .1 properties for scope and model

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#55]
Thanks to @Conal-Tuohy, in #51 ...

Property | Property subtype property
------------|----------
`P3 has note` | `P3.1 has type`
`P14 carried out by` | `P14.1 in the role of`
`P16 used specific object`|`P16.1 mode of use`
`P19 was intended use of`|`P19.1 mode of use`
`P62 depicts`|`P62.1 mode of depiction`
`P67 refers to`|`P67.1 has type`
`P69 has association with`|`P69.1 has type`
`P102 has title`|`P102.1 has type`
`P107 has current or former member`|`P107.1 kind of member`
`P130 shows features of`|`P130.1 kind of similarity`
`P136 was based on`|`P136.1 in the taxonomic role`
`P137 exemplifies`|`P137.1 in the taxonomic role`
`P138 represents`|`P138.1 mode of representation`
`P139 has alternative form`|`P139.1 has type`
`P144 joined with`|`P144.1 kind of member`

- [X] `P3.1` We don't use P3
- [X] `P14.1` Covered by #51 
- [X] `P16.1` Should also be covered by the same technique as #51 -- just make a sub-activity with a P2 that is about the mode of use of the object
- [X] `P19.1` Ditto, but not sure that we have any use cases for P19 anyway
- [x] `P62.1` No use cases where the distinction is needed yet
- [ ] `P67.1` Probably a P2 on the referring text?
- [X] `P69.1` E29 (the domain and range) isn't used
- [X] `P102.1` Title isn't used(!); just Appellation
- [x] `P107.1` For workshop of, use actor that carried out creation of group. Still probably need more detailed roles for other situations, but they haven't come up yet as needed.
- [ ] `P130.1` No use cases?
- [X] `P136.1` E83, P136 not used
- [X] `P137.1` Ditto
- [X] `P138.1` See P62.1
- [ ] `P139.1` Use cases?
- [x] `P144.1` Use cases?

**Comment by Conal-Tuohy** [comment]
What's the story with `P3 has note`? In my experiment with the Collections API of Museum Victoria, I used it a couple of times. From that and other data sets I've seen it seemed to me that relatively informal "notes" would be a fairly common data type in museum CMS. Do such things end up elsewhere in the Linked.Art profile? Or just excluded?

**Comment by azaroth42** [comment]
The big issue is that it changes semantics depending on which class it's used with, which might be okay in the serialization-free CRM, but in RDF is a no-no.  For example, it's a generic note on most classes, but a transcription for an `Inscription`. So if I want to have a note associated with an `Inscription`, I can't programmatically distinguish between transcription of the original and note about the resource.

So ... we use `rdf:value` for all "values" of things, and a `referred_to_by` `LinguisticObject` for notes / statements.  That way 3.1 is the classified_as of the LinguisticObject, and the value is just another use of `rdf:value`.

**Comment by azaroth42** [comment]
So for your cases, I think we'd do a Linguistic object with an aat classification for each of object description versus physical description, per http://linked.art/model/base/#3-statements-about-a-resource

**Comment by Conal-Tuohy** [comment]
I hadn't known about the recommendation to use `P3 has note` for transcriptions. I agree that is awful. I think the CIDOC should purge the model of these "metaproperties" and align their metamodel with RDF. The extra complexity of the metamodel is not worth it, and pragmatically, if it's not expressible in RDF, it's a major barrier to adoption.

**Comment by azaroth42** [comment]
This is what the CRM has to say about P3:

> Additional information that __falls outside the semantics formally defined by the CRM__ can be recorded as unstructured data using `E1 CRM Entity P3 has note E62 String`.
> (Intro, pg xviii, emphasis added)

> The text of an instance of `E33 Linguistic Object` can be documented in a note by `P3 has note E62 String`
> (Pg 18, under E33 definition)

> The transcription of the text can be documented in a note by `P3 has note E62 String`
> (pg 19, under E34 definition)

> The property `P3 has note` allows for the description of this content model
> (pg 40, under E90 definition)

> This property is a container for all informal descriptions about an object that have not been expressed in terms of CRM constructs.
> (pg 48, under P3 definition)

`P3_has_note` is a kludge of the worst sort 😿  How can it be both not expressed in terms of CRM and then used for specific, different cases under E33, E34 and E90 ... none of which are actually "notes" but instead the value of the resource. One despairs!

**Comment by workergnome** [comment]
P144.1 has come up in #62, as well as P107.1.  I lean toward thinking that this is outside of the scope of what we're doing here (we're also not modeling family relationships, or other intracacies of human relationships), but perhaps we should be explicit about that?

**Comment by azaroth42** [comment]
Yes, agreed. It's an art project (heh), not a person project. Put it in model/actor ?

**Comment by workergnome** [comment]
I'd be fine with that.  something like:  "The nuances of person-to-person relationships are outside the scope of this project, beyond simple membership in groups.  This includes the details of family relationships, group roles, and other similar reifications of the nature of relationships"

**Comment by workergnome** [comment]
Probably worth checking out this (https://www.w3.org/TR/vocab-org/) when we decide to revisit.

**Comment by bitno** [comment]
Hello everyone,
As p67.1 is not yet marked as solved, I would have a use case. In our data E38 or an E22 use p67 to refer to an actor E39. In all cases I know in what kind of type/role they refer to this actor, eg. the actor could be the architect of the depicted/discussed work. Would you in this case use p67.1 or is there a better way to express this information?
And forgive me for asking this question here, I was searching your git for p67 and decided to post in this issue, instead of the slack channel.
Many thanks,
Leo

**Comment by azaroth42** [comment]
Hi Leo,

Just to clarify your current usage ... P67 has a domain of E89 Propositional Object. E38 Image is a descendant of E89, but E22 Man-Made Object is not, being the physical thing rather than the intellectual content that it carries.

P67 says:
> P67 refers to (is referred to by) has the P67.1 has type link to an instance of E55 Type. This is intended to allow a more detailed description of the type of reference.

I think the intended use is to clarify the "about-ness" of the intellectual content to the resource that is being referenced by it. For example, a text that is a citation of another text is referring to the second text by citing it, a text might refer to a Dimension by providing evidence for it, or an image might refer to a literary concept by being an allegory for it.  The content refers to the resource in some particular way.  If you knew that all already, apologies for mansplaining / mecspliquer.

I would express 'architect of' by adding a P2 has type / `classified_as` property to a Production activity that produced the MMO. Which avoids the problem but doesn't solve it.

The referring E89 could be partitioned, with the part having a P2 that identifies the type of content and has the P67 relationship. For example:

```
{
  "type": "LinguisticObject",
  "includes": [
    {
      "type": "LinguisticObject",
      "classified_as": [ "aat:citation" ],
      "refers_to": ["some-target-uri-goes-here"]
    } 
  ]
}
```

Saying ... there is a part of this content that is a citation that refers to the target resource.  

Thoughts?

**Comment by bitno** [comment]
Dear @azaroth42 

This helps a lot. In putting the lingustic object in-between I get more flexibility. Is there an issue in using too many linguistic objects?

Many thanks and kind regards,
Leo

**Comment by Conal-Tuohy** [comment]
It turns out that the CRM working group has in fact produced a better RDF mapping for these `.1` properties to RDF than the one which they have been pushing; esssentially reifying the properties-which-have-properties as ordinary resources, which can therefore have their own properties and be associated with `E55 Types` and so on. They have called it the "Property Class" technique.

http://www.cidoc-crm.org/Issue/ID-266-reified-association-vs-sub-event is an archive of a fairly relevant discussion on the CRM mail-list fro 2014.

http://www.cidoc-crm.org/sites/default/files/Roles.pdf presents a few slides showing options for modelling properties of properties, including the "Property Class" approach.

The RDFS expression of "Property Classes" is here: http://www.cidoc-crm.org/sites/default/files/CRMpc_v1.1_0.rdfs

These couple of slides include a nice illustration of the "Property Class" approach defined in the RDFS: http://www.cidoc-crm.org/sites/default/files/20160802PropertiesOfProperties.pptx

**Comment by azaroth42** [comment]
P62.1 is okay for two reasons:
* we don't use P62 in favor of the long-cut
* the VI in the long-cut ( P65 / P138) can have a classification of the mode
And similarly P65.1, P138.1 ... these are types on the domain/range.

P67.1 is the root cause for issue #159. Given that this is the only time it has come up, and we have two possible solutions, it seems done?

P130.1 almost certainly lacks data that would be used to implement it.  Should seek use cases in a time box and if none, then mark okay?

P139.1 - the type of alternate form is surely the type of the ... alternate form Appellation?

**Comment by azaroth42** [comment]
I propose to close this issue for two reasons:

1.  We approach the problem from a use-case-first pattern, and then look for a solution, rather than attempting to align all of the properties in CRM. Thus if we need a .1 property, then we will figure out how to do it.
2. We discussed it ad nauseum in #107 
3. There's a potential for a solution in the pattern described in #229

**Comment by aisaac** [comment]
WG discussion 28-1-2020: we agree it is better to solve the individual situations on a case-by-case basis, when a proper use case come for them

**Comment by azaroth42** [comment]
Closing, per WG discussion.
