### ISSUE TITLE
Document FAQ style decisions per class

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#56]
Each section should have answers to FAQ style questions. For example that People after death are still People, they are not somehow transformed into Things.

**Comment by workergnome** [comment]
Worth looking Into the Primer model as well for this.  I've found that remarkably good at helping me understand specs that are otherwise dense.

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-f0bf71e6b4ce4eb69c1c91ea430b24e6/page-1)

**Comment by azaroth42** [comment]
Summarizing discussion:  The FAQ construct is often unhelpful by being separated from the context of the topic of the question. As such, they should be avoided if possible.

The only current FAQ type entry is about the death of people, which could be a note in the  http://linked.art/model/actor/#birth-and-death-beginning-and-end-of-existence section.
