### ISSUE TITLE
`technique` or `classified_as`?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#561]
A long time ago (#155, #163, #13) we (David and I) decided to use `technique` rather than `classified_as` for the technique of Productions and other activities. A lot of water has passed under the bridge since then, and I think it's worth a brief consideration of whether that is still the right answer.

In favor of `classified_as`:
  * If you don't know if it's a technique or some other classification on the activity, that's okay, just shove it in classified_as
  * If you do know it's a technique, we could add a metatype for its technique-ness. This would be the same approach as nationality, gender, occupation and other similar specific types of classification
  * It reduces the footprint of the model and api by a property, and reduces the number of choices to make (is it a technique or not?)
  * Indexing / querying is easier as you don't have to look in two different properties

In favor of `technique`:
 * Status quo, and late in the game to make such a change
 * It keeps techniques separate from other classification without either metatypes or newly defined properties

Thoughts?

**Comment by cbutcosk** [comment]
Adding to `technique` case:
- Uses terminology that is legible to domain specialists.
- Better aligns `Production` structure with good access design patterns (dicts of arrays, not arrays of dicts) 
- Partitions a crucial search / index signal from the rather messy classification space
- Avoids use of meta-types for core object properties (#461 and overall context collapse of meta-types are unsolved issues)

I don't find the API footprint of `Production`s to be particularly large so this seems like premature optimization to me. Disambiguating the use case for `classified_as` and `technique` in documentation would seem sufficient to resolve the other modeling-ambiguity issues.

**Comment by azaroth42** [comment]
Agreement to keep it as is (call of 2024-01-10). Status quo.
