### ISSUE TITLE
How to model the publication year of a linguistic object?

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#569]
Is this the correct way to model publication year of a bibliographic entry by representing the year as a timespan beneath a Production activity on the LinguisticObject?  Related to this, if there's a creation date description in text form, presumably it should refer to the LinguisticObject and be classified as a creation date description?  Or should it be applied to the timespan directly?

**Comment by azaroth42** [comment]
This one is actually documented :) https://linked.art/model/document/#creation-and-publication 
And https://linked.art/api/1.0/endpoint/textual_work/#example

**Comment by azaroth42** [comment]
Closing
