### ISSUE TITLE
Make languages more usable in the API

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#570]
In the model, languages are dealt with at the data level ... e.g. linguistic objects have a Language associated with them via the `language` property. This can't change to two/three letter codes as there are languages that do not have these codes that are certain to be present in collections. 

However the data usability for the 99% case of the top 10 spoken languages is greatly reduced. Can we solve this in the API somehow?

**Comment by azaroth42** [comment]
Options:

(a) It's just an API affordance to make it easier for developers, so put in a new simple new non-semantic property... which is what devs will like the most:

```
{
  "content": "hello world",
  "language": [{
    "id": "http://vocab.getty.edu/aat/300english",
    "type": "Language",
    "_label": "English",
    "_lang_code": "en"
  }]
 }
```

(b) No, it's a transclusion of an Identifier from the concept's information, no need for a new property:

```
{
  "content": "hello world",
  "language": [{
    "id": "http://vocab.getty.edu/aat/300english",
    "type": "Language",
    "_label": "English",
    "identified_by": [{
      "type": "Identifier",
      "content": "en"
    }]
  }]
 }
```

Which we could then say is `classified_as` a particular type of identifier explicitly, or we could assert in the API that ONLY the two/three letter codes can be transcluded like this (which would be my preference) and hence there's no need to also transclude the type of identifier.

(c) IIIF and others use language maps, so should we for embedded `content`

```
{
  "content": {"en": ["hello world"]},
  "language": [{
    "id": "http://vocab.getty.edu/aat/300english",
    "type": "Language",
    "_label": "English"
  }]
}
```

When there isn't a language (likely the most common situation) it would be 'none' as the key:

```
{
  "content": {"none": ["hello world"]},
}
```
Which would make it a very breaking change.


---

My preference is for (b)

**Comment by beaudet** [comment]
Not sure if it helps, but library of congress has the language codes as part of the iso 639-1 language definitions:
e.g. http://id.loc.gov/vocabulary/iso639-1/zh

**Comment by cbutcosk** [comment]
It seems incomplete to me to reduce this to checking a string at `.language.identified_by[0].value` when as @beaudet points out LOC has ISO-aligned URLs available for use on `.language.equivalent`? If the concern is that IETF is technically a superset of ISO-639-1? Reducing this to string matching does not seem more usable.

**Comment by azaroth42** [comment]
We already have URIs for the languages and we can add additional `equivalent` links to references to make connection easier. The difficulty in my experience is that URIs are and should be opaque, and language of the content is in basically every other API, either linked data or otherwise, expressed only via the two/three letter codes, sometimes with the locale ala en-us or es-br. Developers expect to be able to easily find language in "en" vs "fr", rather than having to deal with these crazy URI things.

In a full graph environment, you could just traverse the connections from the LinguisticObject to the Language to the Identifier to find LOs that are in "en" ... but not in the API, which is this particular issue.

**Comment by cbutcosk** [comment]
If the goal is to interoperate with other machine-readable data sources as a developer I prefer `_language_tags` with a gesture to https://www.w3.org/International/articles/language-tags/ , with the domain typed Array<string> to account for processing-critical but contextually-separable multiples like [ `fr`, `fr-CA` ].

**Comment by azaroth42** [comment]
Option (d) from @bluebinary 

Can we import a new term into the ontology for the iso code identifier, getting the API benefit of (a) and the semantics of (b)?

**Comment by azaroth42** [comment]
Reading the devils in the details ... ISO639-1 isn't exactly what we want. (Of course, when is it ever easy?)
What it doesn't include is 639-2, the three letter codes that expand the space to include a lot of less common languages.

Also, it doesn't include the locale and script from [RFC5646](https://datatracker.ietf.org/doc/html/rfc5646.html) / BCP47 which will likely be what is sent over the wire by language negotiating web browsers.

So my preference is for a new shortcut property defined in Linked Art.

API wise, should it be a string or list of strings? (e.g. can it be `["en", "en-us"]` or should it just be `"en"`. My preference is for a string for simplicity, but with ISO-639-1 and ISO-639-2 (and 3 and 5), it could be an array to handle `["en", "eng"]`

**Comment by azaroth42** [comment]
* use `skos:notation` -- essentially domain of crm:E1_Entity.
* JSON key of `notation`
* array of strings

```
{
  "content": "George",
  "language": [
      {
         "id": "aat:american-english",
         "type": "Language",
         "notation": ["en", "en-us", "eng"]
      },
     {
      "id": "aat:french",
      "type": "Language",
      "notation": ["fr", "fr-ca", "fre"]
     }
  ]
}
```
