### ISSUE TITLE
document difference between multiple classifications applied to an entity vs. a metatype

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#571]
#568 - lists an example of describing a linguistic object that represents a former attribution as follows:

        "referred_to_by": [
            {
                "type" : "LinguisticObject",
                "content": "Arelia Arbo"
                "classified_as" : [ 
                    {
                       "id" : "https://vocab.getty.edu/aat/300056109",
                       "type" : "Type",
                       "_label" : "attribution"                        
                    }
                    ,{
                       "id" : "https://vocab.getty.edu/aat/300404270",
                       "type" : "Type",
                       "_label" : "formerly attributed to (attribution qualifier)"
                    }
                ] 
            }
        ]
        
This usage is presumably valid but leaves me wondering about the differences between multiple classifications applied to the same entity vs. a classification with a metatype.  

FOR EXAMPLE / DISCUSSION ONLY - NOT NECESSARILY PROPOSED DEFINTIONS:
-----------------------------------------------------------------------------------------
While there's some documentation about meta-types, there doesn't appear to be a formal definition that includes something along the lines of: a meta-type should be used when a single classification term cannot be found to express a specific enough concept to correctly convey the semantic meaning of the data.  In such cases, a meta-type should be used to bring this new term into the fold of existing terms.  For example, if red, green, and blue are located beneath a concept called "colors" in a thesaurus, but cyan is not included there then a term for cyan should be identified in a different thesaurus or created as a custom term.  Furthermore, the cyan concept should be decorated with a meta-type of "colors" to ensure it is considered to be "the same type of thing" as red, blue, and green.

Multiple types assigned to an entity, on the other hand, should be used to convey that an entity has aspects or attributes of BOTH terms.  It doesn't, by itself, result in a new concept.   For example, a linguistic object is both an attribution (it started out as a standard attribution before it was changed) but it now is also a former attribution.  So, via this expression, it could be considered to be an attribution. 

Finally, we might have a custom term that is assigned multiple meta-types. 
e.g. former_attribution is a custom term that has a meta-type of attribution and a meta-type of formerly attributed.  This custom term could then be used in place of the more verbose type representation if desired.  But what does that mean exactly?  It would mean that the custom term falls under "attribution" and also falls under "formerly attributed to", so it's polyhierarchical.  Are there any challenges in processing such metatypes correctly?  My concern is that we should be very specific with our definitions here so we're not all scratching our heads wondering how to interpret these various expressions of types.

**Comment by azaroth42** [comment]
Yep -- multiple classifications are all classifications of the entity that has the `classified_as` to them. A meta-type is explicitly the type of a type.

e.g. The object is an oval, a painting, and a highlight. Oval is a shape. Painting is a Type of Object.
oval, painting, highlight = multiple classifications of the object.
Shape = metatype of Oval
Type of Object = metatype of Painting.

**Comment by beaudet** [comment]
If I'm creating a new local concept, for say, sequence as a positional attribute, what thought process should I be following as I consider how to construct this term?

for example: "If AAT were completely fleshed out, maybe I would find sequence below the positional attributes AAT hierarchy already, but since it's not there, it seem I have to either create a new concept for sequence, use a linked art published concept, or find sequence in another well-recognized thesaurus.   I looked and couldn't find it in any other vocabularies so let's create the custom term.  So, sequence is a type of positional attribute so that should be its meta-type.  

"type"   : "Concept"
"id" : "https://local_concepts_r_us.com/12345abcdef"
"_label" : "local concept for sequence as a type of positional attribute"
"classified_as": [ {
    "id" : <AAT URI for positional attribute>
   "type":"Type"
   "_label" : "positional attributes"
} ]

Is it valid to assign multiple meta-types to a concept or is that discouraged for Types?  For example, for a "photographic painting", would it be appropriate to assign a metatype of both "photograph" and "painting" to a local concepts to birth a new "photographic painting" concept and then assign that type to the Human Made Object rather than assigning both terms individually directly to the HumanMadeObject?

And if that's valid, does or even can "equivalent" play a role in this local concept definition?

**Comment by azaroth42** [comment]
Done
