### ISSUE TITLE
how to model a video that is tagged as "associated with" a human made object?

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#574]
I asked this on the modeling channel on Slack so I'm copying the initial discussion here:

Beaudet
We have audio and video files that have a connection with art objects and actors in the sense of "they should be displayed on the web page of those entities", but the relationship isn't specified explicitly.  Would you recommend using "digitally_shows" as the predicate or is there a more generic one you'd recommend in the absence of this detail?  And furthermore, does "digitally_shows" imply that this predicate only applies to video?  There's no "digitally_sonifies" predicate that I've seen. (edited) 

azaroth42
heh. if they're not representations, just associated, I'd use AttributeAssignment

beaudet
I mean the content is about those works or people so it's possible / likely they are displayed or discussed in the media.
But no way to tell for sure without examining each.
And the digitally shows would be to a currently nonexistent visualitem rather than the entity but let's set that aside for now. 

Are you recommending assignment of a specific LA property like subject or about via the attribute assignment? Seems like if visualitem is the intermediary, the visualitem could have an about property that lists the art object or actor instance?
We'd have to synthesize a visual item for this purpose rather than pointing directly to the art or actor instance.

It would be helpful to see an example of using AttributeAssignment to accomplish this. Thanks!

**Comment by beaudet** [comment]
#272 is related and I assume after an AudioItem is created we can proceed with that as well, so hopefully we can resolve #272 soon as well.

**Comment by azaroth42** [comment]
If the content is about the object / actor, then I would create records for the `DigitalObject` and its `LinguisticObject` (as a Work) that is then `about` the object or actor.  If it's just an "associated" or "related" thing, then I would put it under AttributeAssignment (also per #576).
