### ISSUE TITLE
How to model a digital image that is a comparative figure for a HumanMadeObject?

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#576]
How can we model a digital image that is a comparative figure for a HumanMadeObject?

This would be an image (usually of another art object but not necessarily) that scholars have found useful when writing or speaking about the referenced art object.

**Comment by azaroth42** [comment]
AttributeAssignment on the HMO to a Digital Object for the image, without 

e.g. there's no direct relationship, but it's worth associating the two together.

It's like objects that are "related" to the current one -- people have found these to be "useful" together.

**Comment by beaudet** [comment]
Could you please show a JSON-LD example?

**Comment by beaudet** [comment]
I've opted not to include images that don't have a direct relationship to the HMO.  They might still make it into the graph in their own right as native Digital Objects, but they won't be linked to an HMOs.  I thought about this and I think it's cleaner to allow the natural relationship to remain as is which is that images that don't depict the HMO and are only "related" to the HMO aren't actually directly related to the HMO.  They are related through an entity such as a scholarly essay so, while it might provide a shortcut, if we wanted the once-removed relationship for some reason, the right answer is probably to incorporate the essay into the graph.  That can certainly be done as more content is harvested and described as linked art.

**Comment by beaudet** [comment]
[girl_with_a_broom_draf_2.json](https://github.com/linked-art/linked.art/files/14565496/girl_with_a_broom_draf_2.json)

Here's an updated version of Girl with a Broom as Linked Art.  Eyeballs appreciated.
