### ISSUE TITLE
Fix insane CRM domain/range of current_location

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#585]
`P53 has former or current location` has a domain of E18, meaning that any physical thing can have a Place which is where it is now, or where it used to be.

`P55 has current location` has a domain of E19 Physical Object, meaning that physical things that are not also physical objects (such as features, which we might need to use for Conservation and Stratigraphy) can have a former or current location, but cannot have a current location.

This is in the current 7.2 era specifications (reported to George as editor and co-chair). I propose that we treat P55's domain as E18, not E19, as if something can have a former *or current* location, then it must be able to have a current location.

**Comment by beaudet** [comment]
Can changing the domain of a property be represented as a set of statements to be layered over the ontology / schema prior to validation?

**Comment by beaudet** [comment]
Sorry, can you elaborate on what you mean by "for everyone to just publish a fork of the RDFS"?  Could we all just reference the same document published on the linked art site?

**Comment by azaroth42** [comment]
My bad. Yes, I mean that we publish a full RDFS on linked art with the fixed domain and range, then if people need it, they can use our copy.
