### ISSUE TITLE
Engraving Plates, Making Prints

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#59]
Document `used_specific_object` for a plate used in making a print, or a negative used in making a photography, or a cast for a metal sculpture.

(And acknowledge that we're climbing the ladder up to the top of the slippery slope of FRBR / information object vs man made object distinctions)

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-9433b2793f534ee0b77a00260bd5d02c/page-1)

**Comment by azaroth42** [comment]
Discussed on the 10/09 Pharos Data Model call:

`used_specific_object` doesn't sufficiently cover the printing case (in the Pharos case for photographs), as it could be that the negative was used to create a collage of negatives, not a print.  While it would be possible to infer that the same image is carried by the different E22s based on the P2 of the creation event (collaging vs printing) that inference shouldn't be necessary, and relies on external vocabularies.

Proposal is to have multiple MMOs, one per print or negative, plus a single Visual Item that they all carry. 

So... two copies of a photograph from the same negative would be:

* A depicted MMO (painting, P)
* A Visual Item (VI) which is a representation of the painting
* A MMO for the Negative (N), which shows the Visual Item
* Two further MMOs for each print (P1, P2) of the negative

So:
```
P representation VI .
VI shown_by N, P1, P2 .
P1 produced_by P1c .
P1c used_specific_object N .
```

And if you don't know that the Negative was used for the P1 photograph, then you just don't record that.  Thus it scales well when the information is not known.

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-b50efe38463b421c8e9a4749c0ad2302/page-1)

**Comment by azaroth42** [comment]
Knock on effects:

* No need for the dcterms:subject shortcut, we can go back to the longcut through the visual item.
* Statues would also have Visual Items that represent the sitter.
* Digital image files would remain Visual Items, following from the scope notes that E73 Information Object can be used for a JPG ... and VI is a subClass of E73.

**Comment by workergnome** [comment]
I think of VisualItems (and InformationObjects as a whole) as merge points, where a non-CRM representation of an entity can be joined with a the CRM itemness.  I would be careful about the abstract "digital image file" and the specific "digital image file" distinction:  There can be many copies and many derivatives of a digital file, all of which share the same VisualItem, which is what we want, but the ID is not for any one specific one of these, in my opinion.
