### ISSUE TITLE
occurs_during vs part_of

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#599]
In updating the ontology, I ran into our import of `occurs_during` from archaeo. Do we actually need it? Can't we just use `part_of`?

Definition of `part_of` (P9): This property associates an instance of E4 Period with another instance of E4 Period that is defined by a subset of the phenomena that define the former.

Definition of `occurs_during` (AP25): This property identifies the situation in which the entire temporal extent of an instance of E2 Temporal Entity is within the temporal extent of another instance of E2 Temporal Entity that starts before and ends after the included temporal entity.

Note that Period (and further subclasses of it) is the only subclass of Temporal Entity that we use. The other is E3 Condition State (which we would instead use Phase, if we ever have a real need for it).

**Comment by beaudet** [comment]
This is probably a question primarily for those currently publishing Linked Art in production, but FWIW, I've not encountered a need to use this yet.

**Comment by azaroth42** [comment]
Summarizing from George on the call:

Concern -- If we know that (e.g.) the production of an object was in the bronze age, and we use part_of, and then want to find all parts of the bronze age, there would be early bronze age, middle bronze age, late bronze age, and the production of an object. While technically true (the production is fully part of the bronze age) it could be valuable to distinguish between the formal partitioning and the uncertainty of timespan cases.

From an _API_ perspective, this can be distinguished for Productions (as the production is in the HMO record) but could not be distinguished for temporal entities like Exhibitions ... the parts of 18th century are first half, second half, and random exhibition would be indistinguishable.

We could import P10 as `during`, avoiding the Archaeo extension.

Rob thinking:

We would need to make it clear which of `part_of` and `during` to use -- I think it would mostly be `during`

**Comment by azaroth42** [comment]
Analysis:  Use of part/part_of and during in temporal entities

* Most common partition is to manage roles in events. Eg. production, encounter, creation, provenance events etc. This is true partitioning.
* Second most common is managing parent/child relationship. e.g. activity X is part_of activity Y. 
* The only time we actually want `during` is when we want to assert a general relationship to a particular, likely named, period of time. e.g. Production during Victorian Era or during Bronze Age. Might be a stand-in for a TimeSpan (bronze age) or might just be to situate the event in context (Victorian).

Propose `during` as P10, usable on any Period/Event/Activity, must reference a Period. Then `part_of` is for strict hierarchies, and `during` is for temporal context.

**Comment by azaroth42** [comment]
P10 - E92 spacetime volume.

E4 Period sub class of E92
E5 Event sub class of E4

Scope note for P10: This property associates an instance of E92 Spacetime Volume with another instance of E92 Spacetime Volume that falls within the latter. In other words, all points in the former are also points in the latter.

So okay from semantics side and rename to `during` for understanding.

**Comment by azaroth42** [comment]
Needs update to the context and crom to do the mapping.
Also needed for #579 to map `after` and `before`
