### ISSUE TITLE
Find and list CRM / linked art sites

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#6]
To demonstrate just how different this all can be with just an ontology and no discussion.

Starting point:

* http://api.aucklandmuseum.com/id/humanhistory/object/30397
* http://collection.britishart.yale.edu/id/page/object/499
* http://collection.britishmuseum.org/id/object/EOC3130
* http://data.fondazionezeri.unibo.it/id/photo/113202.html
* http://edan.si.edu/saam/id/object/1991.189
* http://data.americanartcollaborative.org/page/npg/object/49748

**Comment by workergnome** [comment]
http://pch.ghamari.net/search/artefact?term=&sort=&pageSize

**Comment by azaroth42** [comment]
Is there a way to get to the actual data in Artefacts Canada? Other than the debug info currently inserted into the page?

**Comment by workergnome** [comment]
Dunno.  I'll ask, but I know they're under active development.

**Comment by workergnome** [comment]
http://data.itatti.harvard.edu/resource/Start

**Comment by azaroth42** [comment]
This has become a task of the CRM SIG as of last week in Paris.
Propose to close and let the SIG do it for us until we get any implementations, and that @Habennin and @azaroth42 to ensure that the above are listed in the CRM site.

**Comment by azaroth42** [comment]
No objections to closing.
