### ISSUE TITLE
Document "copy after" and "workshop of" attributions

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#62]
"copy after" is a Production event that was P15 influenced by the object being copied.  P17 is too specific -- the object is not a reason for carrying out the copying activity, it's only an influence.

"workshop of" is a Production event that was carried out by a Group -- the workshop. The entire group didn't carry it out, just one or more members of it, which is okay. No need for an anonymous individual member. The founder of the group (who the workshop is of) is the actor that carried out the founding of the workshop group.

Adding these probably makes the provenance page too long to be a single page, and should be split up a bit.

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-7dd2ab7355e84723a19eea8bcbf72b53/page-1)

**Comment by mdlincoln** [comment]
<- votes that object production/attribution get its own page

**Comment by workergnome** [comment]
"Copy after" references a work, or a person?

**Comment by azaroth42** [comment]
Copy after/of refers to a work, rather than a person.

Documentation is here:  https://linked.art/model/provenance/production.html 

Sufficient to close, @workergnome @mdlincoln?

**Comment by workergnome** [comment]
Are we requiring people to treat attributions to "Workshop of Rembrandt" differently than other "Rembrandt" attributions?  (since all other attribution patterns are just typed Attribute Assignments)

Or are we detailing an expanded pattern for people who wish to support Workshops as a special case?

**Comment by azaroth42** [comment]
Well, the main attribution pattern is just `carried_out_by` so I think the latter -- this is just a case where the actor is a `Group` not a `Person`.  Perhaps there should be more information about groups in the actor/ section?

**Comment by workergnome** [comment]
I think I'm trying to differentiate between:

`carried_out_by: "Workshop of Rembrandt"`

and 

```

**Comment by azaroth42** [comment]
My understanding from the discussion in slack was that the "workshop of" pattern really was a bona fide `carried_out_by`, unlike "style of". Is there a need to differentiate? Given that Rembrandt is (presumably) a member of Workshop of Rembrandt, it's still possible that he participated in or carried out the `Production`.

**Comment by azaroth42** [comment]
workergnome marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-2c5f7734d02b4ba38973293467d21b5b/page-1)

**Comment by azaroth42** [comment]
Decision: 

> Use Actor pattern when you are talking about Truth (current state of knowledge), and AttributeAssignment when you’re talking about historical or uncertain assignments.
> So if you’ve got a ULAN or internal Actor who is “workshop of Rembrandt”, it’s the Actor pattern.
Actor’s a group.
> If you’ve got the Created pointing to the actor Rembrandt, but you’ve modified that with a caveat of some sort, AttributeAssigment

Will write this up in the docs, and close when merged.
