### ISSUE TITLE
Missing RDF Terms Documents

### ISSUE THREAD

**Issue by bluebinary** [linked-art/linked.art#631]
I noticed that the following RDF terms documents, referenced from the current [linked-art.json](https://linked.art/ns/v1/linked-art.json) context document, are missing from the [linked.art](https://github.com/linked-art/linked.art/tree/master/docs/ns/terms) repository "docs/ns/terms" subdirectory, and the [linked.art](https://linked.art) website:

* https://linked.art/ns/terms/members_exemplified_by
* https://linked.art/ns/terms/members_contained_by
* https://linked.art/ns/terms/contains_members_of
* https://linked.art/ns/terms/lang_code

Please could these missing documents be added and deployed to the linked.art website?

If there is anything I can do to help with adding these, I would be happy to do so.

Separately, there are several other third-party RDF terms documents missing that are also referenced from the current `linked-art.json` context document:

* http://purl.org/dc/elements/1.1/format
* http://www.ics.forth.gr/isl/CRMdig/D1_Digital_Object
* http://www.ics.forth.gr/isl/CRMsci/S19_Encounter_Event
* http://www.ics.forth.gr/isl/CRMsci/O13_triggers
* http://www.ics.forth.gr/isl/CRMsci/O13i_is_triggered_by
* http://www.ics.forth.gr/isl/CRMsci/O19_encountered_object
* http://www.ics.forth.gr/isl/CRMsci/O19i_was_object_encountered_at

I'm not entirely sure what we can do about these missing third-party documents, unless it is a matter of adjusting the relevant prefixes in the `linked-art.json` context to point to another web location that hosts copies of these, or if we can reach out to the relevant organizations to see if these documents could be made available at the relevant URLs?

**Comment by azaroth42** [comment]
This is (thankfully) easy -- there's a script that generates the files, I just haven't run it since updating the context.
The external ones are of course much harder to accommodate :) 

`lang_code` will go away in favor of `skos:notation` per recent decision ... I just haven't re-updated for that yet

**Comment by azaroth42** [comment]
There's something weird about the redirection for members_exemplified_by, but it's there in the repo...
