### ISSUE TITLE
Typos to fix

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#633]
From @tomcrane:

* https://linked.art/model/actor/#gender the example json doesn't match the web page (id is reused somehwere else)
* https://linked.art/example/provenance/ziwei_yuag/1.json has a typo of "lanscape"

**Comment by tomcrane** [comment]
* Dates in https://linked.art/example/activity/exha/1.json are not valid (missing hh:mm:ss)

**Comment by tomcrane** [comment]
* Also dates in https://linked.art/example/activity/exhb/1.json

**Comment by taiwanken** [comment]
Not sure if there's a more apt thread for it but in https://linked.art/model/base/ "Rembrandt (a person) has a nationality of Dutch" is linked to the AAT entry for the Dutch language (aat:300388256) rather than "Dutch (culture or style)" (aat:300111175), the latter being used when the same info is modelled in https://linked.art/model/actor/#nationality

**Comment by tomcrane** [comment]
Another example mismatch

https://linked.art/model/assertion/#related-entities (`nightwatch/17`) is not the same as https://linked.art/example/object/nightwatch/17.json

**Comment by tomcrane** [comment]
Also these two links are broken on https://linked.art/model/

<img width="271" alt="image" src="https://github.com/linked-art/linked.art/assets/1443575/75e691bd-3909-48d7-b5e1-0fd7a6710db7">

**Comment by julsraemy** [comment]
> Also these two links are broken on https://linked.art/model/
> <img alt="image" width="271" src="https://private-user-images.githubusercontent.com/1443575/335207552-75e691bd-3909-48d7-b5e1-0fd7a6710db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjU2MjMsIm5iZiI6MTcxNzUyNTMyMywicGF0aCI6Ii8xNDQzNTc1LzMzNTIwNzU1Mi03NWU2OTFiZC0zOTA5LTQ4ZDctYjVlMS0wZmQ3YTY3MTBkYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTgyMjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWJmMTVmZDNkYWU0Yzk5YzM1NmFkYjRlYTMzMmM0MjI1ZDIzYWI0NTk1ZDEzYzJlM2VkMTI2NDE5Nzc5MzU2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L9bIvvTzE73SGXCIWZLNL9ZW7gtwDveVFClcebLY0to">

I think `https://linked.art/model/vocab/` is a page that still needs to be created If I'm not mistaken. I don't know about the index of examples page though.

**Comment by azaroth42** [comment]
Examples is built by a script that needs to be updated. The rest is fixed. Thank you all!
