### ISSUE TITLE
Allow attribution of statements to people & licenses

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#635]
It would be good for newer professionals to be able to have statements (e.g. biographies, descriptions, etc) to have their name associated with it, and to then assert at least a -BY license with it to ensure it doesn't get lost in the mass of CC0 facts.

At the moment there's nowhere (intentionally) for this level of meta-meta-data to be captured, but should we add it?

This *could* be 1.1 as it's not breaking, just adding the regular fields to statements.

**Comment by beaudet** [comment]
I'm missing the "newer professionals" nuance. Are you looking for an "important person" concept?

Does the existing model not accommodate such statements? Are these museum professionals who probably already exist in the graph due to the duties carried_out_by them?

**Comment by azaroth42** [comment]
Sorry -- was making issues quickly during the linked art / quire discussion! The "newer professional" is the author of the biography, not the subject of it -- the value to them is having their name associated with the content that they wrote, which might be less important for established researchers or curators.

**Comment by azaroth42** [comment]
Proposal:
* allow created_by on statements <-- agreed
* allow subject_to on statements <-- agreed

**Comment by azaroth42** [comment]
Not sure where to put the model documentation for this. Statements are in basic patterns, but these additions don't seem "basic".  Additional patterns as a separate page?

**Comment by azaroth42** [comment]
Related to #648 -- this issue is for human attribution, 648 is software attribution.

**Comment by azaroth42** [comment]
I've put it with assertions, as it's meta-meta-data. Seems to fit okay :) Done.
