### ISSUE TITLE
Prevent multiple link rels in a single web page

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#636]
Because it's stupid

**Comment by beaudet** [comment]
Example?

**Comment by azaroth42** [comment]
There isn't an example of this in practice ... because it's stupid ... but we should prevent it from being legal (which it currently is).

e.g. at the moment you could have a page that says via link headers (https://linked.art/api/1.0/ecosystem/#data-visibility-from-html) that it describes 2 objects, 3 people, a concept and 6 places.

**Comment by beaudet** [comment]
Understood.  It might help in testing for the condition to provide a formatted example of the invalid pattern.

**Comment by azaroth42** [comment]
Discussed on call of 2024-06-12: no objections. More links would over-complicate things - document it must be the primary entity only.

**Comment by azaroth42** [comment]
Done.
