### ISSUE TITLE
Modeling Buildings as Objects/Places

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#66]
In the CRM, there is E27 Site which is a Physical Feature.
> This class describes constellations of matter on the surface of the Earth or other celestial body, which can be represented by photographs, paintings and maps.

And E53 Place, which is a subClass of E1.
> This class comprises extents in space, in particular on the surface of the earth, in the pure sense of physics: independent from temporal phenomena and matter.

The examples of these two disjoint classes are highly overlapping:
  * Heathrow Airport is a Site, but the British Museum and Buckingham Palace are Places. (in the example of E26 and P74)
  * The city of [Knossos](https://en.wikipedia.org/wiki/Knossos) is a Site, but the city of Rome is a Place (in the P1 example)
  * Both Stonehenge and Salisbury Plain are Places (example of P89)
  * `took_place_at` refers to a Place ... so if Heathrow Airport is a Site, then activities cannot take place there. While many travelers might feel this is true, it's not actually so ;)

Places can be the location of Features, and Sites are Features, therefore:
  * Place(Los Angeles) is the former or current location of Site(Los Angeles).

But also:
  * Place(Los Angeles) P156i is occupied by Site(Los Angeles)

With the note:

> In the case of an E26 Physical Feature the default reference space is the one in which the object that bears the feature or at least the surrounding matter of the feature is at rest. In this case there is a 1:1 relation of E26 Feature and E53 Place.

So unless there are use cases in which the Physical Thing-ness of Sites is important,e.g. to allow P52_has_current_owner, then the use of Site seems to be overkill and all places should just be E53 Places.

(Yes that was a very long way of saying we should keep doing what we're doing)

**Comment by workergnome** [comment]
In general agreement about this, though I'm likely to start running into these issues with historical homes as objects, and it might be worth looking at how the architecture and archeology people are using this, if they're using this.  Though I might treat "Buckingham Palace" as a E22_Man-Made_Object if I needed to describe it in more detail, and think of the E53_Place as the "GPS Coordinates" of where the palace is located.

**Comment by azaroth42** [comment]
Yup, and our new collaborators from Historic England are dealing with a country full of built heritage.

I think buildings as MMOs makes a lot of sense. And caves or archaeological digs (the negative space, as opposed to the buildings that they uncover) as features.

**Comment by azaroth42** [comment]
Noted from slack discussion that Feature / MMO + Place is another example of multiple classes for a single instance.

**Comment by azaroth42** [comment]
So I think the question thus becomes:

1. Do we use a multi-classed Place + ManMadeObject?
2. Do we use a ManMadeObject that P156 occupies the Place?

I could see multi-classed being very handy for galleries that are the location of objects and where activities take place (Place), but are part of larger constructions and are owned by organizations (MMO).  Then you don't need two identifiers, one for the physical construction of the gallery, and one for the location in space that it delimits.

On the other hand, for cases like the [Bachman-Wilson House](http://crystalbridges.org/frank-lloyd-wright/), the MMO has occupied two distinct places, at different times. The multi-class situation would then lead one to say that the Move activity moved one Place to a different Place ... which is impossible.

(You can tell that I'm trying (and mostly failing) to write up documentation on Place)

**Comment by azaroth42** [comment]
Coming back to this, an MMO that occupies the Place seems like the best choice. Especially as partitioning would get very messed up -- is it partitioning in the Place aspect or the Object aspect. It would be very hard to decide which predicate to use, even without the serialization complication of the single json term!

**Comment by azaroth42** [comment]
P156 is not correct. Instead it is just current_location.

P156 is ...
> the volume that contains all the points which the thing has covered at some time during its existence.

Rather than where it is today. Also:
> the default reference space is the one which is at rest to the object itself, i.e. which moves together with the object.

**Comment by azaroth42** [comment]
Closing as this is now documented: https://linked.art/model/place/#buildings-and-locations
