### ISSUE TITLE
best way to model a couple acting together as one actor?

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#662]
We have a fair number of constituents tagged with a tms constituent type of "couple" (I'm guessing a custom value but obviously a common real world use case). 

Are couples modeled together as Person or as two people joined by a group representing the couple?

How are other organizations handling couple modeling?

**Comment by beaudet** [comment]
Since Actor is the base class of person and group, presumably most of the properties that would apply to an individual should be applicable on basically the same entity but cast as Group.   So this might be more straightforward that it seemed at first.  Rather than having to create new Person objects of the couple to establish group membership, just treat the couple as a singleton Group actor with no Person members rather than a Person. Any reason that shouldn't work?

**Comment by beaudet** [comment]
I think I saw a situation where corporate is the constituent type and mr. and mrs. are in the label - that's usually through a foundation or other legal instrument where a group is definitely the more natural fit.  The simpler and more complex cases might just be two expressions of the same thing?

groups -> 
     a family
     a married couple united under the legal instrument of their marriage 
     or their estate 
     or a foundation they've established where they might be participating directly (or not)

    group attributes (names, identifiers, etc. etc. perhaps a member_of property if the group is a member of other groups
   
person
   partner1
       member_of -> marriage, foundation, etc. etc.
   partner2
       same
       
If, as in our case, we're treating two people as one entity in TMS, then we can treat the marriage as a Group.  Since Group is an actor it should be able to do most of the things a Person can, perhaps in a Group way, but it seems like there should be effective parity in the model to handle the expression of two people acting as a Group vis-a-vis their marriage and other Groupy constructs?

**Comment by azaroth42** [comment]
I agree that the married (or otherwise) couple is a `Group` in Linked Art terms. Equally a Family would also be a `Group`. The individuals can then be `member_of` to the `Group`. There's lots of groups where we know zero or only some of the members, and otherwise they have all the same features as Person. So I can't see any reason not to go this route.

The marriage as an event could be thought of as the `Formation` of the `Group`.
