### ISSUE TITLE
question about occupation as metatype

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#666]
Should "gold workers" have a metatype of "Occupation" or a metatype of "artist occupation" in order to enable differentiation of gold workers from a collector, donor, dealer type of occupation?

or would it be best to list an occupation such as "cabinet maker" with a metatype like "furniture workers" in order to maintain the hierarchy so long as everything rolls up to "occupations" eventually?

**Comment by azaroth42** [comment]
No, the metatype pattern is there to enable consumers that don't have access to the whole graph to know that the "gold worker" concept is an occupation at all, and to group it with other occupations/roles, rather than with nationalities, gender(s), or other classifications.
