### ISSUE TITLE
Drop use of Purchase

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#67]
The proposal is to drop the use of `Purchase`, separate from `Acquisition`. The property `sales_price` from `Purchase` is not used, as it is either just a dimension with a particular type (consider Auctions' starting price, estimated price, reserve price, ...) or it's the amount that was actually paid, for which we need the extension `Payment` class anyway to model part payments, payments in kind, multiple buyers/sellers, commissions, etc.

Thus, https://linked.art/model/provenance/auctions/#purchase would instead just use Acquisition.

**Comment by azaroth42** [comment]
In cases where we do not know how much was paid, do we:

1. Create a `Payment` regardless, with buyer/seller as `paid_from`/`paid_to` but no `paid_amount` - which is more triples for something easily inferable. 
2. Not do anything, meaning the purchase-ness of the transaction cannot be known
3. Use an aat classification (http://vocab.getty.edu/aat/300077989) on all Acquisitions that are also Purchases.

I think 3 is the most consistent.

**Comment by azaroth42** [comment]
See: 
  https://no-purchase--linked-art.netlify.com/model/provenance/acquisition.html#activity_20 

:+1:s?

**Comment by workergnome** [comment]
:+1: to the "standard Acquisition, or Payment extension" decision.
