### ISSUE TITLE
Overlapping terms and categories in recommended and optional vocabulary terms

### ISSUE THREAD

**Issue by aisaac** [linked-art/linked.art#683]
(Sorry if this issue actually reflects my ignorance of the development status of vocabularies and/or documentation pages)

As it stands now I find it confusing to see that the page for [recommended vocabulary terms](https://linked.art/model/vocab/recommended/) and [optional ones](https://linked.art/model/vocab/optional/) include the same categories, especially when some of these categories are empty (Materials, Occupations, Nationalities, Genders, Languages, Currencies and Measurement Units on the page for optional terms) or have terms in common (for example  "Former Name in Name Types and "Condition Statement" in Statement Types).

Shouldn't we remove the duplicates and empty lists, and perhaps even move all the terms in one category into 'recommended' or 'optional' status?

**Comment by azaroth42** [comment]
Yes, there shouldn't be duplicates or empty lists :) Will fix.

Related to #659

**Comment by azaroth42** [comment]
Removed former name and empty categories.
