### ISSUE TITLE
Should we trash the difference between nationality and ethnicity as it is now?

### ISSUE THREAD

**Issue by aisaac** [linked-art/linked.art#684]
This is a bit provocative, but as I felt I had to create an issue specifically for the problems I have noted while investigating bias [here](https://github.com/linked-art/linked.art/issues/659#issuecomment-2445574238) (sorry I should probably paste bit of my comment here but I'm missing time now).

The issue manifests itself further when looking at LUX nationalities at https://lux.collections.yale.edu/view/results/concepts?q=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22name%22%3A%22nationality%22%7D%7D%5D%7D

There are plenty concepts used there, which would probably better fit the ethnicity as it is defined at https://linked.art/model/actor/#ethnicity.
For example ["Blood"](https://lux.collections.yale.edu/view/concept/b0857d0e-36f5-47c0-aa29-8166c0834afa) may be seen as a nationality ("Refers to the artwork of the North American Indians belonging to Blood tribe of the Blackfoot.") but probably if rather fit the level above ("Blackfoot"). (btw @azaroth42 I'm using this link as the one I could find quickest, but that pages seems to mix the tribe and the body fluid!)
["Aragonese"](https://lux.collections.yale.edu/view/concept/b0d78c8a-1816-4bd4-8e74-32382da9ce29) was a nationality once but it's not anymore, and its description in terms of "style and culture [...] bound by common ethnicity and language" matches better ethnicity.
And certainly "Parisian" has never match the notion of nationality. I reckon "nationality" is [mentioned in the original AAT concept](https://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300387719). But that feels like wrong vocabulary design in the first place.

It's not that I would oppose using AAT's weakly defined nationalities in Linked Art, but for the sake of interoperability it doesn't feel right to use them in a framework of nationality and ethnicity that is presented with much more precise (and exclusive) notions.

**Comment by azaroth42** [comment]
Regarding the LUX concepts -- yes, we don't make any attempt to validate these. They're asserted by external datasets, and we naïvely accept them as is. Will try to disentangle blood vs blood though!
