### ISSUE TITLE
updates to docs for _complete needed?

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#687]
Is the description below correct or does it need rewording?  It seems to suggest that even references must include _complete?  I thought this was only for cases where a portion of the entity is expressed beyond the reference.

_complete | boolean | Optional | Non-Semantic. If there is an id property with a URI, and there is more information about the activity available from the representation at that URI, then _complete MUST be present with a value of false to inform the consuming application that it might want to retrieve it

**Comment by azaroth42** [comment]
Hmm, yes, it's only if it's /not/ a reference ... needs rewording, thank you!

**Comment by azaroth42** [comment]
Done.
