### ISSUE TITLE
IIIF Images should have a format

### ISSUE THREAD

**Issue by workergnome** [linked-art/linked.art#7]
I think that the proposed model for [IIIF Images](http://linked.art/model/object/digital/#iiif-images) should have a `dc:format`.  

As a user, I'm likely to build a switch statement off of that property to evaluate how best to handle various representation formats (PDF vs MP3 vs JPG vs MOV), and having a value provided will allow that to make more sense.  

I suggest something that mimics the Presentation API, perhaps:

```json
   "format": "application/ld+json;profile=\"http://iiif.io/api/image/2/context.json\""
```

I would also (and possibly more likely?) be happy with a straight
```json
   "format": "application/ld+json"
```

**Comment by azaroth42** [comment]
I'm okay with it, but it does mix Resource and Representation in a strange way.  We say that it's an Image (which it is, abstractly) so to then be very concrete about the format of the representation (after following a redirect) that isn't an image media type seems to be mixing something up?  

The `conformsTo` field gives enough information to know its IIIF... but it would be nice to be consistent that all representations have a format. 

Added an issue for IIIF as to the profile.

**Comment by azaroth42** [comment]
Tagging as blocked up by upstream IIIF/iiif.io#1090

**Comment by azaroth42** [comment]
Unblocked by IIIF/api#1090 being fixed. Still needs better modeling as to what is happening.

**Comment by azaroth42** [comment]
@Habennin, @azaroth42 and Nicola Carboni (working with Thomas Hansli of ETH Zurich, part of linked art) are working on a revision of CRMDig (Digital) that includes the notion of a service. This would revamp the model for this issue.

Rob and George to report on a LA call to gather feedback.

**Comment by azaroth42** [comment]
Closing -- Discussion of the New Dig model being proposed was that the image is a real image (thus format would be JPG or similar) and it would have a Service, that conforms_to IIIF.
