### ISSUE TITLE
Shape of Object/Artwork/Part

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#70]
Rather than years of philosophizing about the interpretation of different wavelengths of light, and the tendency of the human brain to assert patterns onto our perceptions[1] ... how do we model shape (and color)?

Proposal is just to use `classified_as` with one of the aat terms in the shape hierarchy:
  http://www.getty.edu/vow/AATHierarchy?find=&logic=AND&note=&page=1&subjectid=300056273

Thus an oval painting would be:
```
{
  "type": "ManMadeObject",
  "classified_as": ["aat:painting", "aat:oval"]
  ...
}
```

[1] http://www.cidoc-crm.org/Issue/ID-255-shape

**Comment by Conal-Tuohy** [comment]
I agree re shape, but I think [E54 Dimension](http://www.cidoc-crm.org/Entity/E54-Dimension/Version-6.2) is the way to model colour:

> This class comprises quantifiable properties that can be measured by some calibrated means and can be approximated by values, i.e. points or regions in a mathematical or conceptual space, such as natural or real numbers, RGB values etc.

**Comment by azaroth42** [comment]
Agreed. I think [aat:300056130](http://vocab.getty.edu/aat/300056130) is the `classified_as` for the Dimension?

**Comment by workergnome** [comment]
I'm in agreement RE:color—What about units?

**Comment by azaroth42** [comment]
Good question! What about:

```
{
  "type": "Dimension",
  "classified_as": "aat:300056130",  // color
  "value": "FFFFFF", // white
  "unit": {
    "id": "aat:300266239", // RGB
    "type": "DimensionUnit"
  }
}
```

**Comment by workergnome** [comment]
I'm OK with that, but I'd also be OK if there's a standard RDF vocab for colorspaces.  See also the discussion of QUDT vs AAT for physical dimensions. 

(I think this is really solved via crosswalks.)

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-1cf47ad0764a411fbae8b9ad778e3677/page-1)

**Comment by azaroth42** [comment]
Discussion on slack:  Defer color until there is data available that can support it. Use Cases über alles.

**Comment by Conal-Tuohy** [comment]
Re use cases, Lev Manovich, for instance, has done some interesting work in the area.

Personally I like the example above of a 6-character hexbinary literal representing RGB byte values.
