### ISSUE TITLE
some web site suggested edits from Kevin

### ISSUE THREAD

**Issue by beaudet** [linked-art/linked.art#714]
Some of the page titles in the chapters are different to the ToC text entry, which is a bit confusing if you don't know they're synonymous
e.g. 'Core Entity'/'Entity Descriptions' on ToC, 'Linked Art API Endpoints' on detail page (Endpoint is better)

Also, next chapter buttons might be helpful when cycling through information.

**Comment by azaroth42** [comment]
Fixed title consistency. Up/Next/Prev links are hard, but likely fixable via the materials scheme menus
