### ISSUE TITLE
Move (some) vocabs to cookbook?

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#72]
The current layout has a half formed "vocabularies" page that lists some of the terms that have been useful, but certainly not all, and there are doubtless ones on the list that shouldn't be there.  The ones that are referenced in the examples (but not the text) are linked in the index.

So... without recreating AAT, what's the right approach for suggesting useful, common terms associated with a CIDOC-CRM class?  Perhaps per-project lists are in the cookbook, and common ones are listed on the vocabularies page? But which ones make it out of the cookbook?

We could start some sort of spreadsheet of term+class to project/dataset and note which terms are used in which data -- if a term is in the majority of datasets, then it's automatically listed? Seems heavyweight but fair... lighter weight would be just best judgement as we see them and manually update?

**Comment by workergnome** [comment]
I think the vocabulary terms that are required to express concepts that we've chosen, like the `provenance` or the `preferred_terms` should be listed.  These are the ones that MUST be used to maintain compatibility.  I think that if specific implementations (AAC, Getty, Art Tracks, Nomisma) use additional terms, that's appropriate at the cookbook level.  

I think there's definitely also utility in providing a limited subset of top-level categories from AAT, but my preference would be to have that attached to a software project that implements functionality that requires them—or have it be outside Linked Art?

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-078d4c183ca5496ab1d434d5dbb3f574/page-1)

**Comment by azaroth42** [comment]
Current progress: http://vocabs--linked-art.netlify.com/community/best-practices/vocabularies/

**Comment by azaroth42** [comment]
Merged the vocabs branch, so closing the issue. Any further enhancements can be discussed in new issues :)
