### ISSUE TITLE
Make slack /mark response a link to the issue

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#73]
If we can figure out how to get the response to render markdown or html, rather than just raw text.

**Comment by azaroth42** [comment]
Possibly:  https://api.slack.com/docs/message-formatting#linking_to_urls ?

**Comment by workergnome** [comment]
Yah—looks like you can't make text a link, but you can put a URL in text and it'll become a link.

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-9a54a08001b348beb108f372c9f7032e/page-1)

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-7227a865ea294bc09b8006153d941cbf/page-1)

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-0e950f3d1f5a4178a73037fb5559db51/page-1)

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-df4adc57acb346b4be3c58fb327719b0/page-1)

**Comment by azaroth42** [comment]
Done (after some PEBKAC bugfixing)
