### ISSUE TITLE
Specify how Statements are composed by (or referred to by) Documents

### ISSUE THREAD

**Issue by mdlincoln** [linked-art/linked.art#80]
http://linked.art/model/base/#statements-about-a-resource

**Comment by mdlincoln** [comment]
Homework for @azaroth42 after 2017-08-02 meeting

**Comment by azaroth42** [comment]
Noting (somewhat for self) that we have the beginning of this:  http://linked.art/model/provenance/auctions/#auction-catalog 

But really the issue is:  Write the documentation for bibliographic sources.

**Comment by workergnome** [comment]
Putting these here so I don't lose them, as references as we work on this:

http://www.bl.uk/bibliographic/pdfs/bldatamodelbook.pdf

in the context of http://bnb.data.bl.uk, which is "The BNB Linked Data Platform provides access to the British National Bibliography published as linked open data and made available through SPARQL services.”

Also relevant: http://opencitations.net

**Comment by mdlincoln** [comment]
Checking in on the progress of this specification? We could use some guidance on how LinguisticObjects like [materials statements](http://linked.art/model/object/physical/#materials-statement) or [attribute assignments](http://linked.art/model/assertion/#assignment-of-attributes) should be connected to documents and to the entities (people, objects, events) they reference.

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-ec2b2256540d4755a4a93c0968c61154/page-1)
