### ISSUE TITLE
exhibition catalog number

### ISSUE THREAD

**Issue by VladimirAlexiev** [linked-art/linked.art#86]
http://linked.art/model/exhibition/#exhibition-specific-labels describes per-object exhibition labels.
But another important attribute is not mapped: exhibition catalog number.
Eg Getty Museum's TMS has a field exhvenuexrefid.catalognumber.

The picture below models it as "identifier of the event that represents object's participation in the exhibition" but I'm not happy about it.
![exhibitions](https://user-images.githubusercontent.com/536250/29660891-2458ce4a-88cb-11e7-9691-e430db957259.png)

Following exhibition labels, it could be modeled as an Identifier Assignment (or Attribute Assignment) activity that's part of the Exhibition (or has specific purpose the Exhibition).
I think we should also model the exhibition catalog itself: a Document classified as aat:300026096 "exhibition catalog". And then the Identifier Assignment is also part of the Creation of that catalog?

**Comment by mdlincoln** [comment]
From my POV as a reader of exhibition catalogs, this would put exhibition catalog numbers in a counterintuitive place in the graph.

I tend to conceive of and use/cite exhibition catalog entries as scholarly units (information objects?). The catalog numbers are thus _meaningful identifiers for those entries_. Such numbers are rarely, if ever, considered identifiers for or attributes of the objects themselves. This is distinct from the way that a title/label assigned in the context of an exhibition would be considered an attribute of the object.

(This is not to be confused with _catalogue raisonné_ numbers, which absolutely are used as identifiers for MMOs)

**Comment by workergnome** [comment]
Huh.  I know at CMOA, we think of the catalog number as an ID for the object in the context of, say, the Northbrook catalog, which is more like an inventory than a exhibition catalog.

**Comment by azaroth42** [comment]
We have two patterns already that cover the two scenarios:

If the identifier is treated as a previous, no-longer valid but interesting identifier of the object, then it is still an identifier of the object.  This is the ["legacy identifiers" pattern](http://linked.art/model/object/identity/#context-for-legacy-identifiers) where the identifier comes from an Information Object representing the set of identifiers associated with a Collection (or in this case, with an Exhibition).

If the identifier should be treated as a context specific property that would be just incorrect to assert in a broader scope, then we have the attribute assignment pattern to ensure that it is kept as an activity within a context, such as the [exhibition label](http://linked.art/model/exhibition/#exhibition-specific-labels), or [previous title](http://linked.art/model/assertion/#assignment-of-attributes)

**Comment by mdlincoln** [comment]
Indeed - though that sounds like a _collection catalog_ rather than an _exhibition catalog_?

**Comment by VladimirAlexiev** [comment]
Exhibition catalogs and collection catalogs are Documents. (If you have deprecated this class in  favor of InformationObject, you should not because you need to distinguish between its children LinguisticObject and Document).

@mdlincoln Catalogs are indeed made of entries (sub-Documents), so you can consider that catalog numbers are Identifiers for those entries. 

@azaroth42 Your example shows that Identifiers form part of catalogs ("composed_from" is a wrong name for P106i, you got it backwards). But this eschews Entries, which are the real intellectual content of catalogs. 

In any case we must make a strong connection between the Entry, Object (the entry is about that object and nothing else!) and Exhibition (that motivated the creation of the whole exhibition catalog). 

I like to think of those identifiers as Identifiers of the object: which were IdentifierAssignment'ed in the context of the Exhibition. If I have the catalog in hand, I may like to search by the printed identifier, and should like to find the object (and perhaps others irrelevant objects), without having to first find the catalog.

PS: It would be a lot easier to discuss these things if we can see them as pictures, don't you agree? We automate making turtle and rdfpuml diagrams for each example.

**Comment by VladimirAlexiev** [comment]
@mdlincoln Why do you consider exhibition labels so different from exhibition catalog numbers? Can you elaborate?

**Comment by VladimirAlexiev** [comment]
Here's a "programme maximum" graph.
![exhibition2](https://user-images.githubusercontent.com/536250/29709496-3463748c-8995-11e7-955c-c814b2abe636.png)

- It represents both "E"vents (catalog creation, number and label assignment) and the resulting "C"onceptual objects (catalog, entry, number, label). (the sole "P"hysical object is the Object itself)
- It has lots of redundant arrows. Our task is to select a minimal set of reasonable arrows
- (I've used P20i rather than P20 just to collect the labels of P20i and P9 on one arrow and not clutter the diagram. I have no preference for the direction of P20)

Would you like to cross-out arrows you don't like?

**Comment by VladimirAlexiev** [comment]
@azaroth42 to avoid hasty closure as in #85: above I have used the most specific CRM props, but that's not the point (i.e. I'm ok to use P1 instead of P102 etc). The point is what is the shape of the graph.

**Comment by mdlincoln** [comment]
@VladimirAlexiev my only concern was that I'd expect to find catalog numbers attached to catalog entries, not _only_ to objects. However, I've no problem with them being attached to both.

**Comment by azaroth42** [comment]
What is the _actual_ issue? That we don't have a description of the catalog itself? If so, yes, that's the next area to document, the "Primary Sources of Information" link under model/

**Comment by VladimirAlexiev** [comment]
@azaroth42: would you please fix this: 
> "composed_from" is a wrong name for P106i, you got it backwards

We're discussing what's the most reasonable way to represent catalog numbers, which are valuable identifiers (of object and/or catalog entry)

**Comment by azaroth42** [comment]
P106 is from the parent to the child, and we keep the name `composed_of`.  We can't use `forms_part_of` for P106i, as there's other "part of" properties.  To keep the inverse consistent in naming, `composed_from` was the best we came up with. 

All of these should really just be `part` / `part_of` ... but until we get JSON-LD 1.1, we're stuck with coming up with new unique names. We could instead use `decomposed_from` if that's more obvious?

The context says:
```
"composed_of":
{
"@id": "crm:P106_is_composed_of",
"@type": "@id",
"@container": "@set"
},
"composed_from": {
"@id": "crm:P106i_forms_part_of",
"@type": "@id",
"@container": "@set"
}
```

**Comment by VladimirAlexiev** [comment]
@azaroth42:
- "house composed of brick" is meaningful
- imho both "brick composed from house" and "brick decomposed from house" are not meaningful. ("flesh decomposed from body" is meaningful, but that's a different kind of meronym: substance rather than part. Wordnet distinguishes between three kinds of meronyms: member, part, substance; and Mereology considers even more cases.)
- **please use "brick component_of house"**

Diagram
- Could you please erase the prop names and nodes that you don't like?

**Comment by azaroth42** [comment]
P106 is about symbolic objects rather than physical, but sure, `component_of` isn't already used in the context and composed/component are memorably similar.

We'll get to documents in due course :)

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-27fe510c3f78478481137cac7968a337/page-1)

**Comment by azaroth42** [comment]
Actually `component_of` __is__ used -- it's P148i, and doesn't need an override as that's the real CRM name of the predicate.  So ... `composed_out_of` ?

**Comment by azaroth42** [comment]
includes / included_in is the new composed_of / composed_from.
(And then had to change the mapping for a bunch of other predicates, but not ones in our profile)

Closing.
