### ISSUE TITLE
homepage vs. page

### ISSUE THREAD

**Issue by workergnome** [linked-art/linked.art#9]
In the http://linked.art/model/object/digital/#web-page section, do we need to make a distinction between various types of webpages?  `foaf:page` vs `foaf:homepage`?

**Comment by workergnome** [comment]
(And is this the same discussion as `about` vs. `references`?

**Comment by azaroth42** [comment]
What's the use case for page separate from homepage?  Link to some resource on the web that has some relationship to the object, but doesn't actually describe it? I'm less convinced that's useful to anyone?

**Comment by workergnome** [comment]
Take, for instance, this page about [Peter Kubelka](http://records.cmoa.org/parties/a8abb812-c11c-400d-89ec-33e4e0c3d05d/)

For the entity, I'd want that URL to be the homepage for the Person, but I'd also want to link to their IMBD record, and their wikipedia page, and their personal homepage.

Are they all home pages?  They're all "about" him, but only one is the official HTML page for the entity.

**Comment by azaroth42** [comment]
Could web pages just be Information Objects that refer to / have subject of the entity? And then keep homepage for the selected/preferred HTML representation?

**Comment by workergnome** [comment]
If we're going to do that, shouldn't we do it for homepage, too, with perhaps the ability to use `foaf:homepage` as a shortcut?

We could also just go to the standard aat:website & aat:preferred_term model at that point...

**Comment by azaroth42** [comment]
Discussion on slack led to:

```
{
  "id": "uri-of-thing",
  "type": "ManMadeObject",
  "subject_of": 
  {
    "id": "uri-of-page",
    "type": "InformationObject",
    "classified_as": ["aat:preferred", "aat:webpage"],
    "label": "title of page",
    "format": "text/html",
  }
}
```

With the potential for foaf:homepage as a shortcut (at the API level) to the preferred webpage which has subject of the resource.

**Comment by azaroth42** [comment]
For non homepage, is it `subject_of` or `referred_to_by` ?
