### ISSUE TITLE
add a prefix and base to turtle

### ISSUE THREAD

**Issue by VladimirAlexiev** [linked-art/linked.art#92]
https://linked.art/example/object/16.ttl is nice, but please:
- add `@prefix aat:`
- add `@base <https://linked.art/example/>`

**Comment by azaroth42** [comment]
I did this but rdflib doesn't produce more readable output.  

e.g.
```
@prefix aat: <http://vocab.getty.edu/aat/> .
@prefix crm: <http://www.cidoc-crm.org/cidoc-crm/> .
[...]

<object/11> a crm:E22_Man-Made_Object ;
    rdfs:label "Simple Example Painting" ;
    crm:P2_has_type <http://vocab.getty.edu/aat/300033618>,
        <http://vocab.getty.edu/aat/300133025> .
```

Note, the base just sets the relative URI, but doesn't add `@base`. And adding aat as a prefix doesn't change the output for the URIs as subjects.

Tagging as blocked.

**Comment by VladimirAlexiev** [comment]
> base just sets the relative URI, but doesn't add `@base`

That's a common problem, eg see also https://github.com/kasei/perlrdf/issues/131 (split from https://github.com/kasei/perlrdf/issues/130#issuecomment-135950524)

> aat as a prefix doesn't change the output for the URIs as subjects

That's a peculiarity of rdflib. Jena RIOT shortens them.

**Comment by azaroth42** [comment]
Closing. Having the full dereferencable URI is valuable for consumers in the JSON, so keeping the turtle in sync with the instance URIs is probably okay.
