### ISSUE TITLE
References to external resources should be consistent

### ISSUE THREAD

**Issue by VladimirAlexiev** [linked-art/linked.art#93]
https://linked.art/example/object/16.json has labels for 2 AAT concepts but is missing labels for 3 more. (The labels are shown in the tooltips of all 5 concepts.)
- Is this by design?
- Is it reflected in the JSONLD context?

If it is by design, can we have a global list of AAT labels for the purpose of image making?

**Comment by azaroth42** [comment]
If the aat concept is used as an identifier for a class other than Type (e.g. for MeasurementUnit, Material, Currency or Language) then I include a label.  If it's just as a classification via `classified_as` then I don't.  This has just been a convention (give everything a label and a type, other than classifications).

We can formalize that as a requirement of the model?

**Comment by VladimirAlexiev** [comment]
All labels will be needed in a deployed repo so it can display stuff reasonably.
Would be better to include them all in examples also, so all labels can be displayed in the example.

(You're right about Context, I mistook it for Frame capabilities)

**Comment by azaroth42** [comment]
An example by value (as the by reference above is now out of date):
```
{
  "id": "https://linked.art/example/object/45", 
  "type": "ManMadeObject", 
  "label": "Example Marble Sculpture", 
  "classified_as": ["aat:300047090","aat:300133025"], 
  "made_of": [{"id": "aat:300011443","type": "Material","label": "marble"}]
}
```

The question is: Should the `Material` be just "aat:3000011443" or should 'sculpture' and 'work of art' be expanded to include `type` and `label`?

My current feeling is that with the upcoming availability of the improved AAT API, plus the listings at http://linked.art/community/best-practices/vocabularies/, the non-Type types could be reduced just to the URI.

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-20bf67d924744d6db63acbf12adc9c6f/page-1)

**Comment by azaroth42** [comment]
Decision from Jan 12 was to have id, type and label for all resources, including AAT concepts used for classification.

**Comment by azaroth42** [comment]
Reaffirmed and expanded consensus that:

* All resources MUST have `id` and `type`, and external (to the document) referenced resources SHOULD have a `label` (including Types).
* Resources MUST either be id/type/[label] or the complete representation. We do not want to optimize the exact set of fields per class, per referencing clas.

The convincing situation is `referred_to_by` with linguistic objects. Some LOs are embedded statements (and hence need to be objects, with at least id, type, value). Some LOs are external references (e.g. to a text of a book that refers to the object). If external references were just the URI, then we would have mixed data type arrays and we want to avoid that inconsistency.
