### ISSUE TITLE
add drop-down menu

### ISSUE THREAD

**Issue by VladimirAlexiev** [linked-art/linked.art#96]
Would be great to have a 2-3 level drop-down menu. Eg to get to http://linked.art/model/object/identity/#titles, I need to click 4 times from Model.

**Comment by azaroth42** [comment]
PRs welcome on this one. A markdown parser could generate it automatically from the content structure, but keeping it up to date by hand would be a nightmare.  Tagging `defer` until someone is able to take it on.

**Comment by azaroth42** [comment]
Anyone willing to do this, otherwise propose close

**Comment by azaroth42** [comment]
No objections to closing.
