### ISSUE TITLE
add Title Type

### ISSUE THREAD

**Issue by VladimirAlexiev** [linked-art/linked.art#97]
Currently you distinguish only title preferredness (http://linked.art/model/object/identity/#primary-title vs http://linked.art/model/object/identity/#alternate-titles) but not the nature of the title.
- CCO sec 1.2.2.2.3 describes various kinds of titles.
- http://www.getty.edu/research/tools/vocabularies/guidelines/cona_3_3_terms_names.html#3_3_2_5_5 describes various kinds of titles
- https://share.getty.edu/display/ITSLODV/CONA+Titles takes into account all title attributes, including sources and contributors.

We need to standardize at least these types as AAT concepts: Artist, Repository, Descriptive, Inscribed, Exhibition.

**Comment by azaroth42** [comment]
If there are the AAT concepts for these, and we'll add them to the vocabulary list.

**Comment by VladimirAlexiev** [comment]
Posted https://jira.getty.edu/browse/ITSLOD-527 to Patricia.

Since that jira is closed, I reproduce the example value lists:
- CCO states "A repeatable controlled field should be used for Title Type" and sec 1.2.2.2.3 describes various kinds of titles, at least:
Owner’s , Creator’s , Inscribed , Descriptive, Numbered, Translation, Former, Constructed
- CONA describes more kinds: http://www.getty.edu/research/tools/vocabularies/guidelines/cona_3_3_terms_names.html#3_3_2_5_5 
Descriptive , Artist's , Repository , Inscribed , Popular , Collective , Collective title as non-preferred, Titles for multiple-part works, Titles for groups, Spelling variants, Historical titles, Misspellings, Archival spellings
- CONA field term.other_flags has these values: 
abbreviated, address, artist's, brand name, brief title, code, collection, collective, constructed, descriptive, exhibition, former, full title, group, inscribed, manuscript designation, original, popular, published, repository, series, subgroup, title statement, translated, volume
- we'd like to add Exhibition (exhibition label)

**Comment by VladimirAlexiev** [comment]
https://github.com/american-art/autry/issues/62 describes a particular sort of Constructed title: Object Name (i.e. object type). Example: "Bulto", "Carving"

**Comment by azaroth42** [comment]
Closing in favor of smaller issues as they come up. A better process, to avoid LONG lists of never used vocabulary terms, is to tackle issues from data and find the appropriate AAT term at the time. Then these can be documented as examples.
