### ISSUE TITLE
work out all of CCO

### ISSUE THREAD

**Issue by VladimirAlexiev** [linked-art/linked.art#98]
I consider CCO the bible when it comes to museum data. It elaborates such data systematically and gives excellent examples.
Like https://share.getty.edu/display/ITSLODV/CONA, I think linked.art should work out CCO systematically so it doesn't omit something important.
You can get CCO as PDF parts from http://cco.vrafoundation.org/index.php/toolkit/cco_pdf_version/, or a concatenated version from http://personal.sirma.bg/vladimir/cco/

**Comment by azaroth42** [comment]
That's not how we work.  As per the design principles, we work from actual data and actual use cases.

**Comment by workergnome** [comment]
This is definitely how the review site for the American Art collaborative was written, trying to make it through all of the required CCO fields.  I could imagine an appendix, that links examples in Linked Art to CCO fields for museum folk—but I agree that exhaustively solving all of CCO is less useful than solving them as specific data and use case examples crop up against them.

**Comment by azaroth42** [comment]
Similarly, CIDOC-CRM with all of its extensions was not made completely from thin air. They would argue it also codifies actual examples.  Doesn't mean we need to accept all of the ontology, either.
