### ISSUE TITLE
Collection vs Complex Object

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#99]
As part of the features discussion, the use of E19 as a Collection of Objects came up and the ability to infer information based on parts.

There seems to be a continuum from something that is clearly an object through to something that is clearly a collection, but no clarity as to where to draw the line in the middle.

* A shaped block of wood or metal (a table carved from a single piece of wood)
* Permanently connected blocks of wood and/or metal (a table made from multiple pieces of wood)
* Connected blocks of wood and/or metal with non-removable but movable parts (desk with drawers)
* Connected wood/metal with removable but integral parts (desk with drawers, that come out)
* The desk, with a key that unlocks the drawers.
* The desk, with a key, and a pad of paper on the top from the original time period.
* Three such desks, created at the same time, designed to be used together, with carved tops with related images that connect together. 
* Same desks without the carved tops, and could be swapped out with others without "looking wrong"
* Similar desks, that could be used together, but weren't created at the same time or by the same artist
* 3 desks displayed together from different time periods
* The collection of the dec arts department.

Without reading the comments, think about where you would draw the line between Object with parts and Collection of Objects.

**Comment by azaroth42** [comment]
...

And I think that the key is a separate object from the desk whereas the drawers are not. The key makes sense as a thing without the context of the desk, whereas the drawers do not.  However the key would never be accessioned separately from the desk.

**Comment by workergnome** [comment]
And to be _more_ abstract:

* Desks that I have owned
* Desks that I have used
* Desks that I like

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-5fe952ea7ac0471c94812dc3c7eecffe/page-1)

**Comment by azaroth42** [comment]
Affects http://linked.art/model/provenance/auctions/#set-of-objects and (importantly) the relationship from the sale of the lot to the set.

**Comment by azaroth42** [comment]
@workergnome and @azaroth42 think that ore:Aggregations would make a good non-specific pattern for various types of Collection. That would clearly separate "thing" from "set".

Related to #124 (and might even just solve it)

**Comment by azaroth42** [comment]
Further discussion:  We think Aggregation does solve it, and that it fits into CRM as a subClassOf E28_Conceptual_Object

Making it so.

**Comment by Conal-Tuohy** [comment]
Is this one of those cases where Linked Art will need to coin a new sub-class to unify `ore:aggregation` and `crm:E28_Conceptual_Object`?

**Comment by workergnome** [comment]
I believe so. Open to suggestions for naming—ConceptualAggregation is correct, but a mouthful!

**Comment by azaroth42** [comment]
azaroth42 marks this issue as being discussed in [slack](https://linked-art.slackarchive.io/-/search-77fdf02e0a4545cbaad87e4c9f6d2c82/page-1)

**Comment by azaroth42** [comment]
I think just `la:Aggregation` ... the only requirement for the class is that we don't want multiple instantiation, and we don't want to make assertions about other people's classes... but we're not going to add new non-aggregation-like features.

**Comment by ajs6f** [comment]
> think about where you would draw the line between Object with parts and Collection of Objects.

Coming in super-late to this conversation (and probably missing or misunderstanding a bunch, as usual) but whence came the assumption that one pattern will suffice for all aggreagate-y, collection-ish, set-esque instances? I understand that fewer constructs makes for simpler data and code, but some of the examples seem "extensive" and some seem "intensive" and using the same construct for both seems like a bad foundational practice. Just my 2¢…

**Comment by workergnome** [comment]
I think what we're addressing is that there are many ways to create sets, and CRM provides only a couple of them: 

* partitioning (many possible ways)
* Group joining/leaving (only works for people)
* Curated Holding (a very, very specific subset of ways to assemble objects)

Our opinion is that partitioning is a very powerful mechanism, but it mostly works for things where you want some level of inheritance between the thing and its parts, where the thing and its parts are of the same type, and it is seems most useful when it's 1-many, not many-many.  For example, events can be exploded into sub-events, and objects into sub-objects, but it's hard to think about an exhibition, for instance, as being partitioned into objects.

The next form of partitioning that we're interested in are "groupings".  Which is to say, collections of entities that an agent has, for some reason or another, decided are related in some way or another.  Within the bounds of this grouping, there may be objects of different types, and there is both per-entity and global metadata about the grouping.

An exhibition is a good example of this--a human has said that "this collection of objects are to be exhibited in my show 'Ugly Babies of the Renascence'.  Within the exhibition, they've each been given an exhibition number and a wall chat, and the grouping as a whole is related to the event of the exhibition".  

This is not a partioning, it's just a collection of objects.  You could potentially describe these with a very dense set of events that describe the actions that a human took to produce the exhibition, but we feel that there's a need for a pattern to describe this grouping not as a "real, object-based" thing, but as a conceptual grouping of entities.

Thus, the grouping is a `E28_Conceptual_Object`.  However, that doesn't give us a mechanism to actually associate the objects with them, nor assign group-specific metadata.  We could mint properties for that, but `ore:Aggregation` has properties that match up nicely, and are already defined and in use.

These are certainly not the only types of aggregations needed--for instance, neither of them will work in the "Work->Edition->Instance" case very well.  But the `la:Aggregation` gives us a way to talk about, say "the history of ownership of an object" as a series of events without minting a Activity that is not actually carrying out any  state changes, or to talk about an exhibition without pretending that there's a Physical Object that is the collection of works in the exhibition.

**Comment by Conal-Tuohy** [comment]
So long as people aren't intending to add CRM properties to ORE Proxies, I'm all good with this. But I don't see what ORE Aggregations add to your toolbox when dealing with sets of physical objects (e.g. the objects in an exhibition). Can anyone enlighten me? It seems to me that the objects of an exhibition can be treated quite naturally as a compound object brought together for the event. I think where it really is useful is when

**Comment by azaroth42** [comment]
To me, after discussions with @workergnome, the test is whether or not the object can be "part of" multiple parents or not.  The canvas of a painting is only part of the painting (at any one time, barring exceptional circumstances like a different painting on the other side).  But it can easily be part of many many aggregations, that group the painting with other resources.

The painting can't be part of multiple exhibitions at the same time (assuming they're physical, not digital) but to use the same predicate would make it difficult to distinguish between the canvas which is physically part of the painting MMO, rather than the MMO which is grouped together, currently physically, within the set of objects that make up the exhibition.

If there were different parts of the exhibition that could be separated, then the exhibition would consist of parts, that then had the MMO as parts, that then had parts as parts ... these partitionings seem different to me.

**Comment by Conal-Tuohy** [comment]
To me it would make sense to distinguish the different types of composite objects by type of object (e.g. an "exhibition set") rather than the mereological predicate but I would need to think about that some more.

**Comment by Conal-Tuohy** [comment]
It seems to me that many composite objects which are treated by museums as first-class objects in their own right (rather than "collections" or groupings brought together for exhibition) are, in a purely physical sense, no different to composites which have been brought together merely for exhibition. For example, a set of objects (such as a desk, pen, and ink-well) belonging to an historical individual may be treated as a composite object, even though they have been produced in different places at quite different dates; they belong together because that historical individual brought them together, and they now have that shared provenance. Whereas another similar set of desk, pen, and ink-well may be physically virtually identical, but have been brought together by an exhibition curator. From a mereological point of view, these two composite objects are the same (i.e. the physical relationships between the wholes and their parts are the same for both sets of writing implements). What actually distinguishes the two cases is the different historical facts around the assembly processes.

**Comment by azaroth42** [comment]
Agree that "exhibition set" is a good sort of thing to distinguish, but it should be done with P2 not as many little classes, for consistency. Thus we need the conceptual grouping class (Aggregation) which is then classified as auction lot, or exhibition set, collector's holdings, or permanent-arrangement-of-objects-for-display.

I also agree that semantically there's almost no distinction between an exhibition of a desk, a pen and an ink-well that happen to be owned by different organizations and normally are physically separate, and the presentation in a permanent collection of a desk, pen and ink-well that are cataloged as a single object.  If each of the objects has its own identity (and they should), then I would prefer to always use membership semantics, rather than the partitioning semantics.  However, pragmatically, if the catalog asserts a materials statement of "desk, oak with inlaid gold; ink-well, ceramic" then we're not going to be able to pull them apart algorithmically. When cataloging is natively happening in LO[U]D then we should insist on the right predicates ... until then it seems like an ignorable inconsistency.

**Comment by Conal-Tuohy** [comment]
@azaroth42 I'm trying to follow this but having real difficulty :-( Please bear with me.

> Agree that "exhibition set" is a good sort of thing to distinguish, but it should be done with P2 not as many little classes, for consistency. 

My suggestion was indeed to use "exhibition set" as (the label of) the value of a `P2_has_type` property of a set of objects brought together for exhibition. But I don't understand what you are referring to by the comment "not as many little classes". What classes are you talking about there?

So I still don't understand why you say  "thus we need the conceptual grouping ..." (i.e. I don't understand the premise, so the "thus" doesn't seem to follow).

Can you clarify also what you mean by the distinction between "membership semantics" and "partitioning semantics".

Regarding the grouping of objects that have been catalogued or registered as a unit; in some cases, the objects which are parts of the whole will already have been registered as units in a collection management system, and the whole will also be registered as a unit. But otherwise, I certainly agree it's not a good idea to attempt to pull them apart into their constituent objects, and I wasn't suggesting doing that, myself. Again, I haven't really grasped what point it is that you are making there.

**Comment by azaroth42** [comment]
Let's start from the other end with a concrete example to discuss :)

I think that this set:
    http://linked.art/model/provenance/auctions.html#set-of-objects

should be an ore:Aggregation, rather than a crm:Physical_Object.

:+1: or :-1: ?

**Comment by Conal-Tuohy** [comment]
I would vote 👎 and ask why not a physical object (the lot) that consists of those objects?

**Comment by azaroth42** [comment]
Because it's not an object, it's a set of objects. Those same objects are part of many other sets at the same time (e.g. the collection they're part of, or the favorite objects of the owner, or ...)

They're collected together for a specific purpose (sale by auction) but might otherwise share no other features. The Lot could be put together by the auction house, for example.
Consider:  http://www.sothebys.com/en/auctions/ecatalogue/2018/important-americana-n09805/lot.643.html -- Six random brass boxes, plus a tobacco tin.

I agree that it _could_ be a E19, in that it's a "unit for documentation" and an "aggregate of objects made for a functional purpose" ... but a box being part of this set versus the front of the box being part of the box seems very different to me.  The identity of the front of the box only makes sense in the context of the box ... otherwise it's just a piece of brass. The identity of each box in the auction lot is entirely independent of it being in that auction lot.

(That E78s are not E19s is still an unfathomable mystery to me!)

**Comment by azaroth42** [comment]
Or another way ... the features of the members do not necessarily add up to the features of the set.  I think it would be very strange to say:  "The Auction Lot is made of (P45_consists_of) Brass and Tin". whereas the materials of parts of objects do inform the material of the object.  "The desk is made of pine, oak, iron and gold" makes sense, even when there is only gold inlaid on the oak top, and the legs are made of pine and iron.

**Comment by Conal-Tuohy** [comment]
Well this is why I mentioned the example of a desk, inkwell, and pen, which had been registered in a content management system as a Physical Object (a composite). The point of that example was to illustrate that there are groupings of objects which curators _do_ consider as _an object_, but which are just as must _sets of objects_ as the objects found e.g. in an exhibition set. You might well say that it would be odd to say that the "office equipment" grouping above `P45_consists_of` "ink, glass, silver, brass, and wood", and I'd agree it is a bit odd. But it's not relevant to the question of whether the "office equipment" is a "Physical Object". What makes it a physical object is that its parts have brought together for some purpose, and in _that_ sense, it doesn't differ from the auction lot, it seems to me. What is different is only what the specific purpose was.

**Comment by Conal-Tuohy** [comment]
e.g. I think this describes the situation just as well as (better, even) than Aggregation, and it also has the advantage that it does so in native CRM terms:

```json
{
  "@context": "https://linked.art/ns/v1/linked-art.json", 
  "id": "https://linked.art/example/set/68", 
  "type": "PhysicalObject", 
  "label": "Set of Objects for Lot 812", 
  "identified_by": [
    {
      "id": "https://linked.art/example/identifier/9", 
      "type": "Identifier", 
      "value": "812", 
      "classified_as": ["aat:300404628"]
    }
  ], 
  "classified_as": ["aat:300411307"], 
  "consists_of": [
    {
      "id": "https://linked.art/example/object/69", 
      "type": "ManMadeObject", 
      "label": "Example Painting", 
      "classified_as": ["aat:300033618","aat:300133025"]
    }
  ]
}
```

**Comment by azaroth42** [comment]
> The point of that example was to illustrate that there are groupings of objects which curators do consider as an object, but which are just as must sets of objects as the objects found e.g. in an exhibition set. 

I agree ... but IMO this is the curators having only one tool to use in their collection management system, and thus using it, rather than that they believe it's a single object.  Curators (at least ours!) also accession individual pages into the CMS separately from the bound volume they're part of as completely separate objects, because that's the tool they have.  If we had a better CMS (one that understood LOUD natively, for example) then I wouldn't want to persist the pattern. 

Not sure how to break this stalemate.

**Comment by Conal-Tuohy** [comment]
Well, the curators' view (that objects can have parts, and still be considered objects themselves) is not going to go away; it actually makes a lot of sense to them (and to me, incidentally). It's also a common sense view that objects are made out of other objects, for a variety of purposes (of which sale and purchase is just one among an infinite number). _And_ critically,, it's the conception of "Physical Object" that's expressed in the CIDOC CRM, to wit: 

> This class comprises items of a material nature that are units for documentation and have physical boundaries that separate them completely in an objective way from other objects. 
>  The class also includes all aggregates of objects made for functional purposes of whatever kind, independent of physical coherence, such as a set of chessmen. Typically, instances of E19 Physical Object can be moved (if not too heavy).
>  In some contexts, such objects, except for aggregates, are also called “bona fide objects” (Smith & Varzi, 2000, pp.401-420), i.e. naturally defined objects. 
>  The decision as to what is documented as a complete item, rather than by its parts or components, may be a purely administrative decision or may be a result of the order in which the item was acquired.

 I don't understand what's to be gained by swimming against that particular current? What, practically and concretely, will Aggregation actually do, that a composite Physical Object will not?

**Comment by azaroth42** [comment]
The advantages as I see them:

* The semantic separation of parts (cardinality 1:*) from members (cardinality *:*). My understanding is that you don't think this is a real distinction.  e.g. that there's no difference between the relationship of a frame to a painting, than the relationship of the painting to its collections.  Or a page to the document, and the document to the archival hierarchies that it's part of.

* The semantic clarity between a MMO and an intellectual Set. MMO and Physical Object are both descendants of E18 Physical Thing, the domain of P46 ...

> This class [E18] comprises all persistent physical items with a relatively stable form ...

I don't believe that an intellectual grouping has a relatively stable form. Hence the notion of "aggregates of objects being also E18 is perplexing to me, and I think that E19 being used for aggregations is semantically invalid.  

> This class [E19] comprises items of a material nature that are units for documentation and have physical boundaries that separate them completely in an objective way from other objects.

Similarly there is no objective way to distinguish the physical boundary of an intellectual set. I do not believe that an intellectual set is an item of "a material nature".  There is no natural boundary to the set, and it can change form at any time through an act of cognition (and thereafter recorded through documentation so we know what happened).

* The consistency of all types of sets being a single class, with P2 to distinguish between uses.  A collection of objects, a collection of people, a collection of concepts, a collection of intellectual works, a collection of places, ... all could be Aggregations.  Currently we use Group for a set of Actors, Physical Object for a set of physical things, Information Object for a set of Conceptual Objects, and I guess would use symbolic object for a group of symbolic objects... but Information Object is also a symbolic object so we could smush them together.  E2s must be contiguous, but E92 allows for composition of non-contiguous parts, so a set of Periods/Events/Activities would be a SpacetimeVolume.  I expect a set of Places is itself a Place (otherwise New Zealand is not a Place as its boundaries include the Chathams with international waters in between ... the scope notes are unsurprisingly unclear).

**Comment by Conal-Tuohy** [comment]
> The semantic separation of parts (cardinality 1:*) from members (cardinality :). 

Typo? Did you mean to counterpose one-to-many vs many-to-many?

> My understanding is that you don't think this is a real distinction. e.g. that there's no difference between the relationship of a frame to a painting, than the relationship of the painting to its collections. Or a page to the document, and the document to the archival hierarchies that it's part of.

It's not that I think there's no difference between the relationship of a frame to a painting vs the relationship of a painting to a set of paintings. That's not my view. On the one hand, a frame is physically bound to the painting of which it's part; they form a solid, contiguous, object. And on the other hand, a group of paintings are not physically attached to each other; they can be moved relative to each other. So the relationships clearly _are_ different. My view, though, is that those differences are orthogonal to the whole-part relationship (i.e. my view is that the physical connectedness of two objects is not relevant to the question of whether they have a whole/part relationship). 

The CRM is very clear on this: the `P46 is composed of` property is explicitly described as many-to-many, and the `E19 Physical Object` class "includes all aggregates of objects made for functional purposes of whatever kind, **independent of physical coherence**" (emphasis mine)

**Comment by Conal-Tuohy** [comment]
BTW I totally agree about using Aggregation for intellectual sets (i.e. as a sub-type of Conceptual Object). It is only for describing (composite) physical objects where I think it's not the best treatment. And for instance, I see an auction lot as a physical object (it's the objects themselves that are for sale, not a conceptualization of the objects)

**Comment by azaroth42** [comment]
LOL, yes, cardinality \*:\* Should have looked at the preview first (or realized that the *s would be interpreted as markdown.

We can also be somewhat vague about the line if we can't find an agreeably bright one. We can simply describe the two options and then let implementers decide whether it's a physical object (intentional lower case) or a conceptual grouping.

The disadvantage is that systems need to deal with different choices made by different implementers for the same situation, but hopefully there'll be sufficient discussion that there'll be at least a reasonable consensus that emerges.

Personally, I would draw it the same as @workergnome does, between 3 and 4, though I could be persuaded between 4 and 5 as well. I'll bet there are people who would draw it between 1 and 2, or that everything is a physical object that is part of the physical universe.

**Comment by Conal-Tuohy** [comment]
@azaroth42 
> I think that E19 being used for aggregations is semantically invalid

Except that, it seems to me, you would be OK with accepting a cup-and-saucer as a single `E19 Physical Object` if it had been registered as such in a CMS? It seems to me that your criterion for whether E19 should be used to model an aggregate isn't about the contiguity or non-contiguity of the parts, but about whether the parts had been physically brought together into any kind of proximity?

Taking up @workergnome 's comment above, I would draw the line between 2 and 3. The works actually in an exhibition are definitely a physical aggregation of objects. A plan for an exhibition is is a Conceptual Object. An exhibition catalogue is some kind of Propositional Object. But the objects on display are physical, and the set of those objects, brought together in the gallery, is also physical.

**Comment by azaroth42** [comment]
I would accept cup-and-saucer as a MMO because I'm not religious about it and from the data, we can't distinguish that case from any other. My preference would be that they had their own identities and were brought together in a set, so that if we find that they were originally from totally separate sets, or one is a forgery, or ... then they're just re-conceptually grouped.

I think we have a way forwards -- describe the framework and the ramifications, then let content experts / implementers draw the line where they feel comfortable.

**Comment by Conal-Tuohy** [comment]
@workergnome writes:
> The question becomes where you draw the line? Which side does number 3 fit best into--is it more like the objects considered for the exhibition, or more like a chess set? And if the exhibition or auction lot is virtual, does that change things?

I think it's important to be clear about what exactly is being described; if you are describing an exhibition set as a mental plan; as a catalogue of the items; or as the set of physical items themselves. A virtual exhibition is not a collection of physical objects: it's some kind of conceptual object which contains visual items (or other digital surrogates) which in turn represent the physical objects. If an "auction lot" is a virtual collection (the objects being sold in an auction have not been brought together physically) then the lot is clearly conceptual; the objects themselves obviously don't constitute a physical object collectively. 

- If I merely contemplate the idea of physically bringing a set of objects together, then that idea is not a physical object; it's a conceptual object. 
- If I make a plan to bring the objects together for an exhibition, then that plan is a propositional object which refers to the objects.
- If I write that plan down, or draw it, then the written plan is a man made object which carries the propositional object as its content.
- If I then execute that plan, then the execution is an activity in which the objects are involved, and which produces a new composite physical object which is the set of objects. 

If people want to focus instead on the _conceptual_ entities, and ignore the _physical_ set of objects, then that's fine (there may be a good reason for that focus). But I don't see any reason why a dataset should not also recognise those physical aggregations, _where they exist_, and I don't accept the notion that a composite `E19 Physical Object` is "semantically invalid".

**Comment by azaroth42** [comment]
I agree with the first three bullets, but I still disagree that a new physical object is produced as a result of carrying out the activity. I don't think we're going to reconcile our world views, as I think the disagreement comes from differing philosophies about identity.  At the risk of sounding like Martin, my rationale is below from most concrete to most philosophical.

I don't think that proximity is a reliable indicator.   If I have a set that consists of a desk, an inkwell and a pen, and I loan the inkwell to another institution for an exhibition, that shouldn't change the set, even though part of the set is no longer in the same location as the other parts. The identity of the set is unchanged by changing the location of the members of the set. Or even destroying the members of the set -- the seven wonders of the world is still a coherent set of physical things. 

Or, the inverse, proximity does not make the set into a physical object: my favorite paintings in gallery W2 versus my favorite paintings in the world are both conceptual, even though the paintings in W2 happen to be in the same location.

Also, the actual proximity information may be impossible to know.  Historically, we don't know whether or not all of the objects being auctioned were physically brought together for the auction. At which point we cannot know whether it was a conceptual or physical aggregation.  Or rather ... we know for certain that it was conceptual, and it might also have been physical... and thus I would err on the side of the certainty that it was conceptual.

The notion of being physically brought together is an extremely fuzzy line. I assume that all of the objects in our collection are "brought together", even if they're on loan to an organization around the world.  If we had a Getty campus in Europe (say Getty Paris), then we would still want to say there was one collection of our objects, not two. Or even the Getty Center vs Getty Villa vs our off-site annex for storage and digitization.  The constellation Gemini is, from our perspective, a set of stars that are close together.

To me, the intent is sufficient to constitute identity of a set of physical objects, rather than any particular activity. I can live with the chess set or cup-and-saucer being a MMO, as the intent of creating the (e.g.) chess set is to create a single "thing" which is not complete without all of its components, despite them not being physically attached to each other. You do not add new parts to the set over time, or take them away.  The Production of the chess set is not complete until all of the pieces and the board have been finished. You can reasonably say that you destroyed the chess set. I don't mind the line between 3 and 4, as it's pragmatic.

However, it runs into [Theseus's paradox](https://en.wikipedia.org/wiki/Ship_of_Theseus).  If I, as the artist, over time replace the chess pieces and board squares, then create a new chess set from the recovered parts ... which is the chess set? The easy way to avoid the paradox is by not admitting of a single physical identity over time (four-dimensionalism in the wikipedia article). Instead there are transformations of sets within a context. The conceptual thing "the chess set" at time t1 is made up of the (equally conceptual) set of objects comprising the board + 32 pieces. At t2 there is an activity that transforms that set into a new set comprising board + 31 original pieces and 1 new piece, but it is the same conceptual thing.  Thereby the rebuilt ship is not the same conceptual thing, even if it follows the same form and material.

Which brings me to this conclusion: https://www.slideshare.net/azaroth42/every-identity-its-ontology

**Comment by ajs6f** [comment]
I got me a feeling that I'm only going to make this worse, but here goes:
Perhaps the things-that-have-been-brought-together-for-an-exhibition stand in relationship, but not directly.

We often introduce a "third party" to mediate difficult relationships. Synchrony is the poster child here-- how many times have we introduced an "event" to be the locus relating an actor, something on which that actor acted, etc.?

Perhaps the TTHBBTFAE just aren't a set/collection/whatever-collective-you-like. Perhaps they just have a traceable relationship to a mediating party (the exhibition), and we're trying to "short circuit" that for convenience. But that hazy area to which we're pointing (in @workergnome's list), maybe that's exactly the area where we can't legitimately do that, where the only ultimately effective move is to leave the relationship indirect/mediated.

Or maybe I'm just repeating people now.

**Comment by azaroth42** [comment]
For exhibitions, I agree the model could simply say that there was an activity (the exhibition) that used many objects. The auction lot however is given identity ("Lot 26") making it not just a modeling construct. 

I'll try to document all this in as comprehensible a way as possible :)

**Comment by workergnome** [comment]
And, to bring back the AAC conversation about this topic (which I was trying to find, but haven't yet), the issue is that for a given exhibition, many things are used--the artwork, yes, but also the furniture, the guestbooks, and other objects.  How do we distinguish between the types of use of objects?  For once, there's not even a property-of-a-property class for `P16_used_specific_object`, so we would actually have to describe the activity of selecting an object to be an artwork in an exhibition.  

(We can't use 'type of object', because often an object is, in one context, an exhibition-worthy-object, and in another, just furniture.  See: Dec Arts, or CMOA's vaunted Tupperware collection.)

**Comment by azaroth42** [comment]
Closing in favor of what is documented. I don't think this issue is resolvable, so using editorial fiat.
